### ISSUE TITLE
Can we get some samples?

### ISSUE THREAD

**Issue by bladedsupernova** [NVIDIA/Megatron-LM#10]
Hi!

Out of interest in GPT-2 and the Megatron LM, can we get a idea what the code outputs? I.e some output samples of what the tool actually does, instead of having to run it just to see what it can do.

**Comment by jaredcasper** [comment]
Do you mean text output of the trained model?  If so, you can see some sample output in the appendix of a paper we just put up on arXiv: https://arxiv.org/abs/1909.08053.

**Comment by bladedsupernova** [comment]
Thanks, I see them.
So these are prompt-completions, correct? So it's GPT-2 on steroids haha?

Btw how well do you understand Transformers? I've spoke with many freelancers and collaborators and they seemed to not fully grasp it, none could re-code the Paper from scratch or explain every atom of the complete thing.

**Comment by jaredcasper** [comment]
Yes, for the samples in that paper GPT-2 is the underlying model (the code in this repo can also do BERT models).

After writing this code and training these models from scratch I think those of us working on this project can all say we have a pretty good understanding of transformers. :)  All the information is there in the various papers, but it can take some determination to really understand it all. Now that there are several open source implementations studying the code is a good way to get to the nuts and bolts. Hopefully this code can help a bit!
