### ISSUE TITLE
[BUG] TypeError: get_cpu_offload_context() takes from 0 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by clarence-lee-sheng** [NVIDIA/Megatron-LM#1041]
**Describe the bug**
in megatron/core/transformer/custom_layers/transformer_engine.py L897, there is a conditional checking if the te version is greater than 1.8.0. If it is greater, then pass in 5 arguments to get_cpu_offload_context, however, on inspection of both transformer_engine 1.8 and 1.9, they both only take in 4 arguments, furthermore, the te_version in the latext nvidia image, nvcr.io/nvidia/pytorch:24.07-py3, has transformer_engine version '1.8.0+37280ec', which is evaluated as true when _te_version is evaluated as greater than packaging.version.Version('1.8.0')), this causes the error TypeError: get_cpu_offload_context() takes from 0 to 4 positional arguments but 5 were given

**Comment by 1195343015** [comment]
PR #996

**Comment by clarence-lee-sheng** [comment]
Thank you for bringing it to my attention. My apologies for not noticing that it had been posted earlier.

**Comment by 1195343015** [comment]
You're welcome!
