### ISSUE TITLE
[BUG] No submodule mapping found in .gitmodules for path 'tests/functional_tests/local_recipes'

### ISSUE THREAD

**Issue by lumosity4tpj** [NVIDIA/Megatron-LM#1058]
**Describe the bug**

Because of this submodule: tests/functional_tests/local_recipes, we need to add a .gitmodules, otherwise we will receive an error message 'No submodule mapping found'.

**Comment by ko3n1g** [comment]
Fixed by https://github.com/NVIDIA/Megatron-LM/commit/c14d9874d2c00274d7df2d958c387cebfc1c76f7
