### ISSUE TITLE
Unclear description of ICT pretraining

### ISSUE THREAD

**Issue by hangzhang-nlp** [NVIDIA/Megatron-LM#108]
How to get ICT pre-train data? I didn't find any information about TITLE_DATA_PATH and TEXT_DATA_PATH in pretrain_ict.sh

**Comment by hangzhang-nlp** [comment]
@mpatwary Looking forward to your early reply.

**Comment by mpatwary** [comment]
This is an ongoing work. We plan to share the latest soon.

**Comment by hangzhang-nlp** [comment]
Thanks for your share. but there are still questions to reproduce the results in "End-to-End Training of Neural Retrievers for Open-Domain Question Answering".  Could you release the bert-base(Megatron) or checkpoints in different settings like DPR, Rocketqa.

**Comment by OctoberChang** [comment]
@mpatwary , do you have any plan to release the unsupervised ICT model checkpoint that is pre-trained on the wikipedia corpus?
