### ISSUE TITLE
Any plans to release pretrained model?

### ISSUE THREAD

**Issue by f-dx** [NVIDIA/Megatron-LM#11]
Hello,
Thank you for your project, are you planning to release pretrained models?

**Comment by FurkanGozukara** [comment]
It is impossible for researchers in Turkey to get even 1% of such hardware to train such models

So Please release the trained model so we can experiment on it

**Comment by loretoparisi** [comment]
Is it possibile to release a pre-trained model?

**Comment by 0ctopirate** [comment]
Just to finally put a cap on this...

https://github.com/pytorch/fairseq/blob/master/examples/megatron_11b/README.md

**Comment by loretoparisi** [comment]
@0ctopirate I wonder if it fits in 11GB GPU, or maybe a new 24GB RTX one?

**Comment by jon-barker** [comment]
As mentioned in the readme, there are some pretrained models available through the NGC catalog in addition to the fairseq provided model above. Closing.
