### ISSUE TITLE
How about supporting alternatives to fine-tuning?

### ISSUE THREAD

**Issue by hwijeen** [NVIDIA/Megatron-LM#114]
Hi, thank you for the great library.

Recently, many algorithms are proposed to replace fine-tuning as it incurs too many burdens, especially with huge models like GPT3. Examples include [P-tuning](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjA2dbKqM3xAhXzKaYKHfRiDDwQFjABegQIBxAD&url=https%3A%2F%2Farxiv.org%2Fabs%2F2103.10385&usg=AOvVaw3jtXvJ-0GWxlJmIFjVpd9M) and [LoRA](https://arxiv.org/abs/2106.09685). I personally implemented both on top of Megatron-LM and was able to achieve SOTA accuracy on a number of Korean benchmark datasets (I used model size ranging from 300M to 82B).

How about supporting the algorithms like the above? I think it's an extension of the current `--fine-tune` option, and is a big plus in terms of the practicality of huge models.

**Comment by alex-ht** [comment]
can you share your implementation? thanks!

**Comment by BrightXiaoHan** [comment]
@hwijeen +1

**Comment by wsh2836741** [comment]
+1

**Comment by wsh2836741** [comment]
@hwijeen +1

**Comment by hwijeen** [comment]
Hi, sorry for the delayed response. I won't be able to make a PR as I no longer have access to the code, it was from my previous job. I'd be happy to work together as a side project if people are still interested.

**Comment by hwijeen** [comment]
@alex-ht @BrightXiaoHan @wsh2836741 Could you share what are your use cases? Are you trying to peft-tune GPT models for conditional generation tasks?

And may I ask what made you reopen this issue @jon-barker? Are you working on this?

**Comment by alex-ht** [comment]
hi @hwijeen 
> Are you trying to peft-tune GPT models for conditional generation tasks?

yes.

I found this tutorial, and it seems that NeMo can inject LoRA adapters into megatron-lm model.
https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/lora.ipynb

**Comment by AlpinDale** [comment]
It would be great if Megatron-LM could support PEFT methods, e.g. QLoRA. We're sorely lacking a PEFT trainer with Tensor Parallelism.
