### ISSUE TITLE
The training of T5 using FP16 is unstable

### ISSUE THREAD

**Issue by zhuhong** [NVIDIA/Megatron-LM#115]
We have meet a problem to train T5 using FP16, as shown in the figure below:

![image](https://user-images.githubusercontent.com/5318606/124530351-f2eeb180-de3e-11eb-9c3e-943453d9d132.png)

after check the loss vs loss scale, we find that the loss scale is going down to 1 rapidly. 

![微信图片_20210705191533](https://user-images.githubusercontent.com/5318606/124530586-609add80-de3f-11eb-8b68-d541523659b8.png)

I want to know if there are some strategy to stablize the training process by tuning the parameters about loss scale like its window or min-loss-scale ?

**Comment by yixuan-qiao** [comment]
We also found this problem in our testing, and sometimes it was even hard to get started
