### ISSUE TITLE
Continue Pre-training from a checkpoint with different config

### ISSUE THREAD

**Issue by bugface** [NVIDIA/Megatron-LM#118]
I have a model pre-trained on 10 nodes for 500k steps.  Then, I need to reduce the number of nodes to 5. But after modified the node numbers, start training yields an error:
```
Traceback (most recent call last):
  File "/red/gatortron-phi/workspace/scripts/Megatron-LM/pretrain_bert.py", line 154, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/training.py", line 107, in pretrain
    model, optimizer, lr_scheduler = setup_model_and_optimizer(model_provider)
  File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/training.py", line 282, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, lr_scheduler)
  File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/checkpointing.py", line 263, in load_checkpoint
    lr_scheduler.load_state_dict(state_dict['lr_scheduler'])
  File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/learning_rates.py", line 146, in load_state_dict
    self.warmup_steps = self._check_and_set(self.warmup_steps,
  File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/learning_rates.py", line 122, in _check_and_set
    assert cls_value == sd_value, \
AssertionError: AnnealingLR: class input value 5600000.0 and checkpointvalue 11040000.0 for warmup iterations do not match
```
How should I deal with this issue?

More generic question: if I want to modify more configs like total training steps, dataset, batch size, learning rate but want to continue from an existing checkpoint, how should I do?

Thanks

**Comment by bugface** [comment]
Should I use (--no-load-optim + --no-load-rng) or --finetune?

**Comment by bugface** [comment]
Given a situation: 
I originally set the training step to 1M. After training, I found the model was not converged and I needed to train another 1M step. How should I set-up my config?

**Comment by bugface** [comment]
> I have a model pre-trained on 10 nodes for 500k steps. Then, I need to reduce the number of nodes to 5. But after modified the node numbers, start training yields an error:
> 
> ```
> Traceback (most recent call last):
>   File "/red/gatortron-phi/workspace/scripts/Megatron-LM/pretrain_bert.py", line 154, in <module>
>     pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
>   File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/training.py", line 107, in pretrain
>     model, optimizer, lr_scheduler = setup_model_and_optimizer(model_provider)
>   File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/training.py", line 282, in setup_model_and_optimizer
>     args.iteration = load_checkpoint(model, optimizer, lr_scheduler)
>   File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/checkpointing.py", line 263, in load_checkpoint
>     lr_scheduler.load_state_dict(state_dict['lr_scheduler'])
>   File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/learning_rates.py", line 146, in load_state_dict
>     self.warmup_steps = self._check_and_set(self.warmup_steps,
>   File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/learning_rates.py", line 122, in _check_and_set
>     assert cls_value == sd_value, \
> AssertionError: AnnealingLR: class input value 5600000.0 and checkpointvalue 11040000.0 for warmup iterations do not match
> ```
> 
> How should I deal with this issue?
> 
> More generic question: if I want to modify more configs like total training steps, dataset, batch size, learning rate but want to continue from an existing checkpoint, how should I do?
> 
> Thanks

**Comment by qijiaxing** [comment]
For this problem, just use one of these two command line arguments: `--override-lr-scheduler` or `--use-checkpoint-lr-scheduler`
