### ISSUE TITLE
Collecting Wikipedia Training Data issues

### ISSUE THREAD

**Issue by great-attraction** [NVIDIA/Megatron-LM#12]
Hi!
I'm dealing with the work of your library and I have a misunderstanding of the point Collecting Wikipedia Training Data.
I run command
[python WikiExtractor.py --json enwiki-latest-pages-articles.xml.bz2](url)
and expected get one json file as output ( do I understand correctly that I need an available .json file to start learning the model ?), but got a  folder with many inner folders like AA, AB, AC ..

Could you explain what I'm doing wrong and how I can start training a model?

**Comment by jon-barker** [comment]
You need to convert the extracted .json files into a single .json file to pass to `preprocess_data.py` as described here: https://github.com/NVIDIA/Megatron-LM/tree/main#data-preprocessing

This will process the data into mmap files that can then be used for training.
