### ISSUE TITLE
Document must have 2+ sentences

### ISSUE THREAD

**Issue by Lavenderjiang** [NVIDIA/Megatron-LM#122]
I found that documents must have 2+ sentences to be successfully index mapped (see code [here](https://github.com/NVIDIA/Megatron-LM/blob/90e0a0dd08159e1c95f4f9d99bb8687f327d36c3/megatron/data/helpers.cpp#L331)). This results in issues like empty index map or a hang in creating the mapping (see issue #67, #70). Is it possible to adapt the code to work with single-sentence documents as well?

**Comment by shoeybi** [comment]
If no binary head is provided, the code should work with a single sentence per document

**Comment by seanbenhur** [comment]
Hi @shoeybi I have compiled a large dataset with more than 100 million sentences but I still get this issue, what could be the reason!?
