### ISSUE TITLE
torch.distributed initialization address already in use

### ISSUE THREAD

**Issue by Lavenderjiang** [NVIDIA/Megatron-LM#125]
When running examples/pretrain_bert_distributed.sh, I had the "address already in use" error from this [line](https://github.com/NVIDIA/Megatron-LM/blob/90e0a0dd08159e1c95f4f9d99bb8687f327d36c3/megatron/initialize.py#L183), even after I made sure the address host:port is open. This issue is fixed by removing the world_size and init_method in the init_process group:
``` 
torch.distributed.init_process_group(
            backend=args.distributed_backend,
            rank=args.rank)
```

**Comment by Lyken17** [comment]
Same issue here. Thanks for the information!

**Comment by jackychancjcjcj** [comment]
I remove this two options, and then get stuck. any suggestion?
