### ISSUE TITLE
[QUESTION] NVIDIA Megatron Core 0.9.0 does not have shared_experts.py

### ISSUE THREAD

**Issue by clarence-lee-sheng** [NVIDIA/Megatron-LM#1257]
Dear Megatron-LM maintainers, 

in your 0.9.0 release, you mentioned that shared experts support was released, however, there is currently no shared_experts.py file in mcore r0.9.0 version, may I ask if it is currently missing from your 0.9.0 release?

**Comment by yaox12** [comment]
Shared expert is in the current main branch but not included in 0.9.0 release branch. The release note results in confusing.

**Comment by clarence-lee-sheng** [comment]
In megatron/core/transformer/moe/README.md in main branch it was also mentioned that "MCore v0.9 introduced the shared expert feature. We can enable this feature by setting suitable --moe-shared-expert-intermediate-size.". May I ask if this will be eventually added into mcore-0.9.0 or another release?

**Comment by yaox12** [comment]
No. MCore v0.9 has been finalized and released. It's going to be included in the next release.
