### ISSUE TITLE
Differences in T5 implementation

### ISSUE THREAD

**Issue by unlimblue** [NVIDIA/Megatron-LM#128]
https://github.com/NVIDIA/Megatron-LM/blob/90e0a0dd08159e1c95f4f9d99bb8687f327d36c3/megatron/model/language_model.py#L140

It seems that there is no implementation of `relative_attention_bias` like in [huggingface](https://github.com/huggingface/transformers/blob/790f1c9545f4a83b97bf75640be82b2112c3efe7/src/transformers/models/t5/modeling_tf_t5.py#L188) and [official](https://github.com/tensorflow/mesh/blob/0cb87fe07da627bf0b7e60475d59f95ed6b5be3d/mesh_tensorflow/transformer/transformer_layers.py#L593).

**Comment by yixuan-qiao** [comment]
Some of the other components are also different, such as layer norm, FFN

**Comment by shoeybi** [comment]
What is the difference in FFN?

**Comment by yixuan-qiao** [comment]
the official T5 use relu without bias, the transformation of q,k,v in attention also without bias

**Comment by shoeybi** [comment]
Thanks for the clarification.

**Comment by twoflypig** [comment]
Hi, is there any updates about the difference?

**Comment by daniel-cuturilo** [comment]
So relative positional embedding is not implemented within Megatron, as opposed to the huggingface/official implementation. I wonder what is the reason behind this?

**Comment by exitxingling** [comment]
Is there any updates about the difference?
