### ISSUE TITLE
Tensorboard logging `last_rank` vs `torch.distributed.get_rank() == 0`

### ISSUE THREAD

**Issue by VictorSanh** [NVIDIA/Megatron-LM#129]
My understanding of [this line](https://github.com/NVIDIA/Megatron-LM/blob/90e0a0dd08159e1c95f4f9d99bb8687f327d36c3/megatron/global_vars.py#L135) is that it ensures that only the last rank process has a non-None `_GLOBAL_TENSORBOARD_WRITER`.
However, [this line](https://github.com/NVIDIA/Megatron-LM/blob/90e0a0dd08159e1c95f4f9d99bb8687f327d36c3/megatron/training.py#L538) expect the first rank process to log some speed-related metrics, so it is actually never logged because the first rank process doesn't have a TB writer...
Could you confirm, the correct if condition should be `if writer and is_last_rank():` which would be consistent with the previous TB logs in the same `training.py`?

**Comment by shoeybi** [comment]
Thanks for reporting this issue. This is definitely a bug, it is fixed, and will be pushed in the next release.
