### ISSUE TITLE
Unitialized data usage

### ISSUE THREAD

**Issue by dzabraev** [NVIDIA/Megatron-LM#130]
Here unitialized tensor is allocated, then
in the next line this tensor used in baddbmm operation. `torch.zeros` have to be used in this place.
Also comment in the first line confuses me. You preallocate tensor for output, but
do not pass it to `out` argument. Instead use it as additive component.

It is unsafe to use unitialized data as numbers (even you multiply it by zero), because not all sequence of bytes is valid float number. Just a small example how to get Nan 

```python
unitialized_data = b'\xff\xff\xff\xff'
np.frombuffer(unitialized_data, dtype=np.float32) * np.float32(0) # == array([nan], dtype=float32)
```

https://github.com/NVIDIA/Megatron-LM/blob/90e0a0dd08159e1c95f4f9d99bb8687f327d36c3/megatron/model/transformer.py#L262-L275

**Comment by kvareddy** [comment]
Hey dzabrev, 

Please refer to baddbmm documentation: https://pytorch.org/docs/stable/generated/torch.baddbmm.html

It clearly states that ```If beta is 0, then input will be ignored, and nan and inf in it will not be propagated.```

Moreover, we do not want the operation to happen inplace in order to enable the backprop.
