### ISSUE TITLE
[QUESTION] recompute activation rather consume more memory while backward (OOM)

### ISSUE THREAD

**Issue by KookHoiKim** [NVIDIA/Megatron-LM#1300]
**Your question**
I am struggling with OOM issue and I found that recompute activations (activation checkpointing) is a great option for me. 
My case is that additional embedding module passes large batch inputs ( differ with args.micro batch) , making huge activation memory. 
Recompute activation seems work well while forwarding but OOM is still occurred processing backward. 
When TP=2, PP=2 without recomputing, the model training works well. (first stage 79G, second stage 71G)
However, when i add recompute options like below, OOM suddenly occurs while backwarding. 

```
     --recompute-granularity full \
     --recompute-method uniform \
     --recompute-num-layers 1 \
```

Does anyone have any idea about memory consumption of recomputation? 
Thanks.

**Comment by eliird** [comment]
Did you find an answer? It should reduce the memory usage but is not reducing memory at all.

**Comment by eliird** [comment]
https://arxiv.org/pdf/[2205.05198](https://arxiv.org/pdf/2205.05198) This is the original paper and according to it memory usage should reduce by a lot but seems to have no effect
