### ISSUE TITLE
[BUG] Source for releases 0.8.0 and 0.9.0 are not available

### ISSUE THREAD

**Issue by dmgcsilva** [NVIDIA/Megatron-LM#1307]
**Describe the bug**
The release files for version 0.8.0 and 0.9.0 are not available.

**To Reproduce**
Go to https://github.com/NVIDIA/Megatron-LM/releases
Try to download the source for version 0.8.0 or 0.9.0
See 404 page

**Expected behavior**
Not 404

**Stack trace/logs**
NA

**Comment by plegresl** [comment]
Hi, are you referring to the "Source code (zip)" and "Source code (tar.gz)" links for each release? The full links are:

https://github.com/NVIDIA/Megatron-LM/archive/refs/tags/core_r0.8.0.zip
https://github.com/NVIDIA/Megatron-LM/archive/refs/tags/core_r0.8.0.tar.gz
https://github.com/NVIDIA/Megatron-LM/archive/refs/tags/core_r0.9.0.zip
https://github.com/NVIDIA/Megatron-LM/archive/refs/tags/core_r0.9.0.tar.gz

and as far as I can tell all of them work.

**Comment by dmgcsilva** [comment]
Hi, at the time they were not working. It appears to be fixed now.
