### ISSUE TITLE
importing new features from the BigScience Megatron-LM fork

### ISSUE THREAD

**Issue by stas00** [NVIDIA/Megatron-LM#137]
At https://github.com/bigscience-workshop/Megatron-DeepSpeed new and improved data pre-processing scripts have been created. Most are documented here: https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/10

@jaredcasper and his team are definitely interested in these new features, but it might be difficult for the Megatron team to easily import those complete new features, as the code base is starting to diverse, so perhaps the original creators would be kind enough and have extra resources to import those into Megatron via PR.

At the moment this call is primarily for @adammoody and @thomasw21 who created the lion shared of those contributions.

Guys, I wonder if it'd be easier to make one large PR that includes both of your contributions? I am thinking that as there are several shared files between both of your works. But I trust your judgment should you be moved to do this extra work.

If you do that please tag: @jaredcasper and @shoeybi on your PR. I think @shoeybi will be the main contact.

Thank you all!

**Comment by shoeybi** [comment]
Thanks everyone for the new features. We prefer smaller PRs as it is easier to review, comment, and test them.
