### ISSUE TITLE
What is ring_exchange? 

### ISSUE THREAD

**Issue by vycezhong** [NVIDIA/Megatron-LM#141]
I am reading the code and get confused with this API. 

https://github.com/NVIDIA/Megatron-LM/blob/3860e995269df61d234ed910d4756e104e1ab844/megatron/p2p_communication.py#L98-L102

I cannot find this function in PyTorch.  Is this a function used internally?

**Comment by shoeybi** [comment]
This is an internal prototype. Please ignore it.
