### ISSUE TITLE
the figure in the paper seems wrong

### ISSUE THREAD

**Issue by jasperzhong** [NVIDIA/Megatron-LM#142]
https://arxiv.org/abs/2104.04473

![image](https://user-images.githubusercontent.com/25879526/132114881-ca840831-da4d-4b71-96aa-f2aaedaf79d7.png)

In Figure 4 (Top), for example, forward pass 3 in device 3 cannot be executed until device 3 receives the gradient w.r.t the first microbatch from device 4. The right position of forward pass 3 in device 3 should be right after the backward pass 1 in device 3. 

https://github.com/NVIDIA/Megatron-LM/blob/3860e995269df61d234ed910d4756e104e1ab844/megatron/schedules.py#L431

**Comment by whaor** [comment]
Yes indeed, according to the code:
The F3, F4 of Device3 should be postponed to the idle time behind B1, B2 respectively.
The F4 of Device2 should be postponed to the idle time behind B1.
But this don't affect the overall latency.
