### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'model_parallel_size'

### ISSUE THREAD

**Issue by abdul756** [NVIDIA/Megatron-LM#145]
When i am running the preprocess.py  file its showing error Namespace' object has no attribute 'model_parallel_size'

!python Megatron-LM/tools/preprocess_data.py \
       --input 'manifest_file.json'\
       --output-prefix 'my_t5' \
       --vocab 'vocab/vocab.txt' \
       --dataset-impl mmap \
       --tokenizer-type BertWordPieceLowerCase \
       --workers 1 \
       --split-sentences

Error:
Opening manifest_file.json
> building BertWordPieceLowerCase tokenizer ...
Traceback (most recent call last):
  File "Megatron-LM/tools/preprocess_data.py", line 203, in <module>
    main()
  File "Megatron-LM/tools/preprocess_data.py", line 155, in main
    tokenizer = build_tokenizer(args)
  File "/opt/conda/lib/python3.6/site-packages/megatron/tokenizer/tokenizer.py", line 48, in build_tokenizer
    args)
  File "/opt/conda/lib/python3.6/site-packages/megatron/tokenizer/tokenizer.py", line 59, in _vocab_size_with_padding
    args.model_parallel_size
AttributeError: 'Namespace' object has no attribute 'model_parallel_size'

**Comment by jaredcasper** [comment]
This happens due to mixing the installed megatron package with the repo checkout. If you uninstall the megatron package it should pick up the tokenizer in the repo and work as expected.

**Comment by abdul756** [comment]
Thanks for the help . Can you guide me how to do this is in a jupyter notebook

**Comment by abdul756** [comment]
!python preprocess_data.py \  --input  manifest_file.json \
--output-prefix 'my_t5' \
--vocab-file 'vocab/vocab.txt' \
--dataset-impl mmap \
--tokenizer-type BertWordPieceCase \
--keep-newlines \
--workers 8 \
--split-sentences

how to resolve this

  File "preprocess_data.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by jaredcasper** [comment]
Sorry, I'm not familiar with jupyter

**Comment by abdul756** [comment]
> Sorry, I'm not familiar with jupyter
Fine , thank you so much for the help
