### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`, CUDA error: device-side assert triggered, 

### ISSUE THREAD

**Issue by abdul756** [NVIDIA/Megatron-LM#146]
When i am running the pretrain_bert.py script 
NK=0
WORLD_SIZE=1
DATA_PATH='my_bert_sentence1/my_bert_sentence_text_sentence'
CHECKPOINT_PATH='checkpoints'

!python -m torch.distributed.launch Megatron-LM/pretrain_bert.py \
       --num-layers 2 \
       --hidden-size 16 \
       --num-attention-heads 16 \
       --micro-batch-size 8 \
       --global-batch-size 16 \
       --seq-length 512 \
       --max-position-embeddings 512 \
       --train-iters 10 \
       --lr-decay-iters 100 \
       --save $CHECKPOINT_PATH \
       --load $CHECKPOINT_PATH \
       --data-path $DATA_PATH \
       --vocab-file vocab.txt \
       --no-masked-softmax-fusion \
       --data-impl mmap \
       --split 10 \
       --lr 0.0001 \
       --min-lr 0.00001 \
       --lr-decay-style linear \
       --lr-warmup-fraction .01 \
       --weight-decay 1e-2 \
       --clip-grad 1.0 \
       --log-interval 100 \
       --save-interval 10000 \
       --eval-interval 1000 \
       --eval-iters 10 \
       --fp16

I am facing the error
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`, CUDA error: device-side assert triggered, 

Please help me

**Comment by hyunwoongko** [comment]
kill your all existed python processes about megatron.

**Comment by QwQxwqQwQ** [comment]
I'm having the same issue. How do you solve this problem?
