### ISSUE TITLE
is fused layernorm really better?

### ISSUE THREAD

**Issue by hyunwoongko** [NVIDIA/Megatron-LM#150]
https://github.com/pytorch/pytorch/commit/8b87f9a5107e8b3c4f87d5297af698bb55838d81#diff-f12c726e3e8cd2b4768f8984fef27059

I think we don't need to use apex fused layernorm anymore. 
torch layernorm is better. what do you think about this?

cc. @jaredcasper @shoeybi

**Comment by lostmsu** [comment]
In [this pull request](https://github.com/NVIDIA/apex/pull/1049) `apex` maintainer pretty much says that `apex` is deprecated. MegatronLM should remove its dependency on `apex` completely.
