### ISSUE TITLE
Usage of --use-cpu-initialization flag

### ISSUE THREAD

**Issue by ParamsRaman** [NVIDIA/Megatron-LM#157]
Hi,

I have a few questions regarding the `--use-cpu-initialization` flag in Megatron.

1. Can you explain the use of this flag? I see the arguments description for it, but it is not clear to me under which situation would one use this flag?
   
```
group.add_argument('--lazy-mpu-init', type=bool, required=False,
                       help='If set to True, initialize_megatron() '
                       'skips DDP initialization and returns function to '
                       'complete it instead.Also turns on '
                       '--use-cpu-initialization flag. This is for '
                       'external DDP manager.' )
group.add_argument('--use-cpu-initialization', action='store_true',
                   default=None, help='If set, affine parallel weights '
                   'initialization uses CPU' )

```

2. This flag seems to be used in the constructor for several model parallel classes such as VocabParallelEmbedding, ParallelEmbedding, RowParallelLinear and ColumnParallelLinear defined in https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/mpu/layers.py . Based on whether this flag is set, two sets of weights are initialized - self.weight and self.master_weight as shown here: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/mpu/layers.py#L391,L404 . 
Could you explain why additional master_weight is used?

3. In the unit tests for layers.py I see that master_weight is accessed - https://github.com/NVIDIA/Megatron-LM/blob/b31e1296354e979722627a6c4dedafe19b51fa97/megatron/mpu/tests/test_layers.py#L284 
Does this mean the use cpu initialization flag has to bet set while running the unit tests? 

Appreciate any clarification on this. Thanks!

**Comment by jaredcasper** [comment]
The `--use-cpu-initialization` is primarily used for testing, but it can also be used in the case that you want to initialize things on a node with no GPU (some tests can be run without GPU, various tools, etc.).  The master_weight returned is only used for testing.
