### ISSUE TITLE
ImportError: cannot import name 'Tokenizer' from 'tokenizer'

### ISSUE THREAD

**Issue by Neleon** [NVIDIA/Megatron-LM#162]
I am preparing the data for GPT training according with the Megatron-LM project's README.md at path "Megatron-LM/tools/openwebtext/tools", I run the cleanup_dataset.py, the code in it:
import sys

from tokenizer import Tokenizer

MIN_DOCUMENT_LENGHT = 128
I encountered the below error:
ImportError: cannot import name 'Tokenizer' from 'tokenizer'
I want to know where can I find the tokenizer lib, someone can give me some tips, thx!

**Comment by jaewonalive** [comment]
Hi, I'm having the same problem. Did you solve the problem? Please, give me a hint! Thanks!

**Comment by weikeduo1** [comment]
我也碰到了同样的问题，请问有人已经解决了吗？

**Comment by wuhouming** [comment]
The 'tokenizer' in 'from tokenizer import Tokenizer' is not a lib.

And fixes are [Issue33](https://github.com/NVIDIA/Megatron-LM/issues/33) and [Issue89](https://github.com/NVIDIA/Megatron-LM/pull/89).


> 我也碰到了同样的问题，请问有人已经解决了吗？

**Comment by jon-barker** [comment]
Closing. Duplicate of: https://github.com/NVIDIA/Megatron-LM/issues/33
