### ISSUE TITLE
AttributeError: 'IndexedDataset' object has no attribute 'get_doc_idx’

### ISSUE THREAD

**Issue by whulxl** [NVIDIA/Megatron-LM#163]
I am preparing the data for GPT training according with the Megatron-LM project's（tag 1.1） README.md at path "Megatron-LM/tools/openwebtext/tools", I run the preprocess_dataset.py, the code in it:
python3 tools/preprocess_data.py --input data/corpus/test.json --output-prefix my-bert --vocab data/tokenizer/bert/bert-large-uncased-vocab.txt --tokenizer-type BertWordPieceLowerCase --split-sentences --dataset-impl cached

i use “cached” type of dataset-impl
but when i run 

python3 pretrain_bert.py \
       --num-layers 12 \
       --hidden-size 1024 \
       --num-attention-heads 16 \
       --batch-size 4 \
       --seq-length 512 \
       --max-position-embeddings 512 \
       --train-iters 2000000 \
       --save $CHECKPOINT_PATH \
       --load $CHECKPOINT_PATH \
       --data-path $DATA_PATH \
       --vocab-file data/tokenizer/bert/bert-large-uncased-vocab.txt \
       --data-impl cached\
       --split 949,50,1 \
       --distributed-backend nccl \
       --lr 0.0001 \
       --min-lr 0.00001 \
       --lr-decay-style linear \
       --lr-decay-iters 990000 \
       --weight-decay 1e-2 \
       --clip-grad 1.0 \
       --warmup .01 \
       --log-interval 100 \
       --save-interval 10000 \
       --eval-interval 1000 \
       --eval-iters 10 \
       --fp16

I encountered the below error:
AttributeError: 'IndexedDataset' object has no attribute 'get_doc_idx'
I want to know how can I fix the error, someone can give me some tips, thx!

**Comment by MayDomine** [comment]
I met the same problem,did you fix this?
