### ISSUE TITLE
<Signals.SIGSEGV: 11> occured in multiple nodes pretraing

### ISSUE THREAD

**Issue by xiongjun19** [NVIDIA/Megatron-LM#166]
Hi, Dear!
   I'm trying to pretraing bert in two nodes! I used the docker image pulled from nvcr.io/nvidia/pytorch:20.12-py3 as my evirnoment, I have managed to run pretraining in a node with single T4 card. but when I trying to train the same model with two nodes both with single T4 card, I always getting the following Error:
      
![image](https://user-images.githubusercontent.com/53548403/142823224-17d28cd4-0f21-4944-ad80-8edf15e0cdca.png)

but if I setting nnodes as one all things goes well? can anyone give me some guide? thanks very much

**Comment by jaeyong-song** [comment]
In my case, it was due to firewall setting. Setting your NIC into 'trusted' zone in firewall may help you from this error.
