### ISSUE TITLE
There is a difference in the calculation of num_warmup_microbatches 

### ISSUE THREAD

**Issue by unlimblue** [NVIDIA/Megatron-LM#169]
In interleaved-1F1B：

https://github.com/NVIDIA/Megatron-LM/blob/b31e1296354e979722627a6c4dedafe19b51fa97/megatron/schedules.py#L222-L223

but in 1F1B:

https://github.com/NVIDIA/Megatron-LM/blob/b31e1296354e979722627a6c4dedafe19b51fa97/megatron/schedules.py#L531-L533

what is the purpose of this diff?

**Comment by jaredcasper** [comment]
@deepakn94 Do you remember why interleaved has the `* 2`?

**Comment by deepakn94** [comment]
We are executing the schedules shown in the figure below (top figure is 1F1B, bottom figure is 1F1B + interleaved).

![image](https://user-images.githubusercontent.com/2724038/144116083-6e5b9875-349b-4091-8b28-16d04982ab34.png)

The purpose of the warmup microbatches is to admit enough work into the pipeline so that every worker is busy in steady state.

**Comment by unlimblue** [comment]
@deepakn94 So a better understanding is that in interleaved mode, the formula of `num_warmup_microbatches` is expressed as:
```python
num_warmup_microbatches = \ 
     (pipeline_parallel_size - pipeline_parallel_rank - 1) * num_model_chunks
``` 
.

**Comment by deepakn94** [comment]
Not quite. The number of warmup microbatches in interleaved mode is this (which is what the implementation does as well):

```
num_warmup_microbatches = ((pipeline_parallel_size - pipeline_parallel_rank - 1) * 2) +
    ((num_model_chunks - 1) * pipeline_parallel_size)
```

For the example timeline above, `pipeline_parallel_size = 4, num_model_chunks = 2`. Which is how we get 10 warmup microbatches on rank 0, 8 on rank 1, 6 on rank 2, and 4 on rank 3.

**Comment by unlimblue** [comment]
In summary, if I want to expand to arbitrary model chunks, I need modify the formula of `num_warmup_microbatches` to:
```python
num_warmup_microbatches = ((pipeline_parallel_size - pipeline_parallel_rank - 1) * num_model_chunks) +
    ((num_model_chunks - 1) * pipeline_parallel_size)
```
.

In addition, I also noticed that the estimation formula of pipeline bubble time fraction mentioned in the [paper](https://arxiv.org/pdf/2104.04473.pdf) is: <img src="https://render.githubusercontent.com/render/math?math=\frac{1}{v}\frac{p-1}{m}">， where m is the number of microbatches in a batch, p is the number of pipeline stages and v is `num_model_chunks`. 

Increasing v (`num_model_chunks`) will reduce bubble time fraction, but will introduce more inter-stage communication. 

So, 
- setting `num_model_chunks` to 2 is the optimal empirical value obtained by your actual experiments? 
- is this value recommended for different models (our customized models)? Or we need to analyze the specific situation.

**Comment by deepakn94** [comment]
No, the formula I posted above already takes into account `num_model_chunks`. The `*2` comes from the fact that we need 2 more warmup microbatches in the first rank compared to the second, and second compared to the third, and so on (which is why rank 0 needs 10 warmup microbatches, rank 1 needs 8, etc.).

For an arbitrary `num_model_chunks`, the number of warmup microbatches is:
```
num_warmup_microbatches = ((pipeline_parallel_size - pipeline_parallel_rank - 1) * 2) +
    ((num_model_chunks - 1) * pipeline_parallel_size)
```

You are right that increasing the number of model chunks decreases the size of the pipeline bubble, but increases the amount of in-pipeline communication. The optimal value is model- and hardware-dependent and is not 2 for all deployments. You should play around with this a bit for your specific situation.

**Comment by unlimblue** [comment]
Thanks for your clarification! What I understand is that the purpose of this `*2` is, when the pipeline parallel executes to the steady state, compared to without `*2`, the timeline of all devices is shifted to the right by one forward calculation time, so that you can use `send_forward_backward_recv_forward_backward` to make full use of the communication bandwidth as much as possible. And this operation will not change the bubble ratio.

In addition, by analyzing the timeline in the 1F1B mode, when the timeline is shifted to the right by one forward calculation time, which can also be optimized for communication bandwidth, and the bubble ratio has not changed.

+ without `*2`
   ![image](https://user-images.githubusercontent.com/16875768/144389953-b1aebef5-9e87-4a8e-9809-eb8a9d2ce57b.png)

+ with `*2`
   ![image](https://user-images.githubusercontent.com/16875768/144390143-7f140002-7215-458c-b054-cd53970b1bc3.png)

Is the above approach reasonable?

**Comment by deepakn94** [comment]
Yup, that's correct! Good analysis.

And yes, you could use the same approach with the default 1F1B approach as well. Note that there is added memory footprint from doing this though (as was the case with the interleaved schedule as well).

**Comment by deepakn94** [comment]
I forgot to add one thing: without the `*2` in the interleaved schedule, it was unclear how to schedule communication when the model wraps around. For example, consider the forward pass of the second chunk of microbatch 5. When should rank 3 send the intermediate forward tensor to rank 0 if we use the `without *2` schedule?

**Comment by unlimblue** [comment]
This question gave me a clearer understanding of the reason why the schedule of interleaved-1F1B and 1F1B is so different. 
1. use 1F1B schedule to get the timeline of interleaved-1F1B:
![image](https://user-images.githubusercontent.com/16875768/144572077-2f5d3144-99a6-4e59-baf9-b477510c8315.png)
2. in order to solve the second chunk of microbatch 5 problem, we need to shift all forwards to the left to start the recv operation of chunk 2 as soon as possible:
![image](https://user-images.githubusercontent.com/16875768/144572191-8cee2a88-8dde-4555-ae85-8b21f4afdd35.png)
3. due to the limitation of in-pipeline communication of microbatch 2 forward, middle part of timeline need to be shifted to the right:
![image](https://user-images.githubusercontent.com/16875768/144572289-c06cbd7b-21c9-43f2-b84b-8c0d156e689a.png)
4. after all other ranks have done the same processing, our timeline is the same as interleaved schedule:
![image](https://user-images.githubusercontent.com/16875768/144572419-ec07cd16-1c17-4fd6-8ecf-1497ac7d14f7.png)

**Comment by deepakn94** [comment]
Yup, exactly!

**Comment by Fword4u** [comment]
Hi, after checked all content above, I still have a little question: will the microbatch 5 problem in `without *2` schedule still be a problem if we use pytorch's `isend/irecv` interface or just do p2p communication in another CUDA stream?
