### ISSUE TITLE
Add support of lazy dataloader?

### ISSUE THREAD

**Issue by Yijia-Xiao** [NVIDIA/Megatron-LM#170]
Hi, I have been using this great framework for a while. However, it seems that the latest version no longer supports lazy-dataloader. Would you have any plan to add this feature? Because the pre-training corpus could be giant and too big to be stored as a single file.

Thank you!

**Comment by jaredcasper** [comment]
There is no plan to bring back a lazy loader.

You can list multiple datasets in the --data-path argument, see the format in the help string here: https://github.com/NVIDIA/Megatron-LM/blob/d41696840ed0a7edb7e0499eb82a48ae112d9bb3/megatron/arguments.py#L703-L707
If they all have the same weight it is functionally the same as concatenating all the input data paths.

**Comment by Yijia-Xiao** [comment]
Got it. Thank you :-)
