### ISSUE TITLE
Is there any problem in my pretrain_gpt.sh? The AssertionError: last epoch number of samples exceeded max value.

### ISSUE THREAD

**Issue by Henry-Avery** [NVIDIA/Megatron-LM#176]
My configuration is only one single server with single P6000 GPU，and use the recommend docker container in Github.

And I use 1k text sample, correctly process my data in json file , maybe the problem is caused by the lack of data?

my train script is as follow:  

```
export MASTER_ADDR=localhost
export MASTER_PORT=5678

CHECKPOINT_PATH=checkpoints/gpt2_34m_maybe
VOCAB_FILE="/workspace/megtron/Megatron-LM-main/gpt2-vocab.json"
MERGE_FILE="/workspace/megtron/Megatron-LM-main/gpt2-merges.txt"
DATA_PATH=my-gpt2_text_document

GPT_ARGS="--num-layers 4 \
          --hidden-size 1024 \
          --num-attention-heads 1 \
          --seq-length 1024 \
          --max-position-embeddings 1024 \
          --micro-batch-size 4 \
          --global-batch-size 8 \
          --lr 0.00015 \
          --train-iters 500000 \
          --lr-decay-iters 320000 \
          --lr-decay-style cosine \
          --vocab-file $VOCAB_FILE \
          --merge-file $MERGE_FILE \
          --lr-warmup-fraction .01 \
          --fp16"

OUTPUT_ARGS="--log-interval 10 \
             --save-interval 500 \
             --eval-interval 100 \
             --eval-iters 10 \
             --activations-checkpoint-method uniform"

python /workspace/megtron/Megatron-LM-main/pretrain_gpt.py \
       $GPT_ARGS \
       $OUTPUT_ARGS \
       --save $CHECKPOINT_PATH \
       --load $CHECKPOINT_PATH \
       --data-path $DATA_PATH \
```

and the log is very long,

`  openai_gelu ..................................... False
  optimizer ....................................... adambin  pretrain_ict.py       tasks                  yyt_preprocess_data_gpt2.sh
  override_lr_scheduler ........................... Falsedx  pretrain_t5.py        testMegatronData.json  yyt_pretrain_gpt.sh
  train_iters ..................................... 1000
  train_samples ................................... None
  use_checkpoint_lr_scheduler ..................... False
  use_contiguous_buffers_in_local_ddp ............. True
  use_cpu_initialization .......................... None
  use_one_sent_docs ............................... False
  merge_file ...................................... gpt2-merges.txt
  micro_batch_size ................................ 4
  min_loss_scale .................................. 1.0ervocab.json
  min_lr .......................................... 0.01
  mmap_warmup ..................................... Falsegpt2_text_document']
  no_async_tensor_model_parallel_allreduce ........ Falsee-
  num_layers_per_virtual_pipeline_stage ........... Nonel
  num_workers ..................................... 2onee
  onnx_safe ....................................... Nonesize: 50304)
  openai_gelu ..................................... False
  optimizer ....................................... adam
  override_lr_scheduler ........................... False
  params_dtype .................................... torch.float16
  patch_dim ....................................... 16neining.py", line 96, in pretrain
  pipeline_model_parallel_size .................... 1one 30, 1r,
  pipeline_model_parallel_split_rank .............. Noneeialize.py", line 82, in initialize_megatron
  query_in_block_prob ............................. 0.1e
  rampup_batch_size ............................... Noneeialize.py", line 60, in finish_mpu_init
  rank ............................................ 0ruee
  reset_attention_mask ............................ Falseialize.py", line 180, in _initialize_distributed
  reset_position_ids .............................. FalsePETokenizer
  retriever_report_topk_accuracies ................ []00h.float161 (nvidia pytorch container paired with v1.11). Defaulting to no_persist_layer_norm=True
  retriever_score_scaling ......................... False--
  retriever_seq_length ............................ 256seributed/rendezvous.py", line 182, in _env_rendezvous_handler
  sample_rate ..................................... 1.0torch v1.11 (nvidia pytorch container paired with v1.11). Defaulting to no_persist_layer_norm=True
  vocab_file ...................................... gpt2-vocab.json
  weight_decay .................................... 0.01  world_size ...................................... 1
-------------------- end of arguments ---------------------setting number of micro-batches to constant 2
> building GPT2BPETokenizer tokenizer ...
 > padded vocab (size: 50257) with 47 dummy tokens (new size: 50304)
> initializing torch distributed ...
  vocab_file ...................................... gpt2-vocab.json
  weight_decay .................................... 0.01
  world_size ...................................... 1-------------------- end of arguments ---------------------setting number of micro-batches to constant 2> building GPT2BPETokenizer tokenizer ... > padded vocab (size: 50257) with 47 dummy tokens (new size: 50304)> initializing torch distributed ...> initializing tensor model parallel with size 1
> initializing pipeline model parallel with size 1  weight_decay .................................... 0.01  world_size ...................................... 1-------------------- end of arguments ---------------------setting number of micro-batches to constant 2> building GPT2BPETokenizer tokenizer ... > padded vocab (size: 50257) with 47 dummy tokens (new size: 50304)> initializing torch distributed ...> initializing tensor model parallel with size 1> initializing torch distributed ...> setting random seeds to 1234 ...
> setting random seeds to 1234 ...> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234> compiling dataset index builder ...make: Entering directory '/workspace/megtron/Megatron-LM-main/megatron/data'  vocab_file ...................................... gpt2-vocab.json  weight_decay .................................... 0.01  world_size ...................................... 1-------------------- end of arguments ---------------------setting number of micro-batches to constant 2> building GPT2BPETokenizer tokenizer ... > padded vocab (size: 50257) with 47 dummy tokens (new size: 50304)> initializing torch distributed ...> initializing tensor model parallel with size 1> initializing pipeline model parallel with size 1> setting random seeds to 1234 ...> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234> compiling dataset index builder ...make: Entering directory '/workspace/megtron/Megatron-LM-main/megatron/data'g++ -O3 -Wall -shared -std=c++11 -fPIC -fdiagnostics-color -I/opt/conda/include/python3.8 -I/opt/conda/lib/python3.8/site-packages/pybind11/include helpers.cpp -o helpernux-gnu.somake: Leaving directory '/workspace/megtron/Megatron-LM-main/megatron/data'
>>> done with dataset index builder. Compilation time: 7.327 seconds> compiling and loading fused kernels ...Detected CUDA files, patching ldflagsEmitting ninja build file /workspace/megtron/Megatron-LM-main/megatron/fused_kernels/build/build.ninja...Building extension module scaled_upper_triang_masked_softmax_cuda...Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)[1/3] c++ -MMD -MF scaled_upper_triang_masked_softmax.o.d -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPIBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -isystem /opt/conda/lib/python3.8/site-packages/torch/include -isystem /opt/conda/lib/python3.8/site-paorch/csrc/api/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.8/site-packages/torch/include/THC -isystem /usr/lotem /opt/conda/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -c /workspace/megtron/Megatron-LM-main/megatron/fused_kernels/scaled_upper_triang_masked_upper_triang_masked_softmax.o 
[2/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -isystem /opt/conda/lib/python3.8/site-packages/torch/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/torchstem /opt/conda/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem hon3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-rele=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALFNO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -std=c++14 -c /workspace/megtron/Megatron-LM-main/megatron/fuse_triang_masked_softmax_cuda.cu -o scaled_upper_triang_masked_softmax_cuda.cuda.o [3/3] c++ scaled_upper_triang_masked_softmax.o scaled_upper_triang_masked_softmax_cuda.cuda.o -shared -L/opt/conda/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cudauda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o scaled_upper_triang_masked_softmax_cuda.so
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
[2/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=scaled_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"__BUILD_ABI=\"_cxxabi1013\" -isystem /opt/conda/lib/python3.8/site-packages/torch/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/incda/lib/python3.8/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/inBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpe_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ [3/3] c++ scaled_masked_softmax.o scaled_masked_softmax_cuda.cuda.o -shared -L/opt/conda/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda [2/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_mix_prec_layer_norm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIBND11_BUILD_ABI=\"_cxxabi1013\" -isystem /opt/conda/lib/python3.8/site-packages/torch/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api
 > elasped time to build and save shuffle-idx mapping (seconds): 0.000984
  no_persist_layer_norm ........................... Truelen_indexmap_8000ns_128sl_1234s_doc_idx.npy
  no_save_optim ................................... Noneltrain_indexmap_8000ns_128sl_1234s_sample_idx.npy
  no_save_rng ..................................... Nonee_train_indexmap_8000ns_128sl_1234s_shuffle_idx.npy
  num_attention_heads ............................. 1one
  num_channels .................................... 3alse
  num_classes ..................................... 1000
  num_layers ...................................... 4one indices on rank 0 ...
  num_layers_per_virtual_pipeline_stage ........... None of number of samples per epoch (56), setting separate_last_epoch to True
  num_workers ..................................... 2024ds): 0.000463
  onnx_safe ....................................... Nonee
  openai_gelu ..................................... False
  optimizer ....................................... adam
  override_lr_scheduler ........................... False
  params_dtype .................................... torch.float16
  patch_dim ....................................... 16neconds): 0.000296
  pipeline_model_parallel_size .................... 1alse04) ...
  pipeline_model_parallel_split_rank .............. Noneeconds): 0.000271
  query_in_block_prob ............................. 0.1seid_indexmap_880ns_128sl_1234s_doc_idx.npy
  rampup_batch_size ............................... None_valid_indexmap_880ns_128sl_1234s_sample_idx.npy
  rank ............................................ 0alse_valid_indexmap_880ns_128sl_1234s_shuffle_idx.npy
  reset_attention_mask ............................ False
  reset_position_ids .............................. False
  retriever_report_topk_accuracies ................ []1
  retriever_score_scaling ......................... Falseindices on rank 0 ...
  retriever_seq_length ............................ 256se
  sample_rate ..................................... 1.0eorm
  save ............................................ checkpoints/gpt2_345m
  save_interval ................................... 500aining.py", line 134, in pretrain
  scatter_gather_tensors_in_pipeline .............. True9
  seed ............................................ 12348ning.py", line 884, in build_train_valid_test_data_iterators
  seq_length ...................................... 1024edatasets_provider(
  sgd_momentum .................................... 0.92datasets_provider
  short_seq_prob .................................. 0.1sedatasets(
  split ........................................... 969, 30, 1dataset.py", line 38, in build_train_valid_test_datasets
  tensor_model_parallel_size ...................... 112[0],
  tensorboard_dir ................................. None5/gpt_dataset.py", line 118, in _build_train_valid_test_datasets
  tensorboard_log_interval ........................ 1one
  tensorboard_queue_size .......................... 1000kpoints/gpt2_345m, line 110, in build_dataset
  titles_data_path ................................ Nonee
  tokenizer_type .................................. GPT2BPETokenizert.py", line 152, in __init__
  train_itera_ids ................................. 0000uild_index_mappings(
  vocab_file ...................................... gpt2-vocab.jsonet.py", line 242, in _build_index_mappings
  weight_decay .................................... 0.01eh + 1), \
  world_size ...................................... 1rueeparallel size: 1, pipeline-model-parallel size: 1 
-------------------- end of arguments ---------------------
setting number of micro-batches to constant 2...... Falserch v1.11 (nvidia pytorch container paired with v1.11). Defaulting to no_persist_layer_norm=True
> building GPT2BPETokenizer tokenizer ............. Nonee--retrain_gpt_yyt2.sh
> initializing tensor model parallel with size 1ns (new size: 50304)
> initializing pipeline model parallel with size 1
> setting random seeds to 1234 ...
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
make: Nothing to be done for 'default'.
make: Leaving directory '/workspace/megtron/Megatron-LM-main/megatron/data''
>>> done with dataset index builder. Compilation time: 0.114 seconds
> compiling and loading fused kernels ...
Detected CUDA files, patching ldflags
Emitting ninja build file /workspace/megtron/Megatron-LM-main/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /workspace/megtron/Megatron-LM-main/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /workspace/megtron/Megatron-LM-main/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
 > building shuffle index with split [0, 8030) and [8030, 8030) ...
 > elasped time to build and save shuffle-idx mapping (seconds): 0.000436
 > loading doc-idx mapping from my-gpt2_text_document_train_indexmap_8000ns_1024sl_1234s_doc_idx.npy
 > loading sample-idx mapping from my-gpt2_text_document_train_indexmap_8000ns_1024sl_1234s_sample_idx.npy
 > loading shuffle-idx mapping from my-gpt2_text_document_train_indexmap_8000ns_1024sl_1234s_shuffle_idx.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 8031    total number of samples: 8031
    total number of epochs: 36
    total number of epochs: 36
 > WARNING: could not find index map files, building the indices on rank 0 ...
 > last epoch number of samples (5) is larger than 80% of number of samples per epoch (7), setting separate_last_epoch to False
 > elasped time to build and save doc-idx mapping (seconds): 0.000500
    using:
     number of documents:       30
     number of epochs:          125
     sequence length:           1024
     total number of samples:   883
 > elasped time to build and save sample-idx mapping (seconds): 0.000285
 > building shuffle index with split [0, 883) and [883, 883) ...
 > elasped time to build and save shuffle-idx mapping (seconds): 0.000232
 > loading doc-idx mapping from my-gpt2_text_document_valid_indexmap_880ns_1024sl_1234s_doc_idx.npy
 > loading sample-idx mapping from my-gpt2_text_document_valid_indexmap_880ns_1024sl_1234s_sample_idx.npy
 > loading shuffle-idx mapping from my-gpt2_text_document_valid_indexmap_880ns_1024sl_1234s_shuffle_idx.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 884
    total number of epochs: 125
 > WARNING: could not find index map files, building the indices on rank 0 ...
Traceback (most recent call last):
  File "pretrain_gpt.py", line 124, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/workspace/megtron/Megatron-LM-main/megatron/training.py", line 134, in pretrain
    = build_train_valid_test_data_iterators(
  File "/workspace/megtron/Megatron-LM-main/megatron/training.py", line 884, in build_train_valid_test_data_iterators
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets_provider(
  File "pretrain_gpt.py", line 109, in train_valid_test_datasets_provider
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/workspace/megtron/Megatron-LM-main/megatron/data/gpt_dataset.py", line 38, in build_train_valid_test_datasets
    return _build_train_valid_test_datasets(data_prefix[0],
  File "/workspace/megtron/Megatron-LM-main/megatron/data/gpt_dataset.py", line 118, in _build_train_valid_test_datasets
    test_dataset = build_dataset(2, 'test')  File "/workspace/megtron/Megatron-LM-main/megatron/data/gpt_dataset.py", line 110, in build_dataset
    dataset = GPTDataset(name, data_prefix,
  File "/workspace/megtron/Megatron-LM-main/megatron/data/gpt_dataset.py", line 152, in __init__
    self.doc_idx, self.sample_idx, self.shuffle_idx = _build_index_mappings(
  File "/workspace/megtron/Megatron-LM-main/megatron/data/gpt_dataset.py", line 242, in _build_index_mappings
    assert last_epoch_num_samples < (num_samples_per_epoch + 1), \
AssertionError: last epoch number of samples exceeded max value.
`

**Comment by Ant0082** [comment]
Hello, How was the problem solved?

**Comment by Henry-Avery** [comment]
Maybe，I don’t follow this issue

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年3月1日 14:38
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [NVIDIA/Megatron-LM] Is there any problem in my pretrain_gpt.sh? The AssertionError: last epoch number of samples exceeded max value. (Issue #176)


Hello, How was the problem solved?

―

**Comment by sato942** [comment]
are you using personal hardware?
try reduce 
          --seq-length 1024 \
          --max-position-embeddings 1024 \
          
 start with 200 - 800
 
 i think it is related to how much vram you have
