### ISSUE TITLE
Memory 

### ISSUE THREAD

**Issue by LangQingjie** [NVIDIA/Megatron-LM#188]
Hello, I have a question to ask. When I use Megatron for training, I train the 2.35b parameter. When using fp16, the maximum value of the calculated video memory should be 16byte * 2.35b = 35g memory, but the video memory in our training is 37.9 + 37.9g. Why?

**Comment by jaredcasper** [comment]
That's just the memory for the parameters. Activations, gradients, fp32 copies of the parameters, optimizer state, etc. also needs to be stored on the GPU.  Also, there will be some fragmentation that will increase the memory usage.
