### ISSUE TITLE
Training recipe/example for vit(visual transformer)

### ISSUE THREAD

**Issue by qysnn** [NVIDIA/Megatron-LM#202]
Hello,

It seems Megatron added support for visual transformer from the code in the repo such as [Megatron-LM/tree/main/megatron/model/vision](https://github.com/NVIDIA/Megatron-LM/tree/main/megatron/model/vision) and [Megatron-LM/blob/main/pretrain_ict.py](https://github.com/NVIDIA/Megatron-LM/blob/main/pretrain_ict.py). But I couldn't find any document about it.  I wonder if there is any training recipe/example available for the visual transformer? Thanks in advance.

**Comment by juncgu** [comment]
Any updates for the ViT example?

**Comment by jon-barker** [comment]
These will be added soon

**Comment by jon-barker** [comment]
You can now find example training scripts for the vision classification, inpainting and Dino models in the examples folder, .e.g `examples/pretrain_vision_classifiy.sh`
