### ISSUE TITLE
Inference on multi GPU

### ISSUE THREAD

**Issue by milad1378yz** [NVIDIA/Megatron-LM#215]
Hi, I have a sizeable pre-trained model and I want to get inference on multiple GPU from it(I don't want to train it).so is there any way for that?
In summary, I want model-parallelism. and if there is a way, how is it done?

**Comment by RPrenger** [comment]
Hi there.  I'm assuming this is a model that was trained with the Megatron-LM code?  If so, here's an example script for launching a server with an 8-way tensor parallel model:

https://github.com/NVIDIA/Megatron-LM/blob/main/examples/run_text_generation_server_345M_8_tensor_parallel.sh

You should be able to modify that to match your Megatron model and launch a server for your model.  You can query it with curl, or a website, or use the commandline script here:

https://github.com/NVIDIA/Megatron-LM/blob/main/tools/text_generation_cli.py
