### ISSUE TITLE
Can I debate it like it debated itself at the Oxford Union?

### ISSUE THREAD

**Issue by Wild-Dog** [NVIDIA/Megatron-LM#223]
Is that possible with what's here?

**Comment by jon-barker** [comment]
I had to look up what this was referring to. The functionality to have Megatron-LM debate itself is not part of this repo. I believe the [Megatron-11b](https://github.com/facebookresearch/fairseq/tree/main/examples/megatron_11b) model from FAIR was used. I would recommend reaching out to the folks at Oxford that put on the debate to find out what software they used.
