### ISSUE TITLE
Can we get the scripts for merging pipeline parallel model partitions?

### ISSUE THREAD

**Issue by mayank31398** [NVIDIA/Megatron-LM#227]
This would be really helpful

**Comment by Codle** [comment]
I met some problems while trying to merge the model. I'm not sure it has been fixed in the latest version. You can read it as a reference if you meet the same problem:: https://github.com/NVIDIA/Megatron-LM/issues/210

**Comment by bzantium** [comment]
You can check the scripts in PR #233. If you have problem, please let me know. Thanks!

**Comment by mayank31398** [comment]
Thanks
