### ISSUE TITLE
about the "Multi-Stage Prompting for Knowledgeable Dialogue Generation"

### ISSUE THREAD

**Issue by bingfeiz** [NVIDIA/Megatron-LM#230]
First of all thank you very much for your work. When I tried to reproduce the model code of MSDP I found that the checkpoint mentioned in the paper was missing. I found that only checkpoints for Bert and GPT are provided in the readme. So I would like to ask if you can provide me with the checkpoints used in the model.

**Comment by ZHUANG-jt** [comment]
I have the same problem. I tried to reproduce this work, but couldn't find the model or code here. It would be appreciated if you could provide it
