### ISSUE TITLE
[BUG] Finetuning a GPT2 checkpoint does not seem to be working

### ISSUE THREAD

**Issue by rohitdwivedula** [NVIDIA/Megatron-LM#250]
I trained my own GPT2-355M param model using a script that looks something like this: 

```
MASTER_ADDR=localhost
MASTER_PORT=6000
NNODES=1
NODE_RANK=0
DISTRIBUTED_ARGS="--nproc_per_node $GPUS_PER_NODE --nnodes $NNODES --node_rank $NODE_RANK --master_addr $MASTER_ADDR --master_port $MASTER_PORT"

python -m torch.distributed.launch $DISTRIBUTED_ARGS \
       pretrain_gpt.py \
       --num-layers 24 --hidden-size 1024 --num-attention-heads 16 \
       --micro-batch-size $MICROBATCH_SIZE --global-batch-size $BATCH_SIZE --seq-length 1024 \
       --max-position-embeddings 1024 \
       --distributed-backend nccl \
       --save $CHECKPOINT_SAVE_PATH \
       --load $LOAD_PATH \
       --data-path $DATA_PATH --data-impl mmap --split 1000,0,0 \
       --vocab-file $DATA_PATH/gpt2-vocab.json \
       --merge-file $DATA_PATH/gpt2-merges.txt \
       --train-iters $TRAIN_ITERS --lr-decay-iters $LR_DECAY_ITERS \
       --lr 5.0e-5 --lr-decay-style cosine --min-lr 1.0e-5 \
       --weight-decay 1e-2 --clip-grad 1.0 --lr-warmup-fraction .01 \
       --activations-checkpoint-method uniform \
       --fp16
```

I trained this model for a total of 300k iterations with a general multi-domain dataset. The last checkpoint is saved in the directory `$CHECKPOINT_SAVE_PATH/iter_0300000`. This is what the final checkpoint directory looks like:

```
.
└── mp_rank_00
    └── model_optim_rng.pt
```

The `model_optim_rng.pt` file looks like this:

```python3
dict_keys(['args', 'checkpoint_version', 'iteration', 'model', 'optimizer', 'lr_scheduler', 'random_rng_state', 'np_rng_state', 'torch_rng_state', 'cuda_rng_state', 'rng_tracker_states'])
```

Now, I have a domain-specific dataset that I want to finetune this model with. So, I attempted to add the `--finetune` argument, change the `--data` argument to the new (smaller) dataset and then tried to run the training script with a lower LR of `5e-5`.

```
Traceback (most recent call last):
  File "pretrain_gpt.py", line 124, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/home/<user>/Megatron-LM/megatron/training.py", line 129, in pretrain
    = build_train_valid_test_data_iterators(
  File "/home/<user>/Megatron-LM/megatron/training.py", line 829, in build_train_valid_test_data_iterators
    train_dataloader = build_pretraining_data_loader(
  File "/home/<user>/Megatron-LM/megatron/data/data_samplers.py", line 34, in build_pretraining_data_loader
    batch_sampler = MegatronPretrainingSampler(
  File "/home/<user>/Megatron-LM/megatron/data/data_samplers.py", line 73, in __init__
    assert self.consumed_samples < self.total_samples, \
AssertionError: no samples left to consume: 153600000, 3012780
```

It looks like the train script is picking up the samples consumed so far (153600000) from the pretraining checkpoint itself. For context, `153600000` is the number of samples I did pretraining for. `3012780` is the size of my new, smaller dataset that I want to finetune with. However, the `--finetune` argument says:

```
  --finetune            Load model for finetuning. Do not load optimizer or rng state from checkpoint and set iteration to 0. Assumed when loading a release checkpoint.
```

So, `--finetune` is not working as intended? Or is there some extra steps I need to do before finetuning for this to work?

**Comment by rohitdwivedula** [comment]
The next thing I tried was to see what `release` checkpoints look like. So, I downloaded the GPT2-345M param model checkpoint provided on this repo by doing:

```
wget --content-disposition https://api.ngc.nvidia.com/v2/models/nvidia/megatron_lm_345m/versions/v0.0/zip -O megatron_lm_345m_v0.0.zip
```

The first difference that I noticed between the last training checkpoint that I had (`iter_0300000`) and the official release checkpoint (`release`) is that:
- The `model_optim_rng.pt` file from the `release` checkpoint contains only two items - `dict_keys(['iteration', 'model'])`. My checkpoint had a lot of other extra keys, such as `'args', 'checkpoint_version', 'optimizer', 'lr_scheduler', 'random_rng_state', 'np_rng_state', 'torch_rng_state', 'cuda_rng_state', 'rng_tracker_states'`.
- In my checkpoint, the value of `iteration` was `300000` but in the release checkpoint it was just `1`. 

I thought I would try to convert my `iter_0300000` checkpoint to match the format of your release checkpoint by making these two changes and saving them to a new directory called `release`. I also changed `latest_checkpoint_iteration.txt` to be `release` so that the checkpoint-loading function would pick up this edited checkpoint. Doing this, however, also does not seem to work. Firstly, the checkpoint-loading code itself produces a warning:

```
 loading checkpoint from /path/to/gpt/ckpt/ at iteration 0
could not find arguments in the checkpoint ...
 checkpoint version 0
 succesfully fixed query-key-values ordering for checkpoint version 0
  successfully loaded checkpoint from /path/to/gpt/ckpt/ at iteration 0
```

and secondly, the initial train losses (in bold) seem way too high:

> [Rank 0] (after 100 iterations) memory (MB) | allocated: 6768.6376953125 | max allocated: 6768.640625 | reserved: 6818.0 | max reserved: 6818.0 iteration      100/   94027 | consumed samples:         3200 | elapsed time per iteration (ms): 308.7 | learning rate: 4.440E-06 | global batch size:    32 |  **lm loss: 9.652503E+00** | loss scale: 16384.0 | grad norm: 2.418 | number of skipped iterations:  19 | number of nan iterations:   0 |
>  iteration      200/   94027 | consumed samples:         6400 | elapsed time per iteration (ms): 203.8 | learning rate: 9.922E-06 | global batch size:    32 | **lm loss: 8.291631E+00** | loss scale: 16384.0 | grad norm: 2.062 | number of skipped iterations:   0 | number of nan iterations:   0 |
>  iteration      300/   94027 | consumed samples:         9600 | elapsed time per iteration (ms): 208.0 | learning rate: 1.540E-05 | global batch size:    32 | **lm loss: 7.266254E+00** | loss scale: 16384.0 | grad norm: 1.679 | number of skipped iterations:   0 | number of nan iterations:   0 |
>  iteration      400/   94027 | consumed samples:        12800 | elapsed time per iteration (ms): 211.6 | learning rate: 2.089E-05 | global batch size:    32 | **lm loss: 6.600114E+00** | loss scale: 16384.0 | grad norm: 1.618 | number of skipped iterations:   0 | number of nan iterations:   0 |
>  iteration      500/   94027 | consumed samples:        16000 | elapsed time per iteration (ms): 211.9 | learning rate: 2.637E-05 | global batch size:    32 | **lm loss: 6.281490E+00** | loss scale: 16384.0 | grad norm: 1.882 | number of skipped iterations:   0 | number of nan iterations:   0 |

My pretrained models final logs indicate that the final train loss was around `2.97` and the final eval loss was around `2.88`:

> iteration   300000/  300000 | consumed samples:    153600000 | elapsed time per iteration (ms): 2230.6 | learning rate: 1.000E-05 | global batch size:   512 | **lm loss: 2.971118E+00** | loss scale: 131072.0 | grad norm: 0.189 | number of skipped iterations:   0 | number of nan iterations:   0 |
> validation loss at iteration 300000 | **lm loss value: 2.910630E+00** | lm loss PPL: 1.836837E+01 | 

Also, to put into context why I think the model is not being correctly loaded:
- The final perplexity in the pretrained model was around `~18.3`
- The initial train loss during finetuning is like `~9.6`, corresponding to a perplexity of `~14764` - which seems almost close to the perplexity a randomly initialized model would have.

**Comment by rohitdwivedula** [comment]
So, in general, it looks like there are more differences between `release` checkpoints and general training checkpoints. In the Python scripts below, the variable `training` refers to my pre-training checkpoint, and `release` refers to the GPT-355M param checkpoint released in this repo: 

```python3
> training['model']['language_model'].keys()
dict_keys(['embedding', 'encoder'])

> release['model']['language_model'].keys()
dict_keys(['embedding', 'transformer'])
```
(there is a difference in naming - `transformer` vs `encoder`). 

In addition to this, inside the `transformer`/`encoder` blocks:
- in training checkpoints, self attentions are stored with keys that look like this: `layers.0.self_attention.query_key_value.weight`
- in release checkpoints, the same layers look like this: `layers.0.attention.query_key_value.weight:torch`
- the difference: The names contain `self_attention` vs `attention`.

I tried to make these changes as well to my train checkpoint `.pt` file and run the finetune script again, but even with this, it still seems to be loading a random model instead of picking up weights from the checkpoint.

**Comment by pangsg** [comment]
I have met this BUG, and have no idea to fix it. Do you figure out this problem now?
