### ISSUE TITLE
[Question]Megatron Performance with NGC PyTorch

### ISSUE THREAD

**Issue by roywei** [NVIDIA/Megatron-LM#254]
Hi I'm not sure if this is the right repo to ask this question please help redirect me.

I'm training Megatron-LM with NGC container, but I need a custom change on PyTorch.
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

I found out that NGC stock PyTorch in the container is constantly faster than other alternatives, in forward/backward compute time.  If I make custom changes and compile from source, or install from conda/pip it's always slower. Any ideas why or how can I match the performance? I'm already using the same PyTorch commit from NGC release notes
https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-03.html#rel_22-03

I'd like to make some custom change and match the perf of NGC PyTorch.

Any insights will be helpful, thanks!
```
# NGC PyTorch
iteration      600/     800 | consumed samples:         4800 | elapsed time per iteration (ms): 437.3 | learning rate: 2.733E-05 | global batch size:     8 | lm loss: 6.766993E+00 | loss scale: 65536.0 | grad norm: 1.671 | number of skipped iterations:   0 | nu
mber of nan iterations:   0 |
7: time (ms) | forward-compute: 117.89 | backward-compute: 278.99 | backward-params-all-reduce: 1.87 | backward-layernorm-all-reduce: 0.01 | backward-embedding-all-reduce: 0.02 | backward-reduce-model-grads: 1.94 | backward-gather-model-params: 0.01 | optimizer-cop

# Conda/Pip installed PyTorch and Compiled from source PyTorch
iteration      600/     800 | consumed samples:         4800 | elapsed time per iteration (ms): 451.7 | learning rate: 2.733E-05 | global batch size:     8 | lm loss: 6.767890E+00 | loss scale: 65536.0 | grad norm: 1.687 | number of skipped iterations:   0 | number of nan iterations:   0 |
7: time (ms) | forward-compute: 120.25 | backward-compute: 290.83 | backward-params-all-reduce: 1.87 | backward-layernorm-all-reduce: 0.01 | backward-embedding-all-reduce: 0.02 | backward-reduce-model-grads: 1.94 | backward-gather-model-params: 0.01 | optimizer-copy-to-main-grad: 4.85 | optimizer-unscale-and-check-inf: 4.91 | optimizer-clip-main-grad: 7.58 | optimizer-count-zeros: 0.01 | optimizer-inner-step: 14.71 | optimizer-copy-main-to-model-params: 5.20 | optimizer: 37.35 | batch-generator: 1.44
```

**Comment by jaredcasper** [comment]
Hi roywei, unfortunately I'm not sure we can be much help with this one. There is a whole team devoted to maximizing performance of those NGC containers so there is a decent amount of magic in there getting everything to play nicely. The nvfuser version/usage could be different, the NCCL version could be different from the upstream pytorch code, assuming you don't set USE_SYSTEM_NCCL in recent containers. The cuDNN version could be an additional difference?

**Comment by roywei** [comment]
Hi @jaredcasper thanks for the reply!
I was able to narrow it down to the PyTorch source code inside the container /opt/pytorch, looks like there is some custom changes by the ncg team. If I compile from there I get better speed. I’ve made everything else the same, using nccl/cuda/cudnn provided by system(inside the ngc container)

Is there a support channel I could reach out for NGC container? Want to understand the implications to make changes on those custom PyTorch source code. Thanks so much for your help!

**Comment by jaredcasper** [comment]
I'm not sure of the best way to reach out to NGC container support. I think if you ping Piotr Bialecki or Masaki Kozuki they might be able to help or direct you further. Ping them on GitHub, PyTorch Slack, Twitter, etc.

**Comment by roywei** [comment]
Thank you so much! Closing now
