### ISSUE TITLE
why the shape of token2use must be [:,prev_context_length:context_length]

### ISSUE THREAD

**Issue by pangsg** [NVIDIA/Megatron-LM#256]
why the shape of tokens2use must be [:,prev_context_length:context_length]? In this way, the token length is always one.

**Comment by jaredcasper** [comment]
During text generation, only one token is generated at a time.

**Comment by pangsg** [comment]
> During text generation, only one token is generated at a time.

Thank you for your reply. But I'm still confused. At time t, it's true that only one token is generated, but at time t+1, we should concatenate the newly generated token into the context and treat [context:text] as the input of the GPT model at time t+1. As I understand it, tokens2use is supposed to represent the input of GPTmodel, but in your code, tokens2use always takes the length of 1, does it mean that there is only 1 token as the input at time t+1? Looking forward to your reply, thank you!


```
            tokens2use = tokens[:, prev_context_length:context_length]
            positions2use = position_ids[:, prev_context_length:context_length]
            attention_mask2use = attention_mask[
                ..., prev_context_length:context_length, :context_length]

            # logits will be meanigful only in the last pipeline stage.
            logits = forward_step(tokens2use, positions2use, attention_mask2use)
```

**Comment by pangsg** [comment]
I have already figured out this issue, thanks for your help!

**Comment by xdhhh** [comment]
> I have already figured out this issue, thanks for your help!

Hi, i am also confused about this problem, could you please share your explanation? Thanks!

**Comment by cordercorder** [comment]
During decoding, we can cache the previous calculation results of keys and values to save computation time. The cached keys and values will be fetched from the cache and concatenated with the new key and value. As a result, we only need to pass one token at a time.

**Comment by xdhhh** [comment]
> During decoding, we can cache the previous calculation results of keys and values to save computation time. The cached keys and values will be fetched from the cache and concatenated with the new key and value. As a result, we only need to pass one token at a time.

But i don't find any parameter about the cache, also, i got size error when using the original code

**Comment by cordercorder** [comment]
You can find detailed information about the implementation of the keys and values cache [here](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/transformer.py#L539). I hope this helps.

**Comment by deepakn94** [comment]
Closing this since I think the original question was resolved.
