### ISSUE TITLE
Max seq len of 4096 support in scaled_upper_triang_masked_softmax?

### ISSUE THREAD

**Issue by zijwang** [NVIDIA/Megatron-LM#260]
It seems `scaled_upper_triang_masked_softmax` does not support max sequence length of 4096, see https://github.com/NVIDIA/Megatron-LM/blob/3860e995269df61d234ed910d4756e104e1ab844/megatron/fused_kernels/scaled_upper_triang_masked_softmax.h#L414-L417

However, `scaled_masked_softmax` does support 4096,  https://github.com/NVIDIA/Megatron-LM/blob/e156d2fea7fc5c98e645f7742eb86b643956d840/megatron/fused_kernels/scaled_masked_softmax.h#L616-L619

Is there any reason why 4096 isn't supported in `scaled_upper_triang_masked_softmax`? Thanks.

**Comment by jon-barker** [comment]
Closing. Issue was fixed here: https://github.com/NVIDIA/Megatron-LM/commit/6753e8bf9eaf1191e69f8e6d5015c4f861569dd2

**Comment by SefaZeng** [comment]
I met the same problem, and is seems the latest megatron has no `scaled_masked_softmax.h`?
