### ISSUE TITLE
Are there more features to be released?

### ISSUE THREAD

**Issue by GxjGit** [NVIDIA/Megatron-LM#269]
It has been a long time since last release. Are there more features to be released?  such as, supporting more high perfamance ops，  adapting to Pytorch 2.0 and so on.

**Comment by jon-barker** [comment]
Yes, Megatron-LM development continues. Pytorch 2.0 is no supported and performance improvements have been made since this issue was opened. If you have other specific enhancement requests please open new issues for them. Thanks.
