### ISSUE TITLE
Calculate the TFLOPS performance with elapsed time per iteration

### ISSUE THREAD

**Issue by fengche86** [NVIDIA/Megatron-LM#27]
Hi!
I'm trying to study the Megatron model-parallel, and was able to run the model on V100 GPU using Pytorch docker container, with GPT2.
However, the benchmark log would only print out the elapsed time spent for every 100 iterations.
My question is, how can I calculate the TFLOPS performance from the elapsed time per iteration?
It would be helpful if you can shed some light on the formula to calculate the TFLOPS/PFLOPS from the model configurations (hidden size, attention heads and number of layers). 
 
I'm now getting 528.9ms per iteration for single GPU, I'm hoping that would match the single GPU baseline performance mentioned in the paper (39 TeraFLOPS).
Following is the model I've been using:
Config | Hidden size | Attention heads | Number of layers | Number of   parameters      (billion) | Model parallel   GPUs
-- | -- | -- | -- | -- | --
1 | 1536 | 16 | 40 | 1.2 | 1

Thanks!

**Comment by fengche86** [comment]
Hi @jaredcasper @raulpuric , would you please help? Thanks!

**Comment by micmelesse** [comment]
Any updates on this?

**Comment by hwdef** [comment]
Have the same problem

**Comment by dageita** [comment]
Have the same problem
