### ISSUE TITLE
Loading pretrained checkpoints in pretraining with model parallel

### ISSUE THREAD

**Issue by karlie38** [NVIDIA/Megatron-LM#276]
There were bugs when loading pretrained checkpoints in with model parallel trianing.
There was no bug when only with data parallel training. Is is possible to train the model with model parallel initialized from pretrained checkpoints?

![image](https://user-images.githubusercontent.com/56949426/216296437-b4a11729-b692-4f4a-b3df-4f72d52828ce.png)

**Comment by karlie38** [comment]
Solved

**Comment by HaoboGu** [comment]
same issue, how do you solved it? @karlie38
