### ISSUE TITLE
Couldn't find BERT 3.9B related implementation

### ISSUE THREAD

**Issue by LiweiPeng** [NVIDIA/Megatron-LM#28]
Hi,  I have a question about your BERT xlarge modeling implementation.

From your [megatron paper](https://arxiv.org/pdf/1909.08053.pdf) Figure 7, by rearranging the order of the layer normalization and the residual connections, you successfully trained BERT xlarge up to 3.9B parameters. 

![Screen Shot 2020-04-13 at 11 02 24 AM](https://user-images.githubusercontent.com/8562078/79146947-06b08280-7d78-11ea-9fe9-62e1c3b3b4ee.png)

When I read the related BERT metatron code, for [all the LayerNorm-related implementation](https://github.com/NVIDIA/Megatron-LM/blob/master/model/modeling.py), I couldn't see the change mentioned in the paper Figure 7.

Can you clarify what I am missing? Thanks.

**Comment by LiweiPeng** [comment]
I found latest code has code change mentioned in the paper. so close it.

**Comment by shamoons** [comment]
I'm confused. The code seems to have 345M parameter models?

**Comment by skye95git** [comment]
> I found latest code has code change mentioned in the paper. so close it.

Hi, I meet the same problems. Can you share where the relevant code snippet is？
