### ISSUE TITLE
support continuous pre-training/fine-tuning for OpenAI's Whisper model

### ISSUE THREAD

**Issue by tnlin** [NVIDIA/Megatron-LM#280]
Hi, I am working on continuous pre-training/fine-tuning with OpenAI's Whisper model 
https://github.com/openai/whisper

1. Is there any roadmap for this project to support more models like Whisper?
2. Are there any suggestions or examples for me to port the Whisper model to this project?

Thanks!

**Comment by huskyachao** [comment]
> Hi, I am working on continuous pre-training/fine-tuning with OpenAI's Whisper model https://github.com/openai/whisper
> 
> 1. Is there any roadmap for this project to support more models like Whisper?
> 2. Are there any suggestions or examples for me to port the Whisper model to this project?
> 
> Thanks!

Hi @tnlin , I am trying to fine-tuning whisper-large-v3 recently. Did you solve the problem of adapting whisper to Megatron-LM? Thanks.
