### ISSUE TITLE
How to change tensor-model-parallel-size of a model

### ISSUE THREAD

**Issue by HaoboGu** [NVIDIA/Megatron-LM#296]
Hello, I want to fine-tune an existing GPT model using megatron, but I got this error: 
```
  File "/mnt/workspace/alibee-shop-megatron/megatron/checkpointing.py", line 58, in _compare
    assert checkpoint_value == args_value, error_message
AssertionError: tensor_model_parallel_size value from checkpoint (1) is not equal to the input argument value (2).
```

I guess this is because the existing model is trained with `tensor-model-parallel-size 1` and I set this parameter to 2 due to my GPU memory limitation. I am wondering is there an approach to change checkpoints `tensor-model-parallel-size` param?

**Comment by uygnef** [comment]
I got same problem.

**Comment by deepakn94** [comment]
We do not have a utility right now to convert checkpoints (i.e., create a TP=1 checkpoint from a TP=2 checkpoint). But we welcome contributions!
