### ISSUE TITLE
why use VocabParallelEmbedding?

### ISSUE THREAD

**Issue by liuchanglab** [NVIDIA/Megatron-LM#300]
Words embedding takes 1~2G GPU memeory (num_embeddings=50000, embedding_dim=3700).  One GPU is enough for words embedding. Why use a distributed vocab embedding? The position embedding only use one GPU.

![image](https://user-images.githubusercontent.com/65170329/228254692-2a7fb952-1bc7-4600-b789-c568fca81ea3.png)

**Comment by daxintan-cuhk** [comment]
same question. This brings difficulty if you want to freeze part of the vocabulary embedding.
