### ISSUE TITLE
how to merge many ckpts to one file

### ISSUE THREAD

**Issue by yoosan** [NVIDIA/Megatron-LM#305]
I have trained a GPT with 4-way tensor parallelism, also used the distributed optimizer. Now I get trained ckpts as shown below.

**Could anynone tell me how can I merge these ckpts to one?**

<img width="788" alt="image" src="https://user-images.githubusercontent.com/6985529/230895597-1a1fce22-3cd5-4a89-be2a-60519b592105.png">

**Comment by zxyscz** [comment]
i have the same question, can you resolve it ?
