### ISSUE TITLE
[Question] How to generate a merge file and a vocab file

### ISSUE THREAD

**Issue by Zhang-kg** [NVIDIA/Megatron-LM#312]
I want to use the Megatron framework for Chinese NLP pre-training tasks. Currently, I have Chinese corpus resources and a vocab.txt file. However, for most frameworks, it seems that vocab.json and merge.txt are needed. Can I generate the above two files from Chinese corpus resources? If so, how can I generate them? Sorry, I haven't found a particularly suitable tutorial on Google.

**Comment by MrInouye** [comment]
I also encountered this problem，how to get chinese vocab.json and  merge.txt?

**Comment by Zhang-kg** [comment]
您好，您的邮件我已经收到！

**Comment by Zhang-kg** [comment]
您好，您的邮件我已经收到！

**Comment by Zhang-kg** [comment]
您好，您的邮件我已经收到！

**Comment by zixianwang2022** [comment]
Hi, I am also wondering what is merge_file and vocab_file. Can you provide some clues?

**Comment by shanmugamr1992** [comment]
Please read about it online. Its related to tokenizers. https://github.com/huggingface/transformers/issues/1083#issuecomment-524303077 That blog might help
