### ISSUE TITLE
[Bug] Transformer engine layer is very slow

### ISSUE THREAD

**Issue by szhengac** [NVIDIA/Megatron-LM#330]
Hi, it seems the transformer engine layer is buggy and I obtained very poor performance when benchmarking a 22B GPT throughput on a single 8xH100 SXM5 box. The 22B parameter model and training configurations are borrowed from paper https://arxiv.org/abs/2205.05198. The numbers are shown as bellow

local implementation with bf16: `311 TFLOPS`
transformer engine implementation by adding `--transformer-impl 'transformer_engine'` to the argument: `87 TFLOPS`
transformer engine implementation with FP8 with hybrid format: `358 TFLOPS`

**Comment by ksivaman** [comment]
Hey, could you answer the following regarding your setup?

- What are the settings you're using for parallelism?
  - Data parallel size?
  - Tensor parallel size? Is sequence parallel enabled?
  - Pipeline parallel size? 
- What are you e2e per step timings for the 3 settings (FP8 vs local BF16 vs TE bf16)?

**Comment by szhengac** [comment]
@ksivaman  I use the same configuration as in the paper. Specifically: DP=1, TP=8, PP=1. Sequence parallel is enabled. The TFLOPS I show above reflect the step time, since I calculated TFLOPS based on Megatron log output.

**Comment by szhengac** [comment]
@ksivaman the example launch script is here: https://github.com/szhengac/Megatron-LM/blob/main/examples/benchmark_gpt3.sh

**Comment by ksivaman** [comment]
Could you try with the environment variable `NVTE_BIAS_GELU_NVFUSION` set to 0?

- `export NVTE_BIAS_GELU_NVFUSION=0`

**Comment by ksivaman** [comment]
Could you try with the environment variable `NVTE_BIAS_GELU_NVFUSION` set to 0?

- `export NVTE_BIAS_GELU_NVFUSION=0`

**Comment by szhengac** [comment]
@ksivaman I lost the access to H100 and I will see if I can get it back. At the same time, do you have any machines for testing?

**Comment by szhengac** [comment]
@ksivaman I can confirm that setting `NVTE_BIAS_GELU_NVFUSION=0` fixes the performance. So bias gelu fusion is buggy.

**Comment by LLMChild** [comment]
@ksivaman I also try to use the fp8 in my 5b model training using 8 h100-sxm4 card.But the memroy consumption is much larger than fp16, do you have any ideas about the reason?

**Comment by stgzr** [comment]
Larger memory consumption, and slower speed in Megatron-LM training. Any advice to check the transformer-engine working properly?

**Comment by MoFHeka** [comment]
Same problem.

**Comment by junpuf** [comment]
same large memory consumption problem observed with fp8
