### ISSUE TITLE
Which data loading strategy is the fastest? cached , mmap, or lazy? 

### ISSUE THREAD

**Issue by 2catycm** [NVIDIA/Megatron-LM#332]
1. Which data loading strategy is the fastest? cached , mmap, or lazy? Or, what aspect it depends on machines?
There isn't any documentation on this, and I cannot understand how they work respectively. 
On the Internet I found that mmap is memory map, a system call to pin the data content from disk to memory, but what is "cached" and what is "lazy"?

2. Besides, why do we need to specify the way of loading strategy in preprocess_data.py？ I thought it was just about how to load data, but not about how to preprocess it.

**Comment by jon-barker** [comment]
We actually only support `mmap` during training. The presence of the other options is an unsupported carryover from fairseq. There is an incoming update that will remove the other options from preprocessing and training and update the README.md accordingly.
