### ISSUE TITLE
AttributeError: 'DistributedOptimizer' object has no attribute '_copy_model_params_to_main_params'

### ISSUE THREAD

**Issue by nullnonenilNULL** [NVIDIA/Megatron-LM#333]
when i fine-tune model from checkpoint with --use-distributed-optimizer，i got the error as the title.

**Comment by yuyq96** [comment]
same problem, seems like only `Float16OptimizerWithFloat16Params` implements `_copy_model_params_to_main_params`

**Comment by liuslnlp** [comment]
same problem

**Comment by Boreaso** [comment]
same problem

**Comment by dumpmemory** [comment]
would u mind testing this pr https://github.com/NVIDIA/Megatron-LM/pull/352 ?

**Comment by jaredcasper** [comment]
This should be fixed in the latest main branch.

**Comment by dumpmemory** [comment]
> This should be fixed in the latest main branch.

Thanks bro
