### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by xyang2013** [NVIDIA/Megatron-LM#338]
Hi,

I am having the following error:

from tools.retro.utils import get_args_path as get_retro_args_path
ModuleNotFoundError: No module named 'tools.retro'

It is fine in the IDE but gives this error during execution.

Any suggestion?

Thanks

**Comment by jon-barker** [comment]
@xyang2013 Can you explain what command you were running from the command line that ended up calling `from tools.retro.utils import get_args_path as get_retro_args_path`? Thanks
