### ISSUE TITLE
RuntimeError: Address already in use

### ISSUE THREAD

**Issue by jackychancjcjcj** [NVIDIA/Megatron-LM#343]
I am running distributed pertaining script. And got problem as shown. Any suggestions? thanks.

My config:
MASTER_ADDR=localhost
MASTER_PORT=8514
NNODES=1
NODE_RANK=0
WORLD_SIZE=$(($GPUS_PER_NODE*$NNODES))

DISTRIBUTED_ARGS="--nproc_per_node $GPUS_PER_NODE --nnodes $NNODES --node_rank $NODE_RANK --master_addr $MASTER_ADDR --master_port $MASTER_PORT"

python -m torch.distributed.launch $DISTRIBUTED_ARGS ......

File "/megatron/initialize.py", line 181, in _initialize_distributed
torch.distributed.init_process_group(
File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group
store, rank, world_size = next(rendezvous_iterator)
File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 142, in _tcp_rendezvous_handler
store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use

**Comment by jon-barker** [comment]
Can you trying using a different MASTER_PORT? This error usually means that that port is already in use.

**Comment by deepakn94** [comment]
Hopefully using a different master port worked for you. I'm going to close this, but feel free to re-open if you are still running into issues.
