### ISSUE TITLE
Code fixes for local-storage-only environment

### ISSUE THREAD

**Issue by learning-chip** [NVIDIA/Megatron-LM#356]
In certain virtualized environment there is no shared storage. Both source code and data are stored (replicated) in each worker node's local storage. The code sections below only load data or build/load binaries on local directory. Other nodes cannot see master's file path.

https://github.com/NVIDIA/Megatron-LM/blob/cd2537d444792b487b1ab5a6fa685e09c9957409/megatron/data/gpt_dataset.py#L310-L317

(same for dataset builders other than GPT)

https://github.com/NVIDIA/Megatron-LM/blob/cd2537d444792b487b1ab5a6fa685e09c9957409/megatron/initialize.py#L92-L100

https://github.com/NVIDIA/Megatron-LM/blob/cd2537d444792b487b1ab5a6fa685e09c9957409/megatron/initialize.py#L126-L130

https://github.com/NVIDIA/Megatron-LM/blob/cd2537d444792b487b1ab5a6fa685e09c9957409/megatron/initialize.py#L140-L143

Changing `torch.distributed.get_rank()` to `torch.distributed.get_rank() % torch.cuda.device_count()` fixes the problem, by having one process on each node accessing its local disk. Of course here assumes each node has the same number of devices. Otherwise need to pass `os.environ['LOCAL_RANK']` from the main script to identify the local rank.

**Comment by jindajia** [comment]
I have a similar problem. My cluster has a relatively slow shared storage system, so I want to copy dataset to compute node temporary storage system. However, I found that, Megatron will first build a data index cache only on rank=0 gpu, so other node can not access this data cache file, which will return FileNotFoundError.

**Comment by MAxx8371** [comment]
> torch.distributed.get_rank() % torch.cuda.device_count()
@jindajia 
The same issue. Could you please advise on how to resolve it?

**Comment by MAxx8371** [comment]
> I have a similar problem. My cluster has a relatively slow shared storage system, so I want to copy dataset to compute node temporary storage system. However, I found that, Megatron will first build a data index cache only on rank=0 gpu, so other node can not access this data cache file, which will return FileNotFoundError.

@jindajia The same issue. Could you please advise on how to resolve it?

**Comment by haok1402** [comment]
We had this issue too! It bothers us a lot, since SSD storage are mounted to each node, which provide faster access over NFS.

**Comment by haok1402** [comment]
We had this issue too!

It bothers us a lot, since SSD storage are mounted to each node, which provide faster access over NFS, which is favored for training scenarios.
