### ISSUE TITLE
Swiglu activation may be wrong when TP > 1

### ISSUE THREAD

**Issue by 17889982022** [NVIDIA/Megatron-LM#360]
Firstly, appreciate for this amazing project！

I want to use swiglu activation in the trianing of GPT，but I found there may be a possible error in the calculation of swiglu when the size of TP comes to > 1.

Compared to the traditional MLP(FFN) part in Transformers，the swiglu can be seen having 3 linear projections, in which the whole calculation is `self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))`. In Megatron-LM,  the "gate_proj" and "up_proj"  are concatenated to a single linear named "dense_h_to_4h", and the output of "dense_h_to_4h" is then chunked into two parts to execute the above process using `F.silu(x[0]) * x[1])`. This works fine except the tensor-model-parallel-size (TP) > 1.
 
Take TP=2 as an example,  the weight of “dense_h_to_4h" will be split into 2 partitions along column axis,  every gpu (or tp_rank) will hold a single partition to calculate its own output, in which the partition is then chunked into two parts again. That's the problem, the original meaning of 2 partitions in "dense_h_to_4h" should have referred to the "gate_proj" and "up_proj", but after the TP operation，"gate_proj" and "up_proj" have been separated into different tp_ranks. This leads  that it is the the output of "gate_proj"  will be chunked into two part in tp_rank0 (or "up_proj" in tprank1) rather than "dense_h_to_4h" itself ,  which is not conform to the original calculation of swish.

Hope to check if there is really indeed an error, thanks!

**Comment by jaredcasper** [comment]
TP splits both gate_proj and up_proj up, so they become interleaved if you were to do a simple concatenation of the combined tensor. So tp_rank0 has [gate_proj_0, up_proj_0], and tp_rank_1 has [gate_proj_1, up_proj_1]. (This needs to be taken into consideration when changing the TP size).

Or am I misunderstanding your concern?

**Comment by 17889982022** [comment]
Thanks for replying!

TP should have gone to split “gate_proj" itself (or "up_proj ") into 2 ranks, but in Megatron-LM TP split "dense_h_to_4h" (the concatenation of gate_proj and up_proj as I understand) into 2 ranks, results in that tp_rank0 holds "gate_proj" and tp_rank1 holds "up_proj"。 It seems that “gate_proj" (or "up_proj ") is not splited along the TP dimension.

More clearly, as you say, the correct calculation is tp_rank0 has [gate_proj_0, up_proj_0], and tp_rank_1 has [gate_proj_1, up_proj_1]. But it seems that Megatron-LM doesn't work that way, I did an experimental comparison of the dense_h_to_4h‘s outputs in both TP=1 and TP=2, and I found that when TP=2, tp_rank0 has [gate_proj_0, gate_proj_1] and tp_rank_1 has [up_proj_0, up_proj_1] That is what I was confused about before.

Of course my understanding may also be wrong.  Appreciate again for your focus.

**Comment by 17889982022** [comment]
Sorry, I found the TP conversion in `tools/checkpoint_utils.py` had noticed the handling of this case, so there is nothing wrong with it. 

In my experiment I use my own code to conduct the TP conversion, where I split the weight of `dense_h_to_4h` directly into the target TP size.  I overlooked the special treatment here, which is why the results are inconsistent.
