### ISSUE TITLE
how to scale up zero1 data parallel world size when resume training ?

### ISSUE THREAD

**Issue by Haijunlv** [NVIDIA/Megatron-LM#361]
When we use megatron to train llm, we would like to scale up nodes in training progress, such as from tp8 pp4 dp2(64 cards) to tp8 pp4 dp4(128 cards).
But if we use zero1 at 64 nodes, optimizer state is splitted between dp=2. And we need to resplitted dp2 optimizer state between dp4 at 128 nodes.
This demand is general in llm training. So Is there any solution or similar solution to handle this problem?

**Comment by lmcafee-nvidia** [comment]
Please try again using the latest code base. The distributed optimizer now saves to a unified checkpoint, where all DP shards are concatenated into a single tensor.
