### ISSUE TITLE
ImportError: .../megatron/fused_kernels/build/scaled_upper_triang_masked_softmax_cuda.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb

### ISSUE THREAD

**Issue by TheGravityZero** [NVIDIA/Megatron-LM#366]
Hello, I have this issue:
```
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: .../megatron/fused_kernels/build/scaled_upper_triang_masked_softmax_cuda.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
```
My configuration:
```
apex                     0.1
torch                    1.11.0+cu113
torchaudio               0.11.0+cu113
torchfile                0.1.0
torchvision              0.12.0+cu113
```
I will be glad for any help!

**Comment by jon-barker** [comment]
Did you move or update environments that you were running the code in? If so the problem may be that the fused_kernels need rebuilding for the new environment.

Try deleting `.../megatron/fused_kernels/build` and re-running. The fused_kernels will automatically re-compile for the current environment.

**Comment by jon-barker** [comment]
Please try again with the latest `main`. [This](https://github.com/NVIDIA/Megatron-LM/commit/cd126362bbe8a08d1813485f6d8307f605a4eedd) commit removes the need for compiling custom kernels and instead relies on the kernels from Apex.
