### ISSUE TITLE
Does the Megatron-LM support automatic selection of different types of network cards, such as Ethernet and high-speed IB network cards?

### ISSUE THREAD

**Issue by pengshuang** [NVIDIA/Megatron-LM#369]
Our scenario involves two heterogeneous GPU clusters, Cluster A and Cluster B, each consisting of 20 GPU machines (A100-80G). Cluster A is internally equipped with both high-speed IB cards and regular Ethernet cards, while Cluster B is internally equipped with high-speed RoCE cards and regular Ethernet cards. Due to the inability to establish a high-speed IB network between Cluster A and Cluster B, communication between them can only be done via Ethernet using TCP/IP (Socket).

Our objective is to have machines within Cluster A and Cluster B connected through high-speed cards, while machines between Cluster A and Cluster B are connected through regular Ethernet networking. I would like to inquire whether Megatron supports automatic card detection and configuration to enable distributed training between the heterogeneous clusters. If it doesn't support it, is it possible to achieve this by modifying the PyTorch code (NCCL part) in Megatron-LM?

I am unsure of the feasibility and would greatly appreciate your response. Thank you very much!

**Comment by plegresl** [comment]
This isn't an interconnect configuration we currently support, and we don't have plans to support it in the foreseeable future. If you want to try implementing something like this I would recommend watching this presentation: https://www.nvidia.com/en-us/on-demand/session/gtcfall22-a41193/

**Comment by jon-barker** [comment]
Closing. I think the question is answered.
