### ISSUE TITLE
[Question] Why bf16 mode must use fp32 for accumulation and communication

### ISSUE THREAD

**Issue by cicirori** [NVIDIA/Megatron-LM#372]
I would like to know why bf16 must be used at the same time as accumulate_allreduce_grads_in_fp32? Is it for accuracy reasons or is it a historical problem due to older versions of nccl not supporting the bf16 format?

**Comment by Kingsleyandher** [comment]
I'm curious about that too.

**Comment by deepakn94** [comment]
We found this to lead to more stable training before, but you could also try to perform the all-reduce in `bf16` (it might hurt convergence but will be faster).
