### ISSUE TITLE
How to split the num_layers unevenly when using pipeline parallelism?

### ISSUE THREAD

**Issue by aoyulong** [NVIDIA/Megatron-LM#381]
For now, Megatron-LM requires the num_layers must be divisible by pipeline_model_parallel_size:
`assert args.num_layers % args.transformer_pipeline_model_parallel_size == 0, \
                'num_layers must be divisible by transformer_pipeline_model_parallel_size'`
How to split the num_layers unevenly? For example, given num_layers=7 and pipeline_model_parallel_size=2, the results will be 3 num_layers for stage 0 and 4 num_layers for stage 1.

**Comment by jon-barker** [comment]
As you note, this isn't currently supported. Are you looking for guidance on how it should be implemented?

**Comment by aoyulong** [comment]
@jon-barker I will try to implement it and some guidances will be very helpful.  I have found [the direct place](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/transformer.py#L1179C1-L1179C57) that needs to be modified. But I am not sure whether there are some other places that need to be modified.

**Comment by jon-barker** [comment]
There is a proposed approach to this here: https://github.com/NVIDIA/Megatron-LM/pull/274

This is still in review and may not be the solution we adopt though.

**Comment by edgeinfinity1** [comment]
This has been implemented by https://github.com/NVIDIA/Megatron-LM/commit/77732c3628ea6843b64d0aa2b02017bd05dddcdb , in case anyone wants it.
