### ISSUE TITLE
Why do we only need to use the layernorm parameters of tp_rank 0 when converting a checkpoint?

### ISSUE THREAD

**Issue by hnczlsr** [NVIDIA/Megatron-LM#383]
https://github.com/NVIDIA/Megatron-LM/blob/060415572f4365a2e895f8036c4e37dad0efbdf5/tools/checkpoint_loader_megatron.py#L236

Is it because all layernorms on tp_rank are the same, so only tp_rank 0 can be used?
If using sequence parallelism, will different tp_ranks contain different layernorms? In this case, do we still only need to use parameters from tp_rank 0? Please advise.

**Comment by ZeldaHuang** [comment]
Sequence parallelism doesn't split layernorm weight&&bias, it spilts input tensor in sequence dimension. So all ranks have same layernorm parameters.

**Comment by forceshorty** [comment]
@ZeldaHuang  Thank you for your answer.
Because all tp_ranks have save layernorm, Does it mean that we can use other rank's layernorm weight, not just tp_rank0 in checkpoint convert script?

**Comment by ZeldaHuang** [comment]
Yes, but tp_rank0 always exists, so we load weight from tp_rank0.
