### ISSUE TITLE
Any plan for supporting overlapping collective communication for data parallel?

### ISSUE THREAD

**Issue by li-yi-dong** [NVIDIA/Megatron-LM#391]
When training with `DistributedOptimizer`, there would be a long collective communication before `optimizer.step`. Is there any plan to overlap this collective communication with backward computation?

**Comment by nullnonenilNULL** [comment]
same problem

**Comment by jon-barker** [comment]
Hi. Yes, this is in the development plan however pipelining and other optimizations we've added make it complicated so we don't have an estimated time for completion yet.

**Comment by li-yi-dong** [comment]
> Hi. Yes, this is in the development plan however pipelining and other optimizations we've added make it complicated so we don't have an estimated time for completion yet.

Hope to see it soon : )

**Comment by deepakn94** [comment]
This is now supported with the `--overlap-grad-reduce` command-line flag: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/arguments.py#L1013.
