### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'overlap_p2p_comm'

### ISSUE THREAD

**Issue by xealml** [NVIDIA/Megatron-LM#393]
Traceback (most recent call last):
  File "../pretrain_gpt.py", line 115, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/data1/limenglin/Megatron-LM/megatron/training.py", line 155, in pretrain
    iteration = train(forward_step_func,
  File "/data1/limenglin/Megatron-LM/megatron/training.py", line 705, in train
    train_step(forward_step_func,
  File "/data1/limenglin/Megatron-LM/megatron/training.py", line 434, in train_step
    overlap_p2p_comm=args.overlap_p2p_comm,
AttributeError: 'Namespace' object has no attribute 'overlap_p2p_comm'

**Comment by jon-barker** [comment]
Hi. What commit of Megatron-LM are you using and what command line args for pretrain_gpt.py?  I don't see this issue in `main` with or without `--overlap_p2p_communication`

**Comment by xealml** [comment]
> 

commit 4f8e9ac412eff9cabae31495b9f5f3f02fe5a9d4 (HEAD -> main, tag: 23.06, origin/master, origin/main, origin/HEAD)
Merge: 2004f03 23329e2
Author: Jared Casper <jcasper@nvidia.com>
Date:   Wed Jun 28 14:38:03 2023 -0700

    Merge branch 'jbarker/preprocessing_workers' into 'main'
    
    Make --workers required in preprocess_data.py
    
    See merge request ADLR/megatron-lm!647

**Comment by jon-barker** [comment]
Can you please provide the hardware configuration (number of nodes + GPUs) you are using the command line args you are using for `pretrain_gpt.py`? I cannot replicate this using that same commit on a single node or multiple nodes with or without `--overlap-p2p-communication`

**Comment by xealml** [comment]
> 

hi, with a100*8

**Comment by jon-barker** [comment]
Please provide the command line args you are using with `pretrain_gpt.py`. I cannot replicate this issue on 8xA100 with the details you've provided.

**Comment by deepakn94** [comment]
Going to close this, please re-open with more details so that we can triage approrpriately.
