### ISSUE TITLE
the whole dataset published in hugingface

### ISSUE THREAD

**Issue by etoilestar** [NVIDIA/Megatron-LM#395]
hello, could you give me some guides about how to use the whole dataset published in https://huggingface.co/datasets/openwebtext, I find these dataset are compressed in .xz files, I don't know how to convert to .json file.

**Comment by lmcafee-nvidia** [comment]
One of the files listed on that dataset page is `openwebtext.py` for processing the data. Have you tried using this script?

More generally, a `xz` file can be extracted using the `tar` command.

Once you are able to access the raw text within that dataset, then you can write a simple script that outputs a jsonl file that follows the format detailed here: https://github.com/NVIDIA/Megatron-LM#data-preprocessing

**Comment by etoilestar** [comment]
Yes, I tried to use that project, but the network here is not easy to download. I found that those .xz files contain a lot of corpus information, which should be the files obtained after downloading, but I don’t know what is the connection with the json file needed for this project. Thank you for your help
