### ISSUE TITLE
preprocessing script for RETRO does not have all the arguments

### ISSUE THREAD

**Issue by spitzfire** [NVIDIA/Megatron-LM#407]
While running run preprocess_data.sh for retro, I'm getting 
`main.py: error: the following arguments are required: --retro-gpt-data-path, --retro-gpt-eval-interval, --retro-gpt-eval-iters, --retro-gpt-global-batch-size, --retro-index-ntrain`
It seems like these arguments were added in e68e57a220d75358bd1842225c6b3776c3f143a2. but  https://github.com/NVIDIA/Megatron-LM/blob/main/tools/retro/examples/preprocess_data.sh does not support these arguments.

**Comment by lmcafee-nvidia** [comment]
Thank you for pointing this out, example scripts sometimes get behind :). `preprocess_data.sh` and `pretrain_model.sh` have both been updated with the latest arguments, so please try using them again.
