### ISSUE TITLE
How to use flash attention when setting "--reset-position-ids"?

### ISSUE THREAD

**Issue by t90tank** [NVIDIA/Megatron-LM#415]
It seems that Megatron do not pass attention mask to flash attention,  but when setting "--reset-position-ids", different inputs have different attention masks.
Does Megatron support this case? 

Also, can we open sequence parallel when setting "--reset-position-ids"?

**Comment by torshie** [comment]
It seems --reset-position-ids doesn't work with flash attention. I checked flash attention's API, it supports causal attention mask only, not custom attention masks.

**Comment by mayank31398** [comment]
Yes, this won't work
See this PR: https://github.com/bigcode-project/Megatron-LM/pull/53 in the BigCode fork

**Comment by t90tank** [comment]
Thanks, I will try other ways.
