### ISSUE TITLE
[QUESTION] Question about the `matmul_input_buffer` variable in the `CoreAttention` module

### ISSUE THREAD

**Issue by cordercorder** [NVIDIA/Megatron-LM#421]
In Megatron-LM, the `forward` function of the `CoreAttention` module contains a variable called `matmul_input_buffer`, which is utilized as an argument in the `torch.baddbmm` function with a beta value set to 0. However, according to the PyTorch [documentation](https://pytorch.org/docs/stable/generated/torch.baddbmm.html?highlight=baddbmm#torch.baddbmm), if beta is set to 0, the `matmul_input_buffer` variable will be ignored. Therefore, it raises the question: Why is the `matmul_input_buffer` variable used in this context, and what is the effect of this variable?

For convenience, the pertinent code snippet is presented below for reference:

https://github.com/NVIDIA/Megatron-LM/blob/040eac9414ccbd1301ae16369c3044c5632b7e14/megatron/model/transformer.py#L243-L276

**Comment by mayank31398** [comment]
Hey, I think the output is stored back in the first argument of the `torch.baddbmm`.
This basically acts as a buffer so PyTorch doesn't have to allocate another buffer for the output tensor and is thus more efficient.
