### ISSUE TITLE
[ENHANCEMENT] Support for LLaMA and LLaMA-2

### ISSUE THREAD

**Issue by lvcc2018** [NVIDIA/Megatron-LM#423]
Support for LLaMA and LLaMA-2

**Comment by jon-barker** [comment]
In theory you could pre-train LLaMA today in Megatron-LM. The only known blocker to pre-training LLaMA 2 is that we don't currently support GQA but we are actively working to add that soon. We don't have the configurations and scripts available out-of-the-box for doing the LLaMA pre-training so you'd have to implement those yourself but all the building blocks should be available.

**Comment by nrailg** [comment]
> In theory you could pre-train LLaMA today in Megatron-LM. The only known blocker to pre-training LLaMA 2 is that we don't currently support GQA but we are actively working to add that soon. We don't have the configurations and scripts available out-of-the-box for doing the LLaMA pre-training so you'd have to implement those yourself but all the building blocks should be available.

Oh, Thank U~
May I ask when will all these blocks be available? (like RMS Norm, GQA...)

Recently I am working on implementing llama 1 and llama 2 in Megatron-LM. If these blocks will be release in several weeks, I can simply wait XD. @jon-barker 

-------------

By the way, RMS Norm is not supported yet (but available in apex).

**Comment by echoyinke** [comment]
I hack the transformer.py to use apex's RMS norm, it does not work in sequence parallel...

**Comment by li-yi-dong** [comment]
@echoyinke @nrailgun @lvcc2018 
You may look into https://github.com/alibaba/Megatron-LLaMA

**Comment by martinjaggi** [comment]
or https://github.com/epfLLM/Megatron-LLM  (this one supports llama and falcon)
