### ISSUE TITLE
[QUESTION] Does the zero-out operation conduct during the model initialization and affect reproducibility?

### ISSUE THREAD

**Issue by zxgx** [NVIDIA/Megatron-LM#427]
**Your question**

As indicated in the annotation, embedding weight in the last stage would be zeroed out. 
I doubt that this zero-out operation is not conducted, as the two conditions in the `if` statement in L87 are contradictory.
But I assume that, finally after the model initialization, the two embedding weights in `self.language_model.embedding` and `self.word_embeddings` would be added up by the following `all_reduce` anyway, so the two weight matrices would still be the same, am I right? 
If so, I assume this problem may lead to some reproducibilitiy issue since the following `all_reduce` changes the initial embedding weight imported from other models.

Just close this issue if I'm wrong 😄 

https://github.com/NVIDIA/Megatron-LM/blob/6ef5bdc9fbe030c45d9f7a19e6c42d39f844aaa7/megatron/model/module.py#L85-L89

```[tasklist]
### Tasks
```

**Comment by jaredcasper** [comment]
This is for the T5 model where you have an embedding layer as part of the first stage in the decoder, which isn't the first stage of the overall pipeline. In that case, and when using the embedding weights as the weights for the output layer, there are three copies of the embedding weights: at the beginning of the encoder, beginning of the decoder, and the output layer.

This code isn't run for GPT or Bert models.

Does that answer the question?

**Comment by zxgx** [comment]
That's true! I must ignore some setup for encoder&decoder models because I follow scripts in `examples/sc21` to read the source code. 😵 

Thanks for your answer!
