### ISSUE TITLE
Are there any plans to add torch DDP with pipeline parallel?

### ISSUE THREAD

**Issue by mayank31398** [NVIDIA/Megatron-LM#428]
torch DDP is more efficient than local DDP since it overlaps comms with backward.
However, in its current state, the communication in local DDP doesn't do this.
Are there plans to add this?

**Comment by jon-barker** [comment]
Yes: https://github.com/NVIDIA/Megatron-LM/issues/391

**Comment by mayank31398** [comment]
Thanks a lot for the quick reply :)

**Comment by mayank31398** [comment]
would love to contribute to this btw.
if this has already started and you have some pointers :)

**Comment by jon-barker** [comment]
There hasn't been any work in earnest yet, although we'd like to get to it soon due to the potential training speedup. We hope/believe it can be achieved with a relatively small amount of code. So we'd welcome help/contribution but it'd be best to take small steps and start with a proposal we can iterate on as necessary. Thanks!

**Comment by li-yi-dong** [comment]
> There hasn't been any work in earnest yet, although we'd like to get to it soon due to the potential training speedup. We hope/believe it can be achieved with a relatively small amount of code. So we'd welcome help/contribution but it'd be best to take small steps and start with a proposal we can iterate on as necessary. Thanks!

Hi @jon-barker,

We implemented it in https://github.com/alibaba/Megatron-LLaMA/blob/main/megatron/optimizer/overlapped_dist_optimizer.py. 
In certain cases, it works really well.

**Comment by deepakn94** [comment]
We recently re-wrote the DDP wrapper to support overlapping of all-reduce with backprop computation: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/distributed.py. It can be turned on using the `--overlap-grad-reduce` command-line argument. The current version does not yet support the distributed optimizer, but this is coming soon.

**Comment by cicirori** [comment]
> We recently re-wrote the DDP wrapper to support overlapping of all-reduce with backprop computation: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/distributed.py. It can be turned on using the `--overlap-grad-reduce` command-line argument. The current version does not yet support the distributed optimizer, but this is coming soon.

@deepakn94 I noticed that there is an implementation of distributed adam in apex that supports overlap for communication calculations and is used in nemo. 

Not quite sure the reason why megatron-lm has to implement its own version, but as a user (who makes some internal changes occasionally), megatron-lm's recent code quality and confusing roadmap has been very frustrating (as a very simple example, the latest ddp implementation is not compatible with distributed optimizer. But you can turn on both options without any errors). It's as if there are a thousand teams inside nvidia working on the llm training framework.

**Comment by deepakn94** [comment]
The latest DDP implementation should support all possible usecases in the next week or so (distributed optimizer, pipeline parallelism). We have an internal implementation working that is making its way through peer review.

What are the issues with Megatron's code quality?
