### ISSUE TITLE
[BUG] Fail to apply GQA when using pipeline parallel.

### ISSUE THREAD

**Issue by MoFHeka** [NVIDIA/Megatron-LM#437]
**Describe the bug**
view op in attention calculation error when enable groups_query_attention and num-query-groups=2 and pipeline-model-parallel-size=2 in one A100 machine

**To Reproduce**
any GPT model

**Expected behavior**
GQA work fine when pipeline parallel

**Stack trace/logs**
```shell
  File "/usr/local/lib/python3.10/dist-packages/megatron/model/transformer.py", line 750, in forward                                                                                      │
    query_layer = query_layer.view(query_layer.size(0), query_layer.size(1), -1, self.hidden_size_per_attention_head)                                                                     │
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead. 
```

**Environment (please complete the following information):**
 - Megatron-LM commit ID
 - PyTorch version 2.1
 - CUDA version 12.1
 - NCCL version

**Comment by stgzr** [comment]
Same issue.
Just fix it with `reshape` method?

**Comment by shaonan1993** [comment]
Same question.

**Comment by deepakn94** [comment]
This is a bug, I believe. I think `reshape()` should be a reasonable workaround for now.
