### ISSUE TITLE
Incorporating Megatron-ML with DeepSpeed

### ISSUE THREAD

**Issue by msmolyak** [NVIDIA/Megatron-LM#44]
Microsoft incorporated Megatron-LM with their DeepSpeed project in [DeepSpeedExamples](https://github.com/microsoft/DeepSpeedExamples) project. The combination of the two projects features increased speed and lower memory requirements compared to standalone Megatron-LM model. However, the version of Megatron-LM used in DeepSpeedExamples dates to February of 2020 and as such lacks the latest updates of your product. Have you considered supporting an up-to-date version of Megatron-LM integrated with DeepSpeed project?

**Comment by jon-barker** [comment]
Closing. This issue should be addressed to the DeepSpeed developers at Microsoft: https://github.com/microsoft/DeepSpeed/
