### ISSUE TITLE
[QUESTION] Why does each pipeline layer initialize and read datasets separately?

### ISSUE THREAD

**Issue by liu-zichen** [NVIDIA/Megatron-LM#441]
Currently each pipeline layer (i.e. tensor model parallel group) initializes and reads datasets separately.
However, I think that all ranks in the model parallel group ($tp \times pp$) should view the same inputs.
If my understanding above is correct, the correctness of the model training now relies on the first pipeline and the last pipeline reading the same data without any random factor.
But why not read and broadcast data in model parallel group?

Each rank0 in tensor model parallel group would build datasets:
https://github.com/NVIDIA/Megatron-LM/blob/65da5be50cdaad2205e0bc96295bcaaf2c2c2a34/megatron/training.py#L982
The read data is broadcast in tensor model parallel group:
https://github.com/NVIDIA/Megatron-LM/blob/65da5be50cdaad2205e0bc96295bcaaf2c2c2a34/pretrain_gpt.py#L49

**Comment by deepakn94** [comment]
Yup, this could certainly be done.
