### ISSUE TITLE
[QUESTION] Why is additional allreduce necessary for layernorm in sequence parallelism scenarios? 

### ISSUE THREAD

**Issue by baoleai** [NVIDIA/Megatron-LM#443]
**Your question**
I noticed that in the [optimizer](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/optimizer/optimizer.py#L256) , there is an `allreduce_layernorm_grads` function when sequence parallelism is used. However, I could not find any explanation for this in the paper or other related issues.

**Comment by cicirori** [comment]
section 4.2.2 from [Reducing Activation Recomputationin Large Transformer Models](https://arxiv.org/abs/2205.05198).
In sequence parallellism, layernorm is split by sequence in tp groups.

**Comment by baoleai** [comment]
According to section 4.2.2 of the paper [Reducing Activation Recomputation in Large Transformer Models](https://arxiv.org/abs/2205.05198), when using tensor parallelism (TP) with sequence parallelism (SP), the only communication operations required are all-gather and reduce-scatter. However, it is unclear if there are any further optimizations that can be made.

**Comment by cicirori** [comment]
> According to section 4.2.2 of the paper [Reducing Activation Recomputation in Large Transformer Models](https://arxiv.org/abs/2205.05198), when using tensor parallelism (TP) with sequence parallelism (SP), the only communication operations required are all-gather and reduce-scatter. However, it is unclear if there are any further optimizations that can be made.

Since it's split by sequence, I suppose you could think of it as parallelizing the "data"(sequence)  within a tensor parallel group.

**Comment by Barber0** [comment]
> > According to section 4.2.2 of the paper [Reducing Activation Recomputation in Large Transformer Models](https://arxiv.org/abs/2205.05198), when using tensor parallelism (TP) with sequence parallelism (SP), the only communication operations required are all-gather and reduce-scatter. However, it is unclear if there are any further optimizations that can be made.
> 
> Since it's split by sequence, I suppose you could think of it as parallelizing the "data"(sequence) within a tensor parallel group.

Can I understand it this way? Assuming world_size=2, seq_length=2048, when the sequence is passed to LayerNorm, the first 1024 tokens and the last 1024 tokens of the sequence will be calculated using different LayerNorms (different weights and bias).

If I want to make convert the parallelized weights into one that can run on single GPU, how should I deal with these split-LayerNorm?

**Comment by baoleai** [comment]
@Barber0  I think the weights in LayerNorm are not split, so you can choose just one of them.
