### ISSUE TITLE
[QUESTION] Can I use the pytorch_model.bin format file in huggingface as pre-training initialization weights?

### ISSUE THREAD

**Issue by chenglong0313** [NVIDIA/Megatron-LM#451]
Can I use the pytorch_model.bin format file in huggingface as pre-training initialization weights?

like this：
![11](https://github.com/NVIDIA/Megatron-LM/assets/30063446/7f8234c1-e353-4d16-9ecd-949fa3910efd)

**Comment by jon-barker** [comment]
Huggingface Accelerate offers some interoperability with Megatron, see here: https://huggingface.co/docs/accelerate/usage_guides/megatron_lm

Linked from that page is a conversion script for Megatron-LM GPT models to Huggingface. https://github.com/huggingface/transformers/blob/main/src/transformers/models/megatron_gpt2/checkpoint_reshaping_and_interoperability.py

This functionality is provided by Huggingface, not NVIDIA/Megatron-LM so it would be best to ask them for further support. Hope that helps.
