### ISSUE TITLE
Data is too large to be stored in only one file(preprocess_data.py)[QUESTION]

### ISSUE THREAD

**Issue by AlvL1225** [NVIDIA/Megatron-LM#452]
**Your question**
Hi, the doc says 'preprocess_data.py' will generate 2 files(bin and index).But for over 1T tokens dataset, the file is too large to save. Can the 'preprocess_data.py' generate several data shards?

**Comment by janEbert** [comment]
The way I've done it is to manually split the JSON file into shards, use `preprocess_data.py` to process each shard, then merge using `merge_datasets.py`.

**Comment by jon-barker** [comment]
Yes, @janEbert 's workflow is the best approach.

**Comment by AlvL1225** [comment]
> Yes, @janEbert 's workflow is the best approach.

Hi @jon-barker , I tried this but merge_dataset.py will still create a very huge file. Is it possible to only create a merged index but keep bin files sharded?

**Comment by AlvL1225** [comment]
> The way I've done it is to manually split the JSON file into shards, use `preprocess_data.py` to process each shard, then merge using `merge_datasets.py`.

Hi @janEbert , will this workflow still create a huge bin file? What I am worrying is that one single merged huge file(probably larger than 2TB) may cause storage problem in some storage systems.

**Comment by janEbert** [comment]
You're right, sorry; the thing I wrote doesn't solve your issue.

**Comment by AlvL1225** [comment]
> You're right, sorry; the thing I wrote doesn't solve your issue.

Thank you for your advice!

I still have another question.

For a common file system(like NFS or XFS), this may not be a problem I guess? Did everyone use one single file(TB level) when using MegatronLM? If so, my worrying might be unnecessary.

**Comment by janEbert** [comment]
I work on a file system on which single, very large files are highly preferred (it's a GPFS). I am not familiar enough with other file systems' intricacies to make any statements, sorry. :)

**Comment by AlvL1225** [comment]
> I work on a file system on which single, very large files are highly preferred (it's a GPFS). I am not familiar enough with other file systems' intricacies to make any statements, sorry. :)

It's also very helpful to know that, thanks!
