### ISSUE TITLE
[QUESTION] Is there any code example to use grad_sync_func to overlap data parallel reduce-scatter?

### ISSUE THREAD

**Issue by Vic0428** [NVIDIA/Megatron-LM#456]
Hi all,

Is there any code example to use `grad_sync_func` to overlap data parallel reduce-scatter?  It seems that the `grad_sync_func` is not being used in `training.py`. I am trying to understand how much reduce-scatter can be overlapped in the backward pass :)

![7c197ebf-fcee-40f2-af62-5098366681b6](https://github.com/NVIDIA/Megatron-LM/assets/32806151/582120d7-6342-4b87-8d32-0dfddc6e247a)

Have a nice day!
~Vic

**Comment by li-yi-dong** [comment]
> Hi all,
> 
> Is there any code example to use `grad_sync_func` to overlap data parallel reduce-scatter? It seems that the `grad_sync_func` is not being used in `training.py`. I am trying to understand how much reduce-scatter can be overlapped in the backward pass :)
> 
> ![7c197ebf-fcee-40f2-af62-5098366681b6](https://user-images.githubusercontent.com/32806151/259574144-582120d7-6342-4b87-8d32-0dfddc6e247a.jpeg)
> 
> Have a nice day! ~Vic

You may look into this one: https://github.com/alibaba/Megatron-LLaMA/blob/main/megatron/optimizer/overlapped_dist_optimizer.py

**Comment by deepakn94** [comment]
This is now supported using the `--overlap-grad-reduce` command-line argument: https://github.com/NVIDIA/Megatron-LM/commit/e801b2bb2f24ad12b2b21efb0c07a717d82335d0.

**Comment by deepakn94** [comment]
It is called here: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/pipeline_parallel/schedules.py#L327.
