### ISSUE TITLE
[QUESTION] Is there a way to change the weights of datasets in BlendableDataset

### ISSUE THREAD

**Issue by xiaojunjie** [NVIDIA/Megatron-LM#457]
**Your question**
Given a [BlendableDataset](https://github.com/NVIDIA/Megatron-LM/blob/0609f27fe8376f17ab65c001d3d8f35cd8175950/megatron/data/blendable_dataset.py#L15C43-L15C43) of dataset A and B with weights 1:1
After training N iterations，change weights to 2:1 and continue from saved checkpoint
According to BlendableDataset,  it will loss some samples of A, and repeat some samples of B
Is there a good way to avoid data loss and duplication？

**Comment by akhilkedia** [comment]
This feature would indeed be very useful if this was implemented.

**Comment by SefaZeng** [comment]
@xiaojunjie Hi, do you solve this issue?

**Comment by haidark** [comment]
This isn't currently supported in MegatronLM. This PR [here](https://github.com/NVIDIA/Megatron-LM/pull/725) adds support for this.

**Comment by felipeliliti** [comment]
Libero
