### ISSUE TITLE
Malicious domain name in openwebtext URL list

### ISSUE THREAD

**Issue by abhinavs95** [NVIDIA/Megatron-LM#46]
I was following the instructions for preparing openwebtext dataset using instructions here: https://github.com/NVIDIA/Megatron-LM/blob/main/tools/openwebtext/README.md

In the URL list downloaded from the link in Step 1 of Download the dataset, one of the domain names ("horsefucker.org") is associated with a known C&C server. This caused security vulnerability on my system. The blacklist_urls list must be updated with this domain name so that its filtered before data download begins.

**Comment by jon-barker** [comment]
Will update blacklist

**Comment by jon-barker** [comment]
Fixed: https://github.com/NVIDIA/Megatron-LM/commit/780978175455afadc78eceea2c8f63ee4fceec7b - thanks for highlighting this
