### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by airicairic** [NVIDIA/Megatron-LM#462]
**Describe the bug**
task/eval_utils.py has an import error from previous version.

**To Reproduce**
Run a task, e.g. RACE

**Expected behavior**
Should import successfully

**Stack trace/logs**
tasks/eval_utils.py", line 14, in <module>
        from megatron.schedules import get_forward_backward_funcfrom megatron.schedules import get_forward_backward_func

    ModuleNotFoundErrorModuleNotFoundError    from megatron.schedules import get_forward_backward_func: : from megatron.schedules import get_forward_backward_func    
No module named 'megatron.schedules'        No module named 'megatron.schedules'

**Proposed fix**
Change import to:

from megatron.core.pipeline_parallel import get_forward_backward_func

**Comment by airicairic** [comment]
megatron/model/multiple_choice.py", line 42, in __init__
    init_method)
NameError: name 'init_method' is not defined

use init_method_normal or import init_method_normal as init_method

**Comment by LittletreeZou** [comment]
Met the same issue when trying to finetune the model. Can be handled by `from megatron.core.pipeline_parallel import get_forward_backward_func`
