### ISSUE TITLE
[QUESTION] Do the functionalities of flash attention and selective recomputation overlap?

### ISSUE THREAD

**Issue by forpanyang** [NVIDIA/Megatron-LM#464]
**Your question**
As the paper [Reducing Activation Recomputation in Large Transformer Models](https://arxiv.org/abs/2205.05198) described, selective recomputation mainly saved the intermediate activation of attention. It seems the optimization chance vanished if one uses [flash-attention](https://github.com/Dao-AILab/flash-attention).

**Comment by deepakn94** [comment]
~They are orthogonal. FlashAttention reduces the memory footprint of the attention layer by not fully materializing `KQ^T`; selective recomputation also reduces the footprint of the FFN / MLP layers.~

**Comment by deepakn94** [comment]
Closing this, feel free to re-open if you still have questions.

**Comment by SeunghyunSEO** [comment]
> They are orthogonal. FlashAttention reduces the memory footprint of the attention layer by not fully materializing `KQ^T`; selective recomputation also reduces the footprint of the FFN / MLP layers.

but whether i disable selective ckpt or not, its max reserved remains same.
but mfu improved a lot when recompute option is set as false.

and following the paper, i only notice selective methods checkpoint qk term, its softmax and dropout activations not mlp.
so i doubt it does not save anything when flash attention is used..?

@deepakn94

**Comment by deepakn94** [comment]
You are right, updated my original comment.

Selective recomputation should not be needed if using Flash Attention.
