### ISSUE TITLE
[QUESTION] Does the functionality of P2P overlap working for 1F1B scheduler?

### ISSUE THREAD

**Issue by wuziyou199217** [NVIDIA/Megatron-LM#465]
**Your question**
I've noticed that the functionality of P2P overlap has been implemented for interleaved pipeline scheduler, is there any possibility to port it to 1F1B pipeline scheduler theoretically?

**Comment by deepakn94** [comment]
We don't currently have plans to support this unfortunately. What is your use case?

**Comment by robotsp** [comment]
@wuziyou199217 Did you implement the overlap?
