### ISSUE TITLE
[ENHANCEMENT] P2P overlap for 1F1B pipeline scheduler

### ISSUE THREAD

**Issue by wuziyou199217** [NVIDIA/Megatron-LM#466]
**Is your feature request related to a problem? Please describe.**
For now, P2P overlap only supports interleaved pipeline scheduler. However, I've find that interleaved pipeline leads to different checkpoint format, which makes it more difficult to convert the checkpoint format. 

**Describe the solution you'd like**
Support P2P overlap for 1F1B pipeline scheduler

**Describe alternatives you've considered**
None

**Proposed implementation**
None

**Additional context**
None

**Comment by deepakn94** [comment]
Closing this since this issue overlaps with #465.
