### ISSUE TITLE
[BUG] num_layers must be divisible by transformer_pipeline_model_parallel_size * virtual_pipeline_model_parallel_size

### ISSUE THREAD

**Issue by cicirori** [NVIDIA/Megatron-LM#468]
**Describe the bug**
num_layers must be divisible by transformer_pipeline_model_parallel_size * virtual_pipeline_model_parallel_size
Megatron only did follow checks:
```
    if args.num_layers_per_virtual_pipeline_stage is not None:
        assert args.pipeline_model_parallel_size > 2, \
            'pipeline-model-parallel size should be greater than 2 with ' \
            'interleaved schedule'
        assert args.num_layers % args.num_layers_per_virtual_pipeline_stage == 0, \
            'number of layers is not divisible by number of layers per virtual ' \
            'pipeline stage'
        args.virtual_pipeline_model_parallel_size = \
            (args.num_layers // args.transformer_pipeline_model_parallel_size) // \
            args.num_layers_per_virtual_pipeline_stage
```
If I have a mode with 80 layers pp=16 vp=2, it will pass all checks and running successfully.
But in this case it's actually running a model with 64 layers.

virtual_pipeline_model_parallel_size would be set to 2 in this case. (2.5 without `//` )

After executing the following two pieces of code, there are 2 layers on each device:
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/transformer.py#L1365
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/transformer.py#L1436

So, the actual num_layers would be `2*2*16=64`, not 80. So, additional assertion should be added.

**Comment by deepakn94** [comment]
Thank you for this! We have patched this internally, and it should reflect in Github soon.
