### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by airicairic** [NVIDIA/Megatron-LM#469]
**Describe the bug**
Datapath set to dataset list now causes error.

**To Reproduce**
Try to use a list of datasets.

**Expected behavior**
Trains on multiple datasets according to assigned percentages.

**Stack trace/logs**
megatron/data/blendable_dataset.py", line 51, in __init__
    desc += dataset.desc + "\n\n"
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError

**Comment by deepakn94** [comment]
Can you post the full command-line that produced this error? A full stack trace would be helpful too.

**Comment by deepakn94** [comment]
Going to close this, please re-open with more details if you are still running into this issue.
