### ISSUE TITLE
[QUESTION] What does persistent layer norm kernel mean?

### ISSUE THREAD

**Issue by Barber0** [NVIDIA/Megatron-LM#475]
I am reading and learning the source code of Megatron-LM. I am curious about the concept `persistent layer norm kernel`.

There's a comment in [fused_layer_norm.py](https://github.com/NVIDIA/Megatron-LM/blob/f24fac4ed0dcf0522056521a93445d9a82f501a9/megatron/core/fusions/fused_layer_norm.py#L40C10-L40C10) shows that 
`List of hiddens sizes supported in the persistent layer norm kernel
 If the hidden size is not supported, fall back to the non-persistent
 kernel."`

What does **persistent layer norm kernel** mean?

**Comment by jon-barker** [comment]
This refers to the use of persistent threads in the apex layer norm kernel I believe. So it's a kernel that does not exit and is continually polling for work from a queue in global memory.
