### ISSUE TITLE
[QUESTION] how to use SHARP with Megatron

### ISSUE THREAD

**Issue by hwdef** [NVIDIA/Megatron-LM#476]
I checked the source code and found the following message:

https://github.com/NVIDIA/Megatron-LM/blob/f24fac4ed0dcf0522056521a93445d9a82f501a9/megatron/core/parallel_state.py#L200C14-L200C14

```python
# Apply SHARP to DP process groups
    if use_sharp:
        if rank == 0:
            print(
                "The number of process groups to use SHARP with depends on the type "
                "of the network switch. Nvidia QM1 switch supports SAHRP up to 8 "
                "process groups and QM2 supports up to 256 process groups. We apply "
                "SHARP to the communications of the data-parallel domain. If the "
                "number of data-parallel process groups is larger than the max "
                "process groups that the network switch supports, the communication "
                "will fall back to non-SHARP operators. To enable SHARP, "
                "`#SBATCH_NETWORK=sharp` should be set in the sbatch script."
            )
        torch.distributed.barrier(
            group=get_data_parallel_group(), device_ids=[torch.cuda.current_device()]
        )
        # Set `NCCL_SHARP_DISABLE=1` to restrict SHARP application to DP process groups
        os.environ["NCCL_SHARP_DISABLE"] = "1"
```

Megatron wants to use sharp when DP, so it turns off SHARP globally. I'm guessing that Megatron turns SHARP on at DP time, but I haven't found the code for that.

Searching for NCCL_SHARP_DISABLE globally, I only found one. It's the above global disable SHARP

![image](https://github.com/NVIDIA/Megatron-LM/assets/13084946/208f39df-9b3d-4d60-a6f1-546791094f04)

Right now I'm in a situation where Megatron is requesting too many pg, resulting in insufficient resource SHARP resources. I want to know what to do in this situation

**Comment by hwdef** [comment]
@erhoo82 

Could you help me ?

**Comment by cicirori** [comment]
```
        torch.distributed.barrier(
            group=get_data_parallel_group(), device_ids=[torch.cuda.current_device()]
        )
```
This line calls nccl allreduce, which triggers the initialization of the nccl comm used by the dp group, with sharp enabled.

**Comment by hwdef** [comment]
> ```
>         torch.distributed.barrier(
>             group=get_data_parallel_group(), device_ids=[torch.cuda.current_device()]
>         )
> ```
> 
> This line calls nccl allreduce, which triggers the initialization of the nccl comm used by the dp group, with sharp enabled.

Do I need to set any additional environment variables?

**Comment by erhoo82** [comment]
As the comment says, you need to set `#SBATCH_NETWORK=sharp` in your sbatch script assuming you are using slurm. COLLNET_DIRECT algorithm is supposed to be used for the collective kernels when all conditions for SHARP are met. However, you can add these env vars to help enabling SHARP `NCCL_ALGO=CollNetDirect` and `NCCL_SHARP_GROUP_SIZE_THRESH=2`.

**Comment by hwdef** [comment]
> As the comment says, you need to set `#SBATCH_NETWORK=sharp` in your sbatch script assuming you are using slurm. COLLNET_DIRECT algorithm is supposed to be used for the collective kernels when all conditions for SHARP are met. However, you can add these env vars to help enabling SHARP `NCCL_ALGO=CollNetDirect` and `NCCL_SHARP_GROUP_SIZE_THRESH=2`.

I use k8s. I already added these env in the container. But I consistently get the SHARP insufficient resources error, and I'm using ConnectX-6.


I have two other confusing points:

1
In the code, it is the first call to the
```python
torch.distributed.barrier(
    group=get_data_parallel_group(), device_ids=[torch.cuda.current_device()]
)
```
After calling
```python
os.environ["NCCL_SHARP_DISABLE"] = "1"
```

If the top one is OPEN and the bottom one is CLOSE, then first the SHARP is turned OPEN at the DP and then it's turned CLOSE globally, I understand that the OPEN won't take effect? Because it was turned OPEN and then turned CLOSE again.


2
Has megartron created too many groups?

```python
    for i in range(pipeline_model_parallel_size):
        start_rank = i * num_pipeline_model_parallel_groups
        end_rank = (i + 1) * num_pipeline_model_parallel_groups
        for j in range(tensor_model_parallel_size):
            ranks = range(start_rank + j, end_rank, tensor_model_parallel_size)
            all_data_parallel_group_ranks.append(list(ranks))
            group = torch.distributed.new_group(ranks)
            group_gloo = torch.distributed.new_group(ranks, backend="gloo")
            if rank in ranks:
                _DATA_PARALLEL_GROUP = group
                _DATA_PARALLEL_GROUP_GLOO = group_gloo
                _DATA_PARALLEL_GLOBAL_RANKS = ranks
```

The above code calls `new_group` after a double *for* loop, does this create too many groups, resulting in insufficient SHARP resources?

**Comment by erhoo82** [comment]
> 1. If the top one is OPEN and the bottom one is CLOSE, then first the SHARP is turned OPEN at the DP and then it's turned CLOSE globally, I understand that the OPEN won't take effect? Because it was turned OPEN and then turned CLOSE again.

Yes, the DP groups that we set barrier to set them as the target apply SHARP should not be affected with the env var disabled.

> 2. The above code calls new_group after a double for loop, does this create too many groups, resulting in insufficient SHARP resources?

Can you try with a few data-parallel groups? I have tested this on QM1 with DP=8 and QM2 with DP16, and both worked for me.

**Comment by hwdef** [comment]
@erhoo82 Thank you!

**Comment by tangjiangling** [comment]
> NCCL_SHARP_DISABLE

@erhoo82 Where is this parameter used, I don't find a reference to it in the `nccl` documentation or code.

One more question: why don't you turn on sharp globally in [this commit](https://github.com/NVIDIA/Megatron-LM/commit/96420eaa80fb7f70015adef358d571e627163b50), but rather on the DP.

**Comment by tangjiangling** [comment]
> Where is this parameter used, I don't find a reference to it in the nccl documentation or code.

Oh, I found it [here](https://github.com/Mellanox/nccl-rdma-sharp-plugins/blob/master/src/sharp_plugin.c#L249).

**Comment by tangjiangling** [comment]
> One more question: why don't you turn on sharp globally in [this commit](https://github.com/NVIDIA/Megatron-LM/commit/96420eaa80fb7f70015adef358d571e627163b50), but rather on the DP.

I got it, it's because DPs usually communicate across machines and need to use switches, so turn on IB sharp between DPs.

**Comment by deepakn94** [comment]
Going to close this, feel free to re-open if you still have questions.

**Comment by Lzhang-hub** [comment]
> I use k8s

@hwdef 
I also use k8s, are there other ENV needed to set for megatron to use sharp?
