### ISSUE TITLE
[ENHANCEMENT] Enhance data efficiency with efficient sequence packing

### ISSUE THREAD

**Issue by Barber0** [NVIDIA/Megatron-LM#478]
As far as I know, Megatron-LM requires the input sequence length to be fixed and padded to the `--seq-length`. However, for some SFT datasets like [tatsu-lab/alpaca](https://huggingface.co/datasets/tatsu-lab/alpaca) or [Open-Orca/OpenOrca](https://huggingface.co/datasets/Open-Orca/OpenOrca), whose encoded sequence length rarely reach to 2048-tokens, that would cause waste of computing resource.

Does Megatron team have plan to apply some efficient sequence packing methods like this paper: [Efficient Sequence Packing without Cross-contamination: Accelerating Large Language Models without Impacting Performance](https://arxiv.org/abs/2107.02027)?

Maybe the technique mentioned above can be added to the script: [preprocess_data.py](https://github.com/NVIDIA/Megatron-LM/blob/main/tools/preprocess_data.py).

**Comment by Leo-T-Zang** [comment]
Wonder the same thing
