### ISSUE TITLE
Reproduce 71.9 TFlops throughput

### ISSUE THREAD

**Issue by eric-haibin-lin** [NVIDIA/Megatron-LM#48]
Hi,

I wonder what batch size per GPU was used for the benchmark below, if I want to reproduce it? 
![scaling-mp](https://user-images.githubusercontent.com/5545640/95613680-2c160480-0a1a-11eb-8956-87ae5d5b4e15.png)

**Comment by eric-haibin-lin** [comment]
@jaredcasper any comment?

**Comment by jaredcasper** [comment]
This table is specifically looking at model parallelism so there is no data parallelism involved. The batch size given is the full and only batch size. With model parallelism "batch size per GPU" isn't really meaningful, as in this case all of the GPUs are working on the same data. Does that help?

**Comment by eric-haibin-lin** [comment]
@jaredcasper that makes sense! Thanks for answering me question!
