### ISSUE TITLE
[QUESTION] MHA to GQA Converter for LLaMA2 Support

### ISSUE THREAD

**Issue by eagle705** [NVIDIA/Megatron-LM#480]
Hello! I've been reviewing the process of training the LLaMA2 architecture from Megatron-LM recently and I'm interested in trying to convert MHA to GQA. I've confirmed that it's possible to train GQA from scratch, but I'd like to know `if there are plans for a conversion script to transform existing MHA checkpoints into GQA checkpoints`.

I attempted to convert the key and value weights using the following logic, but it didn't seem to work well:

```python
key = torch.mean(key.view([num_query_groups_per_partition, -1, hidden_size_per_attention_head, hidden_size]), dim=1).view([-1, hidden_size])
```

**Comment by eagle705** [comment]
I solved it

**Comment by coorful** [comment]
@eagle705 hi, how did you solve it？

**Comment by mrovx** [comment]
Any information on this?
