### ISSUE TITLE
 megatron-lm==1.1.5 and  megatron-lm==2.2.0

### ISSUE THREAD

**Issue by 60wanjinbing** [NVIDIA/Megatron-LM#484]
how to download  megatron-lm==1.1.5 and  megatron-lm==2.2.0 in python ?

**Comment by deepakn94** [comment]
You can see all tagged versions here: https://github.com/NVIDIA/Megatron-LM/tags. Doing something like: `git fetch origin; git checkout <tag>` should then give you the right version that you want.

**Comment by deepakn94** [comment]
Going to close this; feel free to re-open if you run into difficulties.
