### ISSUE TITLE
[QUESTION]why use the [s, b, h] data layout instead of [b, s, h]?

### ISSUE THREAD

**Issue by superzhangmch** [NVIDIA/Megatron-LM#493]
> [Efficient Large-Scale Language Model Training on GPU Clusters
> Using Megatron-LM](https://arxiv.org/pdf/2104.04473.pdf)
> 
> 4.2 Computation Optimizations
> We implemented three model-specific optimizations to the computation graph to attain high performance. 
> First, we changed the data layout in the transformer layer to avoid memory-intensive transpose operations, 
> and to enable the use of strided batched GEMM kernels. Specifically, we changed the data layout 
> from [𝑏, 𝑠, 𝑎, ℎ] to [𝑠, 𝑏, 𝑎, ℎ], where 𝑏, 𝑠, 𝑎, and ℎ are batch, sequence, attention-head, and hidden-size 
> dimensions, respectively.

It is mentioned in the above paper.

what (and where) are the memory-intensive transpose operations if we don't do so?  why it enables the use of strided batched GEMM kernels?

**Comment by Infi-zc** [comment]
for efficiency of seq_parallel

**Comment by superzhangmch** [comment]
> for efficiency of seq_parallel

according to the timeline of metatron-lm paper series, seq_parallel did not appear in this paper(Efficient Large-Scale Language Model Training on GPU Clusters Using Megatron-LM). It appeared firstly in the subsequent paper: [Reducing Activation Recomputation in Large Transformer Models](https://arxiv.org/pdf/2205.05198.pdf)
