### ISSUE TITLE
I do not know how to solve it.

### ISSUE THREAD

**Issue by CatFootPrint** [NVIDIA/Megatron-LM#5]
When I run
bash scripts/pretrain_bert.sh.
I encounter the error as follows:

`Traceback (most recent call last):
  File "pretrain_bert.py", line 581, in <module>
    main()
  File "pretrain_bert.py", line 528, in main
    args.tokenizer_num_type_tokens = get_train_val_test_data(args)
  File "pretrain_bert.py", line 475, in get_train_val_test_data
    (train_data, val_data, test_data), tokenizer = data_config.apply(args)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/configure_data.py", line 34, in apply
    return make_loaders(args)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/configure_data.py", line 170, in make_loaders
    train, tokenizer = data_utils.make_dataset(**data_set_args)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/data_utils/__init__.py", line 101, in make_dataset
    pad_token, character_converage, **kwargs)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/data_utils/tokenization.py", line 39, in make_tokenizer
    return BertWordPieceTokenizer(model_type, **kwargs)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/data_utils/tokenization.py", line 703, in __init__
    self.text_tokenizer.max_len = int(1e12)
AttributeError: 'NoneType' object has no attribute 'max_len'`

I cannot find the solution.
If someone can help me, thanks a lot.

**Comment by raulpuric** [comment]
so that indicates that self.text_tokenizer is None. Which means somehow that downloading the pretrained bert tokenizer failed.

There should be some other output from pytorch-transformers in your logs. Could you please share that. I would double check that you have write permissions to the `--cache-dir` and internet connection to download the models

**Comment by CatFootPrint** [comment]
You are right. I found that I cannot connect to the Internet. Thus, I downloaded the file, bert-base-uncased-vocab.txt and uploaded it to my server. Thanks very much and I appreciate your suggestion. However, the iteration will be terminated when I run pretrain.py.

The errors are given as follows:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/z00487393/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/z00487393/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 586, in <module>
    main()
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 564, in main
    timers, args)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 370, in train
    prefix, val_data_iterator, model, args, timers, False)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 424, in evaluate_and_print_results
    args, timers, verbose)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 400, in evaluate
    args, timers)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 216, in forward_step
    padding_mask = get_batch(data_iterator, timers)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 193, in get_batch
    data = next(data_iterator)
  File "/home/z00487393/Applications/Anaconda/anaconda3/envs/ML_for_Pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 572, in __next__
    raise StopIteration
StopIteration
```

Unfortunately, I cannot find the reason why the iteration is terminated.

**Comment by raulpuric** [comment]
that stack trace isn't very helpful. Maybe try and disable the multithreaded dataloaders by setting `--num-workers` to 0. Hopefully that will give us a better idea

**Comment by CatFootPrint** [comment]
Thanks a lot!
I set --num-workers=0, but encountered the same problem. Would you please help me find the reason why the program is terminated after 1000 iterations, no matter --train-iters=10000 or -train-iters=2000.

```
runfile('/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py', args='--num-layers=24 --hidden-size=1024 --num-attention-heads=16 --batch-size=1 --seq-length=512 --max-preds-per-seq=80 --max-position-embeddings=512 --train-iters=20000 --save=checkpoints/bert_345m --load=checkpoints/bert_345m --train-data=wikipedia --tokenizer-type=BertWordPieceTokenizer --tokenizer-model-type=bert-large-uncased --cache-dir=cache --split=949,50,1 --distributed-backend=nccl --lr=0.0001 --lr-decay-style=linear --lr-decay-iters=990000 --weight-decay=1e-2 --clip-grad=1.0 --warmup=.01 --num-workers=0', wdir='/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master')
using world size: 1 and model-parallel size: 1 
 > using dynamic loss scaling
> initializing model parallel with size 1
Pretrain BERT model
arguments:
  pretrained_bert .............. False
  attention_dropout ............ 0.1
  num_attention_heads .......... 16
  hidden_size .................. 1024
  intermediate_size ............ None
  num_layers ................... 24
  layernorm_epsilon ............ 1e-05
  hidden_dropout ............... 0.1
  max_position_embeddings ...... 512
  vocab_size ................... 30522
  deep_init .................... False
  make_vocab_size_divisible_by . 128
  fp16 ......................... False
  fp32_embedding ............... False
  fp32_layernorm ............... False
  fp32_tokentypes .............. False
  fp32_allreduce ............... False
  hysteresis ................... 2
  loss_scale ................... None
  loss_scale_window ............ 1000
  min_scale .................... 1
  batch_size ................... 1
  weight_decay ................. 0.01
  checkpoint_activations ....... False
  checkpoint_num_layers ........ 1
  clip_grad .................... 1.0
  train_iters .................. 20000
  log_interval ................. 100
  exit_interval ................ None
  seed ......................... 1234
  reset_position_ids ........... False
  reset_attention_mask ......... False
  lr_decay_iters ............... 990000
  lr_decay_style ............... linear
  lr ........................... 0.0001
  warmup ....................... 0.01
  save ......................... checkpoints/bert_345m
  save_interval ................ 5000
  no_save_optim ................ False
  no_save_rng .................. False
  load ......................... checkpoints/bert_345m
  no_load_optim ................ False
  no_load_rng .................. False
  finetune ..................... False
  resume_dataloader ............ False
  distributed_backend .......... nccl
  local_rank ................... None
  eval_batch_size .............. None
  eval_iters ................... 100
  eval_interval ................ 1000
  eval_seq_length .............. None
  eval_max_preds_per_seq ....... None
  overlapping_eval ............. 32
  cloze_eval ................... False
  eval_hf ...................... False
  load_openai .................. False
  temperature .................. 1.0
  top_p ........................ 0.0
  top_k ........................ 0
  out_seq_length ............... 256
  model_parallel_size .......... 1
  shuffle ...................... False
  train_data ................... ['wikipedia']
  use_npy_data_loader .......... False
  train_data_path .............. 
  val_data_path ................ 
  test_data_path ............... 
  input_data_sizes_file ........ sizes.txt
  delim ........................ ,
  text_key ..................... sentence
  eval_text_key ................ None
  valid_data ................... None
  split ........................ 949,50,1
  test_data .................... None
  lazy_loader .................. False
  loose_json ................... False
  presplit_sentences ........... False
  num_workers .................. 0
  tokenizer_model_type ......... bert-large-uncased
  tokenizer_path ............... tokenizer.model
  tokenizer_type ............... BertWordPieceTokenizer
  cache_dir .................... cache
  use_tfrecords ................ False
  seq_length ................... 512
  max_preds_per_seq ............ 80
  cuda ......................... True
  rank ......................... 0
  world_size ................... 1
  dynamic_loss_scale ........... True
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
configuring data
loading BertWordPieceTokenizer ( bert-large-uncased ) from cache_dir  cache
loaded bert-large-uncased
[nltk_data] Error loading punkt: <urlopen error [Errno 110] Connection
[nltk_data]     timed out>
==================================================
[10439 71383 30850 43517 72275 48371 45416  3195  6762  1959 41995 55461
  6631 36412 76058 17788 50721 87317 20968 61507  6800 12890 29741 33757
   987  6022 47041 16967 22031  1830   102   794    77 39569  4554]
==================================================
[nltk_data] Error loading punkt: <urlopen error [Errno 110] Connection
[nltk_data]     timed out>
==================================================
[2058]
==================================================
[nltk_data] Error loading punkt: <urlopen error [Errno 110] Connection
[nltk_data]     timed out>
==================================================
[8584]
==================================================
> padded vocab (size: 30522) with 70 dummy tokens (new size: 30592)
building BERT model ...
 > number of parameters on model parallel rank 0: 336297858
learning rate decaying linear
WARNING: could not find the metadata file checkpoints/bert_345m/latest_checkpointed_iteration.txt 
    will not load any checkpoints and will start from random
 iteration      100/   20000 | elapsed time per iteration (ms): 334.9 | learning rate 1.010E-06 | lm loss 1.020020E+01 | nsp loss 5.515259E-01 |
after 100 iterations memory (MB) | allocated: 5133.326171875 | max allocated: 7899.060546875 | cached: 9324.0 | max cached: 9324.0
time (ms) | forward: 132.49 | backward: 182.57 | optimizer: 18.18 | batch generator: 45.29 | data loader: 43.98
 iteration      200/   20000 | elapsed time per iteration (ms): 313.1 | learning rate 2.020E-06 | lm loss 9.444483E+00 | nsp loss 2.486780E-01 |
time (ms) | forward: 126.98 | backward: 166.20 | optimizer: 18.19 | batch generator: 46.38 | data loader: 45.34
 iteration      300/   20000 | elapsed time per iteration (ms): 310.5 | learning rate 3.030E-06 | lm loss 8.964805E+00 | nsp loss 2.441981E-01 |
time (ms) | forward: 124.48 | backward: 166.07 | optimizer: 18.20 | batch generator: 43.98 | data loader: 42.95
 iteration      400/   20000 | elapsed time per iteration (ms): 319.9 | learning rate 4.040E-06 | lm loss 8.615480E+00 | nsp loss 1.926981E-01 |
time (ms) | forward: 127.28 | backward: 172.71 | optimizer: 18.18 | batch generator: 45.43 | data loader: 44.29
 iteration      500/   20000 | elapsed time per iteration (ms): 313.0 | learning rate 5.051E-06 | lm loss 8.258979E+00 | nsp loss 3.433331E-02 |
time (ms) | forward: 126.62 | backward: 166.39 | optimizer: 18.19 | batch generator: 46.21 | data loader: 45.18
 iteration      600/   20000 | elapsed time per iteration (ms): 313.5 | learning rate 6.061E-06 | lm loss 8.009584E+00 | nsp loss 7.460073E-02 |
time (ms) | forward: 127.12 | backward: 166.40 | optimizer: 18.20 | batch generator: 46.71 | data loader: 45.69
 iteration      700/   20000 | elapsed time per iteration (ms): 313.0 | learning rate 7.071E-06 | lm loss 7.688071E+00 | nsp loss 1.607947E-02 |
time (ms) | forward: 126.81 | backward: 166.21 | optimizer: 18.19 | batch generator: 46.40 | data loader: 45.37
 iteration      800/   20000 | elapsed time per iteration (ms): 323.6 | learning rate 8.081E-06 | lm loss 7.504505E+00 | nsp loss 1.320782E-03 |
time (ms) | forward: 127.72 | backward: 176.17 | optimizer: 18.17 | batch generator: 46.04 | data loader: 44.88
 iteration      900/   20000 | elapsed time per iteration (ms): 311.6 | learning rate 9.091E-06 | lm loss 7.395828E+00 | nsp loss 8.472300E-04 |
time (ms) | forward: 125.32 | backward: 166.38 | optimizer: 18.20 | batch generator: 44.85 | data loader: 43.83
 iteration     1000/   20000 | elapsed time per iteration (ms): 318.6 | learning rate 1.010E-05 | lm loss 7.482427E+00 | nsp loss 4.071171E-01 |
time (ms) | forward: 124.55 | backward: 174.33 | optimizer: 18.17 | batch generator: 42.16 | data loader: 40.99
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/z00487393/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/z00487393/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 581, in <module>
    main()
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 559, in main
    timers, args)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 365, in train
    prefix, val_data_iterator, model, args, timers, False)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 419, in evaluate_and_print_results
    args, timers, verbose)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 395, in evaluate
    args, timers)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 211, in forward_step
    padding_mask = get_batch(data_iterator, timers)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 188, in get_batch
    data = next(data_iterator)
  File "/home/z00487393/Applications/Anaconda/anaconda3/envs/ML_for_Pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 559, in __next__
    indices = next(self.sample_iter)  # may raise StopIteration
StopIteration
```

I appreciate your suggestion and thanks a lot!

**Comment by CatFootPrint** [comment]
> that stack trace isn't very helpful. Maybe try and disable the multithreaded dataloaders by setting `--num-workers` to 0. Hopefully that will give us a better idea

Unfortunately, setting --num_workers==0 does not work. Would you please help me find the reason why iterations are terminated for 1000 iterations. Maybe the functions for loading data causes this problem, I think.
Thank you very much for your guidance. Best wishes for you!

**Comment by CatFootPrint** [comment]
Dear Raul:
Thanks a lot for your guidance!
However, I set --num-workers=0, but encountered the same problem. Would you please help me find the reason why the program is terminated after 1000 iterations, no matter --train-iters=10000 or -train-iters=2000.
runfile('/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py', args='--num-layers=24 --hidden-size=1024 --num-attention-heads=16 --batch-size=1 --seq-length=512 --max-preds-per-seq=80 --max-position-embeddings=512 --train-iters=20000 --save=checkpoints/bert_345m --load=checkpoints/bert_345m --train-data=wikipedia --tokenizer-type=BertWordPieceTokenizer --tokenizer-model-type=bert-large-uncased --cache-dir=cache --split=949,50,1 --distributed-backend=nccl --lr=0.0001 --lr-decay-style=linear --lr-decay-iters=990000 --weight-decay=1e-2 --clip-grad=1.0 --warmup=.01 --num-workers=0', wdir='/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master')
using world size: 1 and model-parallel size: 1 
 > using dynamic loss scaling
> initializing model parallel with size 1
Pretrain BERT model
arguments:
  pretrained_bert .............. False
  attention_dropout ............ 0.1
  num_attention_heads .......... 16
  hidden_size .................. 1024
  intermediate_size ............ None
  num_layers ................... 24
  layernorm_epsilon ............ 1e-05
  hidden_dropout ............... 0.1
  max_position_embeddings ...... 512
  vocab_size ................... 30522
  deep_init .................... False
  make_vocab_size_divisible_by . 128
  fp16 ......................... False
  fp32_embedding ............... False
  fp32_layernorm ............... False
  fp32_tokentypes .............. False
  fp32_allreduce ............... False
  hysteresis ................... 2
  loss_scale ................... None
  loss_scale_window ............ 1000
  min_scale .................... 1
  batch_size ................... 1
  weight_decay ................. 0.01
  checkpoint_activations ....... False
  checkpoint_num_layers ........ 1
  clip_grad .................... 1.0
  train_iters .................. 20000
  log_interval ................. 100
  exit_interval ................ None
  seed ......................... 1234
  reset_position_ids ........... False
  reset_attention_mask ......... False
  lr_decay_iters ............... 990000
  lr_decay_style ............... linear
  lr ........................... 0.0001
  warmup ....................... 0.01
  save ......................... checkpoints/bert_345m
  save_interval ................ 5000
  no_save_optim ................ False
  no_save_rng .................. False
  load ......................... checkpoints/bert_345m
  no_load_optim ................ False
  no_load_rng .................. False
  finetune ..................... False
  resume_dataloader ............ False
  distributed_backend .......... nccl
  local_rank ................... None
  eval_batch_size .............. None
  eval_iters ................... 100
  eval_interval ................ 1000
  eval_seq_length .............. None
  eval_max_preds_per_seq ....... None
  overlapping_eval ............. 32
  cloze_eval ................... False
  eval_hf ...................... False
  load_openai .................. False
  temperature .................. 1.0
  top_p ........................ 0.0
  top_k ........................ 0
  out_seq_length ............... 256
  model_parallel_size .......... 1
  shuffle ...................... False
  train_data ................... ['wikipedia']
  use_npy_data_loader .......... False
  train_data_path .............. 
  val_data_path ................ 
  test_data_path ............... 
  input_data_sizes_file ........ sizes.txt
  delim ........................ ,
  text_key ..................... sentence
  eval_text_key ................ None
  valid_data ................... None
  split ........................ 949,50,1
  test_data .................... None
  lazy_loader .................. False
  loose_json ................... False
  presplit_sentences ........... False
  num_workers .................. 0
  tokenizer_model_type ......... bert-large-uncased
  tokenizer_path ............... tokenizer.model
  tokenizer_type ............... BertWordPieceTokenizer
  cache_dir .................... cache
  use_tfrecords ................ False
  seq_length ................... 512
  max_preds_per_seq ............ 80
  cuda ......................... True
  rank ......................... 0
  world_size ................... 1
  dynamic_loss_scale ........... True
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
configuring data
loading BertWordPieceTokenizer ( bert-large-uncased ) from cache_dir  cache
loaded bert-large-uncased
[nltk_data] Error loading punkt: <urlopen error [Errno 110] Connection
[nltk_data]     timed out>
==================================================
[10439 71383 30850 43517 72275 48371 45416  3195  6762  1959 41995 55461
  6631 36412 76058 17788 50721 87317 20968 61507  6800 12890 29741 33757
   987  6022 47041 16967 22031  1830   102   794    77 39569  4554]
==================================================
[nltk_data] Error loading punkt: <urlopen error [Errno 110] Connection
[nltk_data]     timed out>
==================================================
[2058]
==================================================
[nltk_data] Error loading punkt: <urlopen error [Errno 110] Connection
[nltk_data]     timed out>
==================================================
[8584]
==================================================
> padded vocab (size: 30522) with 70 dummy tokens (new size: 30592)
building BERT model ...
 > number of parameters on model parallel rank 0: 336297858
learning rate decaying linear
WARNING: could not find the metadata file checkpoints/bert_345m/latest_checkpointed_iteration.txt 
    will not load any checkpoints and will start from random
 iteration      100/   20000 | elapsed time per iteration (ms): 334.9 | learning rate 1.010E-06 | lm loss 1.020020E+01 | nsp loss 5.515259E-01 |
after 100 iterations memory (MB) | allocated: 5133.326171875 | max allocated: 7899.060546875 | cached: 9324.0 | max cached: 9324.0
time (ms) | forward: 132.49 | backward: 182.57 | optimizer: 18.18 | batch generator: 45.29 | data loader: 43.98
 iteration      200/   20000 | elapsed time per iteration (ms): 313.1 | learning rate 2.020E-06 | lm loss 9.444483E+00 | nsp loss 2.486780E-01 |
time (ms) | forward: 126.98 | backward: 166.20 | optimizer: 18.19 | batch generator: 46.38 | data loader: 45.34
 iteration      300/   20000 | elapsed time per iteration (ms): 310.5 | learning rate 3.030E-06 | lm loss 8.964805E+00 | nsp loss 2.441981E-01 |
time (ms) | forward: 124.48 | backward: 166.07 | optimizer: 18.20 | batch generator: 43.98 | data loader: 42.95
 iteration      400/   20000 | elapsed time per iteration (ms): 319.9 | learning rate 4.040E-06 | lm loss 8.615480E+00 | nsp loss 1.926981E-01 |
time (ms) | forward: 127.28 | backward: 172.71 | optimizer: 18.18 | batch generator: 45.43 | data loader: 44.29
 iteration      500/   20000 | elapsed time per iteration (ms): 313.0 | learning rate 5.051E-06 | lm loss 8.258979E+00 | nsp loss 3.433331E-02 |
time (ms) | forward: 126.62 | backward: 166.39 | optimizer: 18.19 | batch generator: 46.21 | data loader: 45.18
 iteration      600/   20000 | elapsed time per iteration (ms): 313.5 | learning rate 6.061E-06 | lm loss 8.009584E+00 | nsp loss 7.460073E-02 |
time (ms) | forward: 127.12 | backward: 166.40 | optimizer: 18.20 | batch generator: 46.71 | data loader: 45.69
 iteration      700/   20000 | elapsed time per iteration (ms): 313.0 | learning rate 7.071E-06 | lm loss 7.688071E+00 | nsp loss 1.607947E-02 |
time (ms) | forward: 126.81 | backward: 166.21 | optimizer: 18.19 | batch generator: 46.40 | data loader: 45.37
 iteration      800/   20000 | elapsed time per iteration (ms): 323.6 | learning rate 8.081E-06 | lm loss 7.504505E+00 | nsp loss 1.320782E-03 |
time (ms) | forward: 127.72 | backward: 176.17 | optimizer: 18.17 | batch generator: 46.04 | data loader: 44.88
 iteration      900/   20000 | elapsed time per iteration (ms): 311.6 | learning rate 9.091E-06 | lm loss 7.395828E+00 | nsp loss 8.472300E-04 |
time (ms) | forward: 125.32 | backward: 166.38 | optimizer: 18.20 | batch generator: 44.85 | data loader: 43.83
 iteration     1000/   20000 | elapsed time per iteration (ms): 318.6 | learning rate 1.010E-05 | lm loss 7.482427E+00 | nsp loss 4.071171E-01 |
time (ms) | forward: 124.55 | backward: 174.33 | optimizer: 18.17 | batch generator: 42.16 | data loader: 40.99
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/z00487393/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/z00487393/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 581, in <module>
    main()
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 559, in main
    timers, args)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 365, in train
    prefix, val_data_iterator, model, args, timers, False)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 419, in evaluate_and_print_results
    args, timers, verbose)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 395, in evaluate
    args, timers)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 211, in forward_step
    padding_mask = get_batch(data_iterator, timers)
  File "/home/z00487393/Documents/Scripts/TensorFlow/Megatron/Megatron-LM-master/pretrain_bert.py", line 188, in get_batch
    data = next(data_iterator)
  File "/home/z00487393/Applications/Anaconda/anaconda3/envs/ML_for_Pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 559, in __next__
    indices = next(self.sample_iter)  # may raise StopIteration
StopIteration
Would you please help me find the reason why iterations are terminated for 1000 iterations. Maybe the functions for loading data causes this problem, I think.
Best wishes for you!
I appreciate it very much for your kindly guidance.



--

At 2019-09-06 04:18:25, "Raul Puri" <notifications@github.com> wrote:


that stack trace isn't very helpful. Maybe try and disable the multithreaded dataloaders by setting --num-workers to 0. Hopefully that will give us a better idea

**Comment by CatFootPrint** [comment]
> that stack trace isn't very helpful. Maybe try and disable the multithreaded dataloaders by setting `--num-workers` to 0. Hopefully that will give us a better idea

Fortunately, when I choose a larger training set, the the number of iteration of pretrain_bert.sh is much larger than 1000. However, I find that when the program finishes loading training data, it will stop iteration, which is shown as follow. I am not sure whether the program executes correctly or not.
Best wishes for you. Thanks a lot for your kindly guidance.

```
  successfully saved checkpoints/bert_345m/iter_0050000/mp_rank_00/model_optim_rng.pt
Traceback (most recent call last):
  File "pretrain_bert.py", line 584, in <module>
    main()
  File "pretrain_bert.py", line 562, in main
    timers, args)
  File "pretrain_bert.py", line 365, in train
    prefix, val_data_iterator, model, args, timers, False)
  File "pretrain_bert.py", line 419, in evaluate_and_print_results
    args, timers, verbose)
  File "pretrain_bert.py", line 395, in evaluate
    args, timers)
  File "pretrain_bert.py", line 212, in forward_step
    padding_mask = get_batch(data_iterator, timers)
  File "pretrain_bert.py", line 189, in get_batch
    data = next(data_iterator)
  File "/data2/z00487393/Applications/Anaconda/envs/ML_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 794, in __next__
    raise StopIteration
StopIteration
```

**Comment by raulpuric** [comment]
Are you training with the full dataset? Based on your results it appears to me that you just don't have enough data? We typically do not run into this problem even with 1 million iterations @ batch 256. 

Can you share the size of your wikipedia dataset in terms of raw GB and number of lines `wc -l <file>`

**Comment by CatFootPrint** [comment]
Sorry for late. 
You are right.
I adopted the whole Wikipedia data set and the programs works without warning.
Thank you very much!
Best Wishes for you.

**Comment by jon-barker** [comment]
This appears to be solved, re-open if not.
