### ISSUE TITLE
[QUESTION]What is the reason why bfloat16 requires gradient accumulation and allreductions need to be completed in fp32

### ISSUE THREAD

**Issue by huhu0823** [NVIDIA/Megatron-LM#502]
Hi,I am currently studying the Megatron framework. I noticed that bfloat16 in megatron requires gradient accumulation, and allreductions need to be completed in fp32. Then the gradient communicates in fp32 format.
However, fp16 requires gradient accumulation, and allreductions can be completed in fp16.Then the gradient communicates in fp16 format.
I want to know what are the special reasons for these two different calculation methods

Line 159-160 of the megatron/arguments. py file

![lQLPJxda3cZZmQjNApzNBeiwwTfxEK6Mif0E95eXr1raAA_1512_668](https://github.com/NVIDIA/Megatron-LM/assets/57345759/12e7e4ea-6d15-49f7-ae21-d234c31fc6c5)

**Comment by Boreaso** [comment]
Same question, anyone knows the reason?
