### ISSUE TITLE
[QUESTION]  both are right?

### ISSUE THREAD

**Issue by DavideHe** [NVIDIA/Megatron-LM#513]
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/transformer.py#L1441
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/transformer/transformer_layer.py#L94

two  way  calculate offset ,but they are different .    both are right?

**Comment by deepakn94** [comment]
Yup, both should be computing the same set of offsets:

```
With 8 layers, 2 stages, and 4 model chunks, we want an assignment of layers to stages like (each list is a model chunk):
Stage 0: [0]  [2]  [4]  [6]
Stage 1: [1]  [3]  [5]  [7]


With 8 layers, 2 stages, and 2 virtual stages, we want an assignment of layers to stages like (each list is a model chunk):
Stage 0: [0, 1]  [4, 5]
Stage 1: [2, 3]  [6, 7]```

**Comment by deepakn94** [comment]
Going to close this, feel free to re-open if you still have questions.
