### ISSUE TITLE
[BUG] no_sync_func in forward_backward_pipelining_without_interleaving of file schedules.py

### ISSUE THREAD

**Issue by gouchangjiang** [NVIDIA/Megatron-LM#519]
**Describe the bug**
[line 1062](https://github.com/NVIDIA/Megatron-LM/blob/52f13005148afa47a6f37b082083fa2c6675ae3e/megatron/core/pipeline_parallel/schedules.py#L1062C12-L1062C12) of file schedules.py, duplicates the logic of setting no_sync_func. It will override logic between lines 1060 and 1061. No matter what the typing of the model is, no_sync_func will be selected as contextlib.nullcontext if it is not set in the arguments.

**Proposed fix**
maybe write it like 
if no_sync_func is None:
   if isinstance(model, torchDDP):
        no_sync_func = model.no_sync
   else:
        no_sync_func = contextlib.nullcontext

**Comment by wdykas** [comment]
I think this may be fine how it is because if the first condition is met it sets `no_sync_func = model.no_sync` so it won't be set to `contextlib.nullcontext` unless `model.no_sync` returns None
```
if no_sync_func is None and isinstance(model, torchDDP):
        no_sync_func = model.no_sync
if no_sync_func is None:
       no_sync_func = contextlib.nullcontext
```

**Comment by deepakn94** [comment]
Yup, @wdykas is correct.

**Comment by gouchangjiang** [comment]
thanks @wdykas  my bad.
