### ISSUE TITLE
[BUG] FLOPs computation in "Reducing Activation Recomputation in Large Transformer Models"

### ISSUE THREAD

**Issue by Muennighoff** [NVIDIA/Megatron-LM#523]
In your paper (https://arxiv.org/pdf/2205.05198.pdf) you write that:
`Selective activation recomputation requires an additional forward pass attention matrix computation (2Bs2h operations) and attention over values (2Bs2h operations). Adding these required FLOPs to Equation 7, the total number of FLOPs we require per iteration (denoted by hardware FLOPs) is..`

However the first formula you give is
`72BLs(h**2) * (1 + s/6h + v/12hL) = 72BLs(h**2) + 12BL(s**2)h + 6BLshv`
while the second formula is:
`72BLs(h**2) * (1 + s/3h + v/12hL) = 72BLs(h**2) + 24BL(s**2)h + 6BLshv`

The difference is `12BL(s**2)h` not `4BL(s**2)h` as I would have expected given your explanation. Could you clarify why that is the case? Since ths is forward only, the additional 2x cannot come from a backward pass I guess. Thanks!

Sorry if this is the wrong place but you don't provide any email in your paper.

@kvareddy @jaredcasper @bryancatanzaro

**Comment by jaredcasper** [comment]
Yes, this equation is incorrect, there are 16 BL(s**2)h FLOPs, not 24, so the second term should be 2/9 not 1/3.
