### ISSUE TITLE
[QUESTION] which script to use to launch llama 2 fine tuning?

### ISSUE THREAD

**Issue by ppt0011** [NVIDIA/Megatron-LM#528]
which script should we pass the paramaters defined here to in order to launch the model?
https://github.com/NVIDIA/Megatron-LM/blob/main/docs/llama2.md#launch-megatron

**Comment by taowangcheng** [comment]
@ppt0011 I have the same question. Do you have any ideas?

**Comment by Dongximing** [comment]
same question please !!!!!!
