### ISSUE TITLE
[ENHANCEMENT]Does BPipe implement in Megatron-LM framework?

### ISSUE THREAD

**Issue by robotsp** [NVIDIA/Megatron-LM#539]
**Is your feature request related to a problem? Please describe.**
I read a paper named: **bpipe: memory-balanced pipeline parallelism for training large language models**. The author said they have implemented in Megatron which I cannot find.

**Describe the solution you'd like**
My question is, Does BPipe implement in Megatron-LM framework?

@sublee @jaredcasper @bryancatanzaro @aaronp24 @dweekly 
```[tasklist]
### Tasks
```

**Comment by deepakn94** [comment]
No, this is not implemented in this repository. The authors probably meant they implemented their techniques in a fork of Megatron.
