### ISSUE TITLE
[ENHANCEMENT] relax assert gbuf_size % data_parallel_world_size == 0 when using use-distributed-optimizer

### ISSUE THREAD

**Issue by SeaOfOcean** [NVIDIA/Megatron-LM#545]
**Is your feature request related to a problem? Please describe.**
relax assert gbuf_size % data_parallel_world_size == 0 when using use-distributed-optimizer. In some setting, when I enable use-distributed-optimizer, the assertion failed 
```
AssertionError: Each bucket's buffer size should be divisible by 2
```

**Describe the solution you'd like**
relax the assert

**Comment by SeaOfOcean** [comment]
@deepakn94 Can you help check it? Why do we need this assert?

**Comment by SeaOfOcean** [comment]
I found that this PR  https://github.com/NVIDIA/Megatron-LM/commit/efb2e25595bcced494da3566b248dfeed55f27f6 introduced the change

**Comment by deepakn94** [comment]
Can you share the command-line arguments you used to produce this assertion error?

The assertion itself is important since with the distributed optimizer, we want to give every DP rank "ownership" on an equal-sized shard of the parameters.

**Comment by deepakn94** [comment]
Per-bucket padding code pushed here: https://github.com/NVIDIA/Megatron-LM/commit/443ce9f3f98fdc5a53c6b480c6e21b79944d198e. Please let me know if you run into any issues.
