### ISSUE TITLE
[QUESTION] Options to blend multiple datasets evenly.

### ISSUE THREAD

**Issue by torshie** [NVIDIA/Megatron-LM#547]
I have two datasets `A` and `B`, assume `A` has 10 samples, `B` has 20 samples. I want to megatron to sample from the two datasets evenly across all 30 samples (no up sampling or down sampling).

Should the option to blend the datasets be `--data-path 1 A 1 B` or `--data-path 10 A 20 B` ?

**Comment by wowfingerlicker** [comment]
same question

**Comment by janEbert** [comment]
The blend will be calculated depending on the number of _training samples_, completely independent of the number of samples in the datasets. So indeed it would be the second option, where you sample from `B` with an increased probability.
