### ISSUE TITLE
Support of LoRA/QLoRA?

### ISSUE THREAD

**Issue by lingjiew93** [NVIDIA/Megatron-LM#554]
Hi,

I saw megatron already included llama2 inference and finetune but I didn't find LoRA.
Do you have plan to support LoRA/QLoRA for llama2 in future?

Thanks,

**Comment by deepakn94** [comment]
We have support for LoRA and other adapters in NeMo: https://docs.nvidia.com/nemo-framework/user-guide/latest/playbooks/llama2peft.html.

**Comment by lingjiew93** [comment]
> We have support for LoRA and other adapters in NeMo: https://docs.nvidia.com/nemo-framework/user-guide/latest/playbooks/llama2peft.html.

Will check that. Thanks.
