### ISSUE TITLE
[QUESTION] run_text_generation_server arguments

### ISSUE THREAD

**Issue by V3RGANz** [NVIDIA/Megatron-LM#555]
Text generation server scripts like this https://github.com/NVIDIA/Megatron-LM/blob/main/examples/run_text_generation_server_345M.sh contain following arguments:
```
       --out-seq-length 1024  \
       --temperature 1.0  \
       --top_p 0.9  \
```
But script run failed because it does not recognise them. I also could not find them anywhere in source code. I have only seen that text generation configuration can be passed directly in request json (https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/text_generation_server.py#L86). 

Are these args wrong or I am missing something?

**Comment by wdykas** [comment]
hi thanks for pointing this out, these were recently removed because they were not actually doing anything and the sampling args are controlled in the payload. I will update the examples.
