### ISSUE TITLE
[QUESTION] Whether to consider optimizing TP scheduling?

### ISSUE THREAD

**Issue by bisunny** [NVIDIA/Megatron-LM#556]
The performance when using tensor parallel is restricted by communication. Have you considered adding some enhancement strategies to Megatron, such as paper [Overlap Communication with Dependent Computation via Decomposition in Large Deep Learning Models]

**Comment by rejoicesyc** [comment]
TransformerEngine has implemented the UserBuffer for overlapping and can be used for Megaton. However, I suppose it will work fine to just overlap with matmul in Linear class.

**Comment by bisunny** [comment]
Thank you for your reply, I will study it.
