### ISSUE TITLE
[QUESTION] Is it possible to enable sequence parallel in inference time

### ISSUE THREAD

**Issue by cckao** [NVIDIA/Megatron-LM#557]
**Your question**
To be specific, text generation of Llama 2. I've seen examples show how to use sequence parallelism in training, but I don't see any for inference. Can anyone tell me how to do it? Thank you.

**Comment by deepakn94** [comment]
It should be the same way: using the `--sequence-parallel` command-line argument.

**Comment by deepakn94** [comment]
It should be the same way: using the `--sequence-parallel` command-line argument.
