### ISSUE TITLE
[QUESTION] All-Reduce placement in backwards for Tensor Parallel MLP blocks

### ISSUE THREAD

**Issue by joshlk** [NVIDIA/Megatron-LM#559]
In the [2019 paper](https://arxiv.org/pdf/1909.08053.pdf), Megatron introduces how to apply tensor parallel to MLP transformer blocks. This diagram is taken from the paper:

![Screenshot 2023-10-24 at 14 27 01](https://github.com/NVIDIA/Megatron-LM/assets/5648645/54019e8c-d6b8-4397-bd6c-b440d40f3937)

Here the function `f` is an identity for forward computation and an all-reduce in the backward computation. `g` is an all-reduce in the forward computation and an identity in the backward computation.

However, usually the gradient of an all-reduce is also an all-reduce ([see pytorch](https://github.com/pytorch/pytorch/blob/ac44569b0d87ef7c2c8c26f3057f797f40cc6111/torch/distributed/nn/functional.py#L252-L263)) - why is that not the case above? I have verified that the above multi-device MLP block is numerically equivalent to that of a single-device MLP block, and I understand the intuition; however, I am struggling to show this is equivalent using matrix calculus mathematically. Can you please help? 🙂

**Comment by deepakn94** [comment]
Thanks for the question!

For simplicity, I am going to consider 2 scalars, but the math should translate to $n$ vectors as well.

Let $y = x_1 + x_2$ (all-reducing two scalars $x_1$ and $x_2$). In the backward pass, we have the derivative of the loss with respect to $y$ ($dL/dy$) and want to compute the derivatives of the loss with respect to $x_1$ and $x_2$ ($dL/dx_1$ and $dL/dx_2$). Using the chain rule, $dL/dx_1 = dL/dy \cdot dy/dx_1 = dL/dy \cdot 1 = dL/dy$. Similarly, $dL/dx_2 = dL/dy$ as well.

Hope this helps!

**Comment by deepakn94** [comment]
Fwiw, I think the PyTorch code is doing something a little different. If $y = x_1 + x_2$ as before, then the PyTorch code is saying $dy/dw = dx_1/dw + dx_2/dw$ where $w$ is some other variable.

**Comment by joshlk** [comment]
Hi, thanks for the help 🙂 

If I understand correctly, I think the maths above models this computation graph:

<img src="https://github.com/NVIDIA/Megatron-LM/assets/5648645/dd0632fa-f106-4402-afc9-c4fef592079a" width="300">

However, we are using multiple devices and the all-reduce replicates $y$ like so:

<img src="https://github.com/NVIDIA/Megatron-LM/assets/5648645/147d3243-0960-484d-9787-d534c57b93c1" width="300">

If we consider the above, to calculate the backwards pass, we first need the gradient of $\hat{y}$ with respect to $\hat{x}$:

$$
\begin{aligned}
\frac{\mathrm{d} \hat{y} }{\mathrm{d} \hat{x}} &= \begin{pmatrix}
\mathrm{d} y_1 / \mathrm{d} x_1 & \mathrm{d} y_1 / \mathrm{d} x_2 \\ 
\mathrm{d} y_2 / \mathrm{d} x_1 & \mathrm{d} y_2 / \mathrm{d} x_2
\end{pmatrix} \\
&= \begin{pmatrix}
1 & 1 \\ 
1 & 1
\end{pmatrix}
\end{aligned}
$$

Then to obtain $\mathrm{d} L / \mathrm{d} \hat{x}$ given $\mathrm{d} L / \mathrm{d} \hat{y}$:

$$
\begin{aligned}
\frac{\mathrm{d} L }{\mathrm{d} \hat{x}} &= \frac{\mathrm{d} L }{\mathrm{d} \hat{y}}\frac{\mathrm{d} \hat{y} }{\mathrm{d} \hat{x}} \\
&= \begin{pmatrix}
\mathrm{d} L / \mathrm{d} y_1 & \mathrm{d} L / \mathrm{d} y_2 
\end{pmatrix}
\begin{pmatrix}
1 & 1 \\ 
1 & 1
\end{pmatrix} \\
&=\begin{pmatrix}
\mathrm{d} L / \mathrm{d} y_1 + \mathrm{d} L / \mathrm{d} y_2 & \mathrm{d} L / \mathrm{d} y_1 + \mathrm{d} L / \mathrm{d} y_2 
\end{pmatrix}
\end{aligned}
$$

So $\mathrm{d} L / \mathrm{d} x_1$ and $\mathrm{d} L / \mathrm{d} x_2$ are the sum of the two $y$ grad contributions, which is an all-reduce. I believe this is how [PyTorch](https://github.com/pytorch/pytorch/blob/ac44569b0d87ef7c2c8c26f3057f797f40cc6111/torch/distributed/nn/functional.py#L252-L263) also derived the backwards to an all-reduce is an all-reduce.

I am doing something wrong here, do you know what? In general, is an all-reduce not the backwards to an all-reduce?

**Comment by joshlk** [comment]
Hi @deepakn94, I think I now know where the discrepancy comes from. You need to consider the loss as vector of different functions on each device: $\hat{L}$ instead of $L$, and so $\mathrm{d} \hat{L}  / \mathrm{d} \hat{x}$ and not $\mathrm{d} L  / \mathrm{d} \hat{x}$. I have written up my argument here. I would welcome your comments: https://github.com/pytorch/pytorch/issues/58005#issuecomment-1783782272
