### ISSUE TITLE
[QUESTION] Seeking documentation/paper for expert and context parallel

### ISSUE THREAD

**Issue by mayank31398** [NVIDIA/Megatron-LM#562]
same as title

**Comment by janEbert** [comment]
https://github.com/NVIDIA/NeMo/pull/9184 introduced some documentation into NeMo regarding these which are rendered here:
https://docs.nvidia.com/nemo-framework/user-guide/latest/nemotoolkit/features/parallelisms.html

**Comment by mayank31398** [comment]
thanks
