### ISSUE TITLE
[QUESTION] Is there a plan to introduce torch.compile into Megatron?

### ISSUE THREAD

**Issue by wuyujiji** [NVIDIA/Megatron-LM#563]
**Your question**
Is there a plan to introduce `torch.compile` into Megatron to speed up the training performance?

**Comment by bisunny** [comment]
@deepakn94  I have the same question

**Comment by Jack47** [comment]
+1, according to [this](https://github.com/pytorch-labs/gpt-fast), torch.compile can speed up the megatron server inference speed
