### ISSUE TITLE
[QUESTION]How to serving Llama2

### ISSUE THREAD

**Issue by xealml** [NVIDIA/Megatron-LM#581]
**Your question**
Ask a clear and concise question about Megatron-LM.
in this doc 
https://github.com/NVIDIA/Megatron-LM/blob/main/docs/llama2.md#launch-megatron
says 

If loading for either inference or finetuning, use the following arguments:

which  python file is for config infer
```[tasklist]
### Tasks
```

**Comment by Dongximing** [comment]
??? same question
