### ISSUE TITLE
[QUESTION] How to preprocess data for lustre file system?

### ISSUE THREAD

**Issue by nikit91** [NVIDIA/Megatron-LM#584]
When I train a megatron GPT model on computing cluster with lustre file system, I observe frequent file-open and file-close operations (which causes performance degradation in lustre) even though the read/write bandwidth is barely utilized for them.

![image](https://github.com/NVIDIA/Megatron-LM/assets/2648871/6b475e8b-aa85-4486-8920-def5dc9a2139)

I preprocess data using mmap, as described in the readme (https://github.com/NVIDIA/Megatron-LM#data-preprocessing).

What would be an ideal way to resolve this issue?

**Comment by nikit-srivastava** [comment]
On further analysis, we discovered that the frequent opening/closing requests were made to the temporary files. This can be solved by placing those temporary files on non-lustre directory such as `$HOME`.
