### ISSUE TITLE
How Megatron trains multiple subgraphs on multiple GPUs and where the relevant files are

### ISSUE THREAD

**Issue by jrt-20** [NVIDIA/Megatron-LM#585]
**Your question**

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by deepakn94** [comment]
What do you mean by "subgraphs" and "relevant files"?

**Comment by Hongjie1Chu** [comment]
In the context of model parallelism, each layer's input for training is derived from the output of the previous layer. How is this information passed from one layer to the next? Moreover, after an individual process completes its training during an iteration, how does it communicate with other processes within the same tensor parallelism group?

For instance, in the train() method within the training.py file, there is a loop while iteration < args.train_iters. After the current process finishes its training iteration, which specific interface does it use to communicate with other processes within the same tensor parallelism group? Additionally, which interface is used for passing the output to the subsequent layer?

**Comment by deepakn94** [comment]
The tensor-parallel communication is embedded in the relevant linear layers: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/tensor_parallel/layers.py. For example, row-parallel linear layers are implemented here: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/tensor_parallel/layers.py#L764.  In the corresponding `forward` method, you can see the relevant communication calls: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/tensor_parallel/layers.py#L933-L936.

Hope this helps, let me know if you still have questions.

**Comment by jrt-20** [comment]
> The tensor-parallel communication is embedded in the relevant linear layers: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/tensor_parallel/layers.py. For example, row-parallel linear layers are implemented here: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/tensor_parallel/layers.py#L764. In the corresponding `forward` method, you can see the relevant communication calls: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/tensor_parallel/layers.py#L933-L936.
> 
> Hope this helps, let me know if you still have questions.

Thanks, lgtm!
