### ISSUE TITLE
Inter-process and Inter-layer Communication in Model Parallelism within Megatron

### ISSUE THREAD

**Issue by Hongjie1Chu** [NVIDIA/Megatron-LM#586]
In the context of model parallelism, each layer's input for training is derived from the output of the previous layer. How is this information passed from one layer to the next? Moreover, after an individual process completes its training during an iteration, how does it communicate with other processes within the same tensor parallelism group?

For instance, in the train() method within the training.py file, there is a loop while iteration < args.train_iters. After the current process finishes its training iteration, which specific interface does it use to communicate with other processes within the same tensor parallelism group? Additionally, which interface is used for passing the output to the subsequent layer?

I'm keen to understand the underlying mechanisms for both inter-process communication and the transfer of results between layers in the Megatron framework. Any insights or pointers towards relevant sections of the codebase would be greatly appreciated.

Thank you for your assistance.

**Comment by Hongjie1Chu** [comment]
Specifically, referring to the model parallelism diagram, how do processes 3 and 4 obtain the computation results from processes 1 and 2 respectively? After 3 and 4 complete their individual computations, how do they communicate with each other? Furthermore, after this communication, which interface is used to pass the results to processes 5 and 6?
![v2-708c01105de92567824bd9d3456b9459_720w](https://github.com/NVIDIA/Megatron-LM/assets/140596238/1078cead-7fb8-4431-a009-1c5aff668bce)

**Comment by deepakn94** [comment]
(Copying partially from a comment on another issue)

The tensor-parallel communication is embedded in the relevant linear layers: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/tensor_parallel/layers.py. For example, row-parallel linear layers are implemented here: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/tensor_parallel/layers.py#L764. In the corresponding forward method, you can see the relevant communication calls: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/tensor_parallel/layers.py#L933-L936.

The pipeline-parallel communication is embedded in schedules.py: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/pipeline_parallel/schedules.py#L1042. This method has relevant communication methods like `recv_forward`, `send_forward`, etc.

Hope this helps, let me know if you still have questions.

**Comment by deepakn94** [comment]
Closing, feel free to re-open if you still have questions.
