### ISSUE TITLE
Data preprocessing Readme instructions fail

### ISSUE THREAD

**Issue by yselivonchyk** [NVIDIA/Megatron-LM#59]
I put example data into a ./data/data.json file:
```{"src": "www.nvidia.com", "text": "The quick brown fox", "type": "Eng", "id": "0", "title": "First Part"}
{"src": "The Internet", "text": "jumps over the lazy dog", "type": "Eng", "id": "42", "title": "Second Part"}
```

And run suggested command:

```
```python tools/preprocess_data.py \
       --input ./data/data.json \
       --output-prefix wtever \
       --vocab bert-vocab.txt \
       --dataset-impl mmap \
       --tokenizer-type BertWordPieceLowerCase \
       --split-sentences```
```

Which first results in:

```NameError: name 'nltk' is not defined```

After installing nltk, running the same script results in:
```
FileNotFoundError: [Errno 2] No such file or directory: 'bert-vocab.txt'
```
Is there a description of vocab.txt format and content? Can you provide an example vocab file for the example data?

**Comment by yselivonchyk** [comment]
The necessary BERT vocab file should look like: 
```[CLS]
[SEP]
[PAD]
[MASK]
[UNK]
The
quick
brown
fox
jumps
over
lazy
dog
```

**Comment by jon-barker** [comment]
The vocab files used for bert and GPT training are linked here: https://github.com/NVIDIA/Megatron-LM#downloading-checkpoints
