### ISSUE TITLE
[QUESTION]for model

### ISSUE THREAD

**Issue by Mrzhang-dada** [NVIDIA/Megatron-LM#592]
**Your question**
Ask a clear and concise question about Megatron-LM.
After carefully reading the readme, I only saw Megatron LM's user manual for Bert, GPT, etc., and did not see the extension effect that Megatron LM can have on other models. May I ask if Megatron LM supports the use of other models and how to call interfaces to adapt to them?

**Comment by deepakn94** [comment]
I am not sure I fully follow: what do you mean by "did not see the extension effect that Megatron LM can have on other models"?

**Comment by Mrzhang-dada** [comment]
> I am not sure I fully follow: what do you mean by "did not see the extension effect that Megatron LM can have on other models"?
What I mean is whether Megatron LM can be used on other large models besides BERT, GPT, T5, etc. If so, what should I do?

**Comment by deepakn94** [comment]
We only support the models that have corresponding `pretrain_*.py` scripts in the root directory.
