### ISSUE TITLE
OOM when training the same size of gpt2(2.6B) with mp=2 dp=8 with 64*V100(32GB)

### ISSUE THREAD

**Issue by Hanlard** [NVIDIA/Megatron-LM#60]
**We train gpt2(2.6B) with following parameters ，but OOM**

using world size: 16 and model-parallel size: 2 
using torch.float16 for parameters ...
-------------------- arguments --------------------
  adam_beta1 ...................... 0.9
  adam_beta2 ...................... 0.999
  adam_eps ........................ 1e-08
  adlr_autoresume ................. False
  adlr_autoresume_interval ........ 1000
  apply_query_key_layer_scaling ... False
  apply_residual_connection_post_layernorm  False
  attention_dropout ............... 0.1
  attention_softmax_in_fp32 ....... False
  batch_size ...................... 8
  bert_load ....................... None
  bias_dropout_fusion ............. False
  bias_gelu_fusion ................ False
  block_data_path ................. None
  checkpoint_activations .......... True
  checkpoint_num_layers ........... 1
  clip_grad ....................... 1.0
  data_impl ....................... mmap
  data_path ....................... /raid/gpt3-train-data/filterBy256-100G-notag_text_document
  DDP_impl ........................ local
  distribute_checkpointed_activations  True
  distributed_backend ............. nccl
  dynamic_loss_scale .............. True
  eod_mask_loss ................... False
  eval_interval ................... 10000
  eval_iters ...................... 10
  exit_interval ................... None
  faiss_use_gpu ................... False
  finetune ........................ False
  fp16 ............................ True
  fp16_lm_cross_entropy ........... True
  fp32_allreduce .................. False
  hidden_dropout .................. 0.1
  hidden_size ..................... 1920
  hysteresis ...................... 2
  ict_head_size ................... None
  ict_load ........................ None
  indexer_batch_size .............. 128
  indexer_log_interval ............ 1000
  init_method_std ................. 0.02
  layernorm_epsilon ............... 1e-05
  lazy_mpu_init ................... None
  load ............................ checkpoints/gpt2_64_xxxM
  local_rank ...................... 0
  log_interval .................... 5
  loss_scale ...................... None
  loss_scale_window ............... 1000
  lr .............................. 0.00015
  lr_decay_iters .................. 70000
  lr_decay_style .................. cosine
  make_vocab_size_divisible_by .... 128
  mask_prob ....................... 0.15
  max_position_embeddings ......... 1024
  merge_file ...................... bpe_3w_new/merges.txt
  min_lr .......................... 1e-05
  min_scale ....................... 1
  mmap_warmup ..................... False
  model_parallel_size ............. 2
  no_load_optim ................... False
  no_load_rng ..................... False
  no_save_optim ................... False
  no_save_rng ..................... False
  num_attention_heads ............. 20
  num_layers ...................... 54
  num_unique_layers ............... None
  num_workers ..................... 2
  onnx_safe ....................... None
  openai_gelu ..................... False
  override_lr_scheduler ........... False
  param_sharing_style ............. grouped
  params_dtype .................... torch.float16
  query_in_block_prob ............. 0.1
  rank ............................ 0
  report_topk_accuracies .......... []
  reset_attention_mask ............ False
  reset_position_ids .............. False
  save ............................ checkpoints/gpt2_64_xxxM
  save_interval ................... 10000
  scaled_masked_softmax_fusion .... False
  scaled_upper_triang_masked_softmax_fusion  False
  seed ............................ 1234
  seq_length ...................... 1024
  short_seq_prob .................. 0.1
  split ........................... 950,49,1
  tensorboard_dir ................. logs/gpt2_64_xxxxxxxxx
  titles_data_path ................ None
  tokenizer_type .................. GPT2BPETokenizer
  train_iters ..................... 120000
  use_checkpoint_lr_scheduler ..... False
  use_cpu_initialization .......... True
  use_one_sent_docs ............... False
  vocab_file ...................... bpe_3w_new/vocab.json
  warmup .......................... 0.01
  weight_decay .................... 0.01
  world_size ...................... 16
---------------- end of arguments ----------------
> building GPT2BPETokenizer tokenizer ...
 > padded vocab (size: 30001) with 207 dummy tokens (new size: 30208)
> setting tensorboard ...
> initializing torch distributed ...
> initializing model parallel with size 2
> setting random seeds to 1234 ...
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
> building the checkpointed activations memory buffer with 424673280 num elements and torch.float16 dtype (810.0 MB)...
building GPT2 model ...
 > number of parameters on model parallel rank 1: 1226348160
 > number of parameters on model parallel rank 0: 1226348160
> learning rate decay style: cosine
WARNING: could not find the metadata file checkpoints/gpt2_64_xxxM/latest_checkpointed_iteration.txt 
    will not load any checkpoints and will start from random
> building train, validation, and test datasets ...
 > datasets target sizes (minimum size):
    train:      7680000
    validation: 8320
    test:       640
> building train, validation, and test datasets for GPT2 ...
 > building dataset index ...
    reading sizes...
    reading pointers...
    reading document index...
    creating numpy buffer of mmap...
    creating memory view of numpy buffer...
 > finished creating indexed dataset in 0.021106 seconds
    number of documents: 48889798
 > dataset split:
    train:
     document indices in [0, 46445308) total of 46445308 documents
    validation:
     document indices in [46445308, 48840908) total of 2395600 documents
    test:
     document indices in [48840908, 48889798) total of 48890 documents

_________________________________________________________________________________

...
_________________________________________________________________________________

setting training data start iteration to 0
setting validation data start iteration to 0
done with setups ...
time (ms) | model and optimizer: 78841.91 | train/valid/test data iterators: 56110.31
training ...
 iteration        5/  120000 | elapsed time per iteration (ms): 16491.5 | learning rate: 0.000E+00 | loss scale: 268435456.0 | number of skipped iterations:   5 | number of nan iterations:   0 |
after 5 iterations memory (MB) | allocated: 10250.5693359375 | max allocated: 12606.06201171875 | reserved: 17482.0 | max reserved: 17482.0
time (ms) | forward: 11716.18 | backward: 4770.37 | backward-backward: 1742.88 | backward-allreduce: 195.31 | backward-master-grad: 2832.04 | backward-clip-grad: 0.03 | optimizer: 0.06 | batch generator: 2.61
 iteration       10/  120000 | elapsed time per iteration (ms): 1993.9 | learning rate: 0.000E+00 | loss scale: 8388608.0 | number of skipped iterations:   5 | number of nan iterations:   0 |
time (ms) | forward: 483.93 | backward: 1502.71 | backward-backward: 1395.29 | backward-allreduce: 103.87 | backward-master-grad: 3.43 | backward-clip-grad: 0.02 | optimizer: 0.04 | batch generator: 3.45
 iteration       15/  120000 | elapsed time per iteration (ms): 1978.1 | learning rate: 0.000E+00 | loss scale: 262144.0 | number of skipped iterations:   5 | number of nan iterations:   0 |
time (ms) | forward: 482.15 | backward: 1488.69 | backward-backward: 1395.11 | backward-allreduce: 88.19 | backward-master-grad: 5.28 | backward-clip-grad: 0.02 | optimizer: 0.04 | batch generator: 1.42
 iteration       20/  120000 | elapsed time per iteration (ms): 4540.0 | learning rate: 6.429E-07 | lm loss: 1.054034E+01 | loss scale: 65536.0 | number of skipped iterations:   2 | number of nan iterations:   0 |
time (ms) | forward: 1179.18 | backward: 1651.14 | backward-backward: 1399.57 | backward-allreduce: 106.88 | backward-master-grad: 107.87 | backward-clip-grad: 36.73 | optimizer: 1703.15 | batch generator: 36.27
 iteration       25/  120000 | elapsed time per iteration (ms): 2335.3 | learning rate: 1.286E-06 | lm loss: 9.976491E+00 | loss scale: 16384.0 | number of skipped iterations:   2 | number of nan iterations:   0 |
time (ms) | forward: 650.95 | backward: 1645.41 | backward-backward: 1397.91 | backward-allreduce: 140.40 | backward-master-grad: 74.19 | backward-clip-grad: 32.81 | optimizer: 34.49 | batch generator: 3.38
 iteration       30/  120000 | elapsed time per iteration (ms): 2325.9 | learning rate: 2.357E-06 | lm loss: 8.780370E+00 | loss scale: 16384.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
time (ms) | forward: 556.28 | backward: 1708.32 | backward-backward: 1404.33 | backward-allreduce: 113.45 | backward-master-grad: 137.84 | backward-clip-grad: 52.61 | optimizer: 58.05 | batch generator: 1.82
 iteration       35/  120000 | elapsed time per iteration (ms): 2340.5 | learning rate: 3.429E-06 | lm loss: 8.286386E+00 | loss scale: 16384.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
time (ms) | forward: 561.67 | backward: 1718.01 | backward-backward: 1396.69 | backward-allreduce: 166.71 | backward-master-grad: 102.91 | backward-clip-grad: 51.60 | optimizer: 58.24 | batch generator: 3.14
 iteration       40/  120000 | elapsed time per iteration (ms): 2320.2 | learning rate: 4.500E-06 | lm loss: 7.960351E+00 | loss scale: 16384.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
time (ms) | forward: 496.76 | backward: 1760.00 | backward-backward: 1401.41 | backward-allreduce: 212.65 | backward-master-grad: 87.91 | backward-clip-grad: 57.93 | optimizer: 57.71 | batch generator: 7.84
 iteration       45/  120000 | elapsed time per iteration (ms): 2222.0 | learning rate: 5.571E-06 | lm loss: 7.752969E+00 | loss scale: 16384.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
time (ms) | forward: 515.71 | backward: 1644.29 | backward-backward: 1401.37 | backward-allreduce: 93.53 | backward-master-grad: 97.84 | backward-clip-grad: 51.46 | optimizer: 57.72 | batch generator: 2.10
 iteration       50/  120000 | elapsed time per iteration (ms): 2333.7 | learning rate: 6.643E-06 | lm loss: 7.703540E+00 | loss scale: 16384.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
time (ms) | forward: 547.30 | backward: 1724.37 | backward-backward: 1399.37 | backward-allreduce: 102.34 | backward-master-grad: 171.11 | backward-clip-grad: 51.46 | optimizer: 57.51 | batch generator: 4.48
 iteration       55/  120000 | elapsed time per iteration (ms): 2218.5 | learning rate: 7.714E-06 | lm loss: 7.548244E+00 | loss scale: 16384.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
time (ms) | forward: 502.01 | backward: 1651.20 | backward-backward: 1399.92 | backward-allreduce: 109.33 | backward-master-grad: 88.23 | backward-clip-grad: 53.63 | optimizer: 59.16 | batch generator: 1.40
 iteration       60/  120000 | elapsed time per iteration (ms): 2236.7 | learning rate: 8.786E-06 | lm loss: 7.576575E+00 | loss scale: 16384.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
time (ms) | forward: 525.56 | backward: 1647.52 | backward-backward: 1398.55 | backward-allreduce: 100.72 | backward-master-grad: 96.68 | backward-clip-grad: 51.47 | optimizer: 57.61 | batch generator: 1.38
 iteration       65/  120000 | elapsed time per iteration (ms): 2212.0 | learning rate: 9.857E-06 | lm loss: 7.420119E+00 | loss scale: 16384.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
time (ms) | forward: 506.30 | backward: 1643.29 | backward-backward: 1398.46 | backward-allreduce: 96.29 | backward-master-grad: 90.85 | backward-clip-grad: 57.61 | optimizer: 57.66 | batch generator: 1.42
Traceback (most recent call last):
  File "pretrain_gpt2.py", line 115, in <module>
    args_defaults={'tokenizer_type': 'GPT2BPETokenizer'})
  File "/userhome/megatron/megatron/training.py", line 109, in pretrain
    train_data_iterator, valid_data_iterator)
  File "/userhome/megatron/megatron/training.py", line 438, in train
    lr_scheduler)
  File "/userhome/megatron/megatron/training.py", line 300, in train_step
    backward_step(optimizer, model, loss)
  File "/userhome/megatron/megatron/training.py", line 265, in backward_step
    fp32_allreduce=args.fp32_allreduce)
  File "/userhome/megatron/megatron/model/distributed.py", line 53, in allreduce_params
    coalesced = _flatten_dense_tensors(grads)
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 229, in _flatten_dense_tensors
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
RuntimeError: CUDA out of memory. Tried to allocate 2.29 GiB (GPU 0; 31.72 GiB total capacity; 19.22 GiB already allocated; 1.88 GiB free; 28.32 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'pretrain_gpt2.py', '--local_rank=15', '--model-parallel-size', '2', '--num-layers', '54', '--hidden-size', '1920', '--num-attention-heads', '20', '--batch-size', '8', '--seq-length', '1024', '--max-position-embeddings', '1024', '--train-iters', '120000', '--lr-decay-iters', '70000', '--save', 'checkpoints/gpt2_64_xxxM', '--load', 'checkpoints/gpt2_64_xxxM', '--data-path', '/raid/gpt3-train-data/filterBy256-100G-notag_text_document', '--vocab-file', 'bpe_3w_new/vocab.json', '--merge-file', 'bpe_3w_new/merges.txt', '--data-impl', 'mmap', '--split', '950,49,1', '--distributed-backend', 'nccl', '--lr', '0.00015', '--lr-decay-style', 'cosine', '--min-lr', '1.0e-5', '--weight-decay', '1e-2', '--clip-grad', '1.0', '--warmup', '.01', '--checkpoint-activations', '--log-interval', '5', '--tensorboard-dir', 'logs/gpt2_64_xxxxxxxxx', '--save-interval', '10000', '--eval-interval', '10000', '--eval-iters', '10', '--checkpoint-num-layers', '1', '--fp16', '--checkpoint-activations', '--distribute-checkpointed-activations', '--fp16-lm-cross-entropy', '--use-cpu-initialization']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************

**Comment by Hanlard** [comment]
This is 16 * V100(32G) for debug...

**Comment by Hanlard** [comment]
I find that if add "torch.cuda.empty_cahce()" at every train_step then paragram will not OOM ...

**Comment by Hanlard** [comment]
I have used following techniches to save memory...
       --fp16  \
       --checkpoint-activations  \
       --distribute-checkpointed-activations  \
       --fp16-lm-cross-entropy  \
       --use-cpu-initialization

**Comment by eric-haibin-lin** [comment]
Did you intentionally choose MP=2? Would increasing MP help? (e.g. MP=4, DP=4)

**Comment by Hanlard** [comment]
> Did you intentionally choose MP=2? Would increasing MP help? (e.g. MP=4, DP=4)
increasing MP will help...

**Comment by Hanlard** [comment]
> Did you intentionally choose MP=2? Would increasing MP help? (e.g. MP=4, DP=4)

I solve the problem by changing DDP_impl = “local”  to ”torch” ...

**Comment by gbxu** [comment]
In the [readme](https://github.com/NVIDIA/Megatron-LM/blob/main/README.md) it says that "2.5 billion parameters using 2-way model parallel and 1.2 billion parameters with no model parallel". 
It's confusing that splitting the model into 2 shards takes more GPU memory. Assuming that the original model size as M, after 2-way model parallel each GPU should hold M/2. 
Does Anyone know what other GPU footprint comes from with setting DDP_impl “local” and ”torch” respectively? Dose the communication library pin M or more GPU memory?
Thanks.

**Comment by ShivanshuPurohit** [comment]
I am getting out of memory errors with mp>1, which all disappear if I just use `mp=1`, with the deepspeed megatron enabled.
