### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'change_data_ptr'

### ISSUE THREAD

**Issue by Ultramarine** [NVIDIA/Megatron-LM#603]
**Describe the bug**
I use the #[[preprocess_data.py]](https://github.com/NVIDIA/Megatron-LM/blob/main/tools/preprocess_data.py)to process the data of enwiki ,then it appeared. 

**To Reproduce**
I try to find  the package  in NNIDIA/apex and pypi, but I nothing , and seems no others meet it .

**Stack trace/logs**
...lib/python3.7/site-packages/apex/contrib/combine_tensors/combine_tensors.py", line 19, in <module>
from change_data_ptr import change_data_ptr
ModuleNotFoundError: No module named 'change_data_ptr'

**Environment (please complete the following information):**
 - Megatron-LM main?
 - PyTorch 1.81
 - pythion >=3.7.0

**Comment by yiakwy-xpu-ml-framework-team** [comment]
It looks like you have an old Apex (which is used by migatron for kernel fusion impl). change_data_ptr.so is compiled and found (located in ${YOUR_ANACONDA_HOME}/envs/${your_env:llama-py38}/lib/${python_version:python3.8}/site-packages/apex). 

@Ultramarine Wish this helps.
