### ISSUE TITLE
[BUG] communicate shapes when variable_seq_lengths enabled

### ISSUE THREAD

**Issue by xiaojunjie** [NVIDIA/Megatron-LM#620]
**Describe the bug**
When variable_seq_lengths=true and **tp>1**， tensor_shape was not correctly communicated among ranks.

**To Reproduce**
world_size = 8
tp = 2
pp = 4
variable_seq_lengths = true

**Expected behavior**
ranks of parallel_groups arranged as follows:
group0:   0  -  2  -  4  -  6
group1:     1  -  3  -  5   - 7

rank0 send tensor to rank2, success
rank1 send  tensor to rank3, hang

**Environment (please complete the following information):**
 - Megatron-LM commit ID Lastest
 - PyTorch version 1.14.0a0+410ce96
 - CUDA version 11.4
 - NCCL version  2.15.5

**Proposed fix**
Assign **pipeline_model_parallel_group** for P2POp when communicating shapes. Just like when communicating tensor
![image](https://github.com/NVIDIA/Megatron-LM/assets/9473836/4f45898d-67bc-47a0-9af7-224227248f60)

**Comment by xiaojunjie** [comment]
Hey! Correct me if I am wrong @kvareddy

**Comment by kvareddy** [comment]
Sounds good to me. Can you please submit a merge request.

**Comment by xiaojunjie** [comment]
> Sounds good to me. Can you please submit a merge request.

[#622 ] @kvareddy

**Comment by ShaokeXi** [comment]
Hi, @xiaojunjie, do you have any idea why the hang occurs? And why using pipeline_model_parallel_group for P2POp can solve this problem? It seems that the default communication group should work, right?

**Comment by xiaojunjie** [comment]
> Hi, @xiaojunjie, do you have any idea why the hang occurs? And why using pipeline_model_parallel_group for P2POp can solve this problem? It seems that the default communication group should work, right?

As seen in the case above, shape should be communicated separately in two pp groups, because the rank given in line 73 is within a pp group, values 0~3. The default communication group can work if the rank is global. You are right. I think mismatched rank and group caused the communication hang. @ShaokeXi
