### ISSUE TITLE
[BUG] embedding table OOB check

### ISSUE THREAD

**Issue by SeaOfOcean** [NVIDIA/Megatron-LM#623]
**Describe the bug**

In this commit https://github.com/NVIDIA/Megatron-LM/commit/b30f553ff7566da865b9c27b552da79d5f09cfed

add embedding table OOB test

```
assert not torch.any(
            (input_ < 0) | (input_ >= self.num_embeddings)
        ), "An input token is out of bounds of the embedding table"
```
but I found that the Llama2Tokenizer has pad_id == -1, when we pad the data with pad_id, the check will fail.

@wdykas

**Comment by wdykas** [comment]
ok thanks Ill remove the lower check than I guess to support llama
