### ISSUE TITLE
Any plan on supportting LLM pretraining with FSDP?

### ISSUE THREAD

**Issue by lingjiew93** [NVIDIA/Megatron-LM#634]
Hi,

Want to konw that do you have any plan on fsdp to replace 3d parallel?
Since there are zero3 from microsoft and fsdp from meta which all target on data parallel. And I saw there is fsdp in NEMO but not in LLM pretraing scenario. 
Not sure do you have comparison on 3d and fsdp and future plan?

Thanks

**Comment by lingjiew93** [comment]
Closed as I saw it will be supported in Nemo

**Comment by Infi-zc** [comment]
> Closed as I saw it will be supported in Nemo

Is there a link available? Regarding what you mentioned about "will be supported in Nemo."

**Comment by dmarx** [comment]
https://docs.nvidia.com/nemo-framework/user-guide/latest/nemotoolkit/features/parallelisms.html#fully-shared-data-parallelism-fsdp
