### ISSUE TITLE
[QUESTION] Report OOM after 10 iterations when running pretrain_gpt_distributed_with_mp.sh

### ISSUE THREAD

**Issue by THULiusj** [NVIDIA/Megatron-LM#637]
**Your question**
I run pretrain_gpt_distributed_with_mp.sh script, and reported OOM after 10 iterations. Anyone knows why it suddenly reported OOM?

detailed configuratioins as below:
```
GPT-30B model
num_nodes=2
num_gpu_per_node=8
mini_batch_size=2
global_batch_size=2048
enable fp8 transformer engine
enable recompute-activations
enable distributed optimizer
enable flash attention
```

```
Apex=22.04
TransformerEngine=0.12
Megatron=latest commit
cuda=12.2
NCCL=2.18.5
```

**Comment by deepakn94** [comment]
It probably ran OOM as soon as it tried to allocate optimizer state.

Can you paste the relevant output log lines here? (after it sets up the data loader)
