### ISSUE TITLE
[BUG] Building the db for retro needs args.json

### ISSUE THREAD

**Issue by apupneja** [NVIDIA/Megatron-LM#639]
**Describe the bug**
On the [second step](https://github.com/NVIDIA/Megatron-LM/blob/main/tools/retro/build_db.md#step-2-build-retrieval-chunk-database) for building the db for Retro, the `db-build` should produce the args.json, however, I get the following error on running `bash tools/retro/examples/preprocess_data.sh db-build `:

**To Reproduce**
Run `bash tools/retro/examples/preprocess_data.sh db-build `

**Expected behavior**
This step should have created the file, however, it seems that an [assert statement in the validation step](https://github.com/NVIDIA/Megatron-LM/blob/2bc6cd307a11423928c675f741e79e03df23e721/megatron/arguments.py#L371) requires that it is created first.

**Stack trace/logs**
```
Traceback (most recent call last):
  File "/workspace/Megatron-LM/tools/retro/main.py", line 192, in <module>
    initialize_megatron(extra_args_provider=add_retro_args)
  File "/workspace/Megatron-LM/megatron/initialize.py", line 50, in initialize_megatron
    validate_args(args, args_defaults)
  File "/workspace/Megatron-LM/megatron/arguments.py", line 371, in validate_args
    assert os.path.exists(retro_args_path), "retro workdir missing args.json"
AssertionError: retro workdir missing args.json
```

**Environment:**
I used the docker environment provided, along with the latest commit of Megatron=LM

**Comment by zhentingqi** [comment]
Same problem here. Could anyone please tackle this issue?

**Comment by owlsan49** [comment]
This file is provided in https://drive.google.com/file/d/121GqAdMvf8bJEBZRt-SD4uhW-SRWgI3s/view?pli=1
