### ISSUE TITLE
[QUESTION] During pre training, the first global batch can run, but the second global batch reports the error "cuda of memory".

### ISSUE THREAD

**Issue by Rememberz** [NVIDIA/Megatron-LM#640]
Hello, I have encountered an issue: during pre training, the first global batch can run, but the second global batch reports the error "cuda of memory".

Specifically, I tested a set of runnable configuration: 4 nodes with 16 GPUs, 4 GPUs/node, tp=1, pp=8, dp=2, global_batch_size=1024, micro_batch_size=1, and the micro_batch_num = 1024/2=512, 1F1B strategy. I have summarized the memory changes of the GPU15 in the last stage of PP (stable 1F1B stage)：

![tp1pp8dp2_memory_change](https://github.com/NVIDIA/Megatron-LM/assets/55800016/cd3b4cd9-a196-4852-8bee-a072615fc7a6)

It can be seen that in the first minibatch stage, forward propagation increases the memory of 3G, while backward propagation reduces the memory of 3G, with the highest memory usage of 17.5G. In the second minibatch stage, the first forward propagation increased **10G** of memory, but the first backward propagation only reduced 3G of memory, with the highest memory usage of 24.5G. Subsequently, both forward and backward directions steadily increased by 3G and decreased by 3G, resulting in an inexplicable increase of 7G of memory.

May I ask if anyone knows the reason for this abnormal increase in GPU memory footprint? How to solve this problem?

**Comment by deepakn94** [comment]
It is expected: the optimizer state is allocated lazily the first time the optimizer runs. You can try to measure the footprint after the optimizer step, and you should see a jump the first time the optimizer step runs.
