### ISSUE TITLE
[ENHANCEMENT] Asynchronously save the checkpoint to storage with minimizing the paused time of training.

### ISSUE THREAD

**Issue by workingloong** [NVIDIA/Megatron-LM#651]
**Is your feature request related to a problem? Please describe.**

Fault often occurs during the training of a large LLM.  To recover the training, users usually periodically save checkpoints. However,  
the time to save a checkpoint to storage needs minutes. High-frequency checkpoints will waste an amount of time on GPUs. If using low-frequency checkpoints, the latest checkpoint is far away from the training break point, which also wastes an amount of iterations.  It is important to shorten the checkpoint time to improve the goodput of training.

**Describe the solution you'd like**

We can synchronously copy the state dict into the shared memory of training processes and the main process of `torchrun`. The main process can asynchronously save the state dict from the shared memory to storage without any interference of training.

**Describe alternatives you've considered**

**Proposed implementation**

We have implemented asynchronous persistence in [DLRover Flash Checkpoint](https://github.com/intelligent-machine-learning/dlrover/blob/master/docs/blogs/flash_checkpoint.md).  The APIs to support Megatron-LM is same as the `save_checkpoint` and `load_checkpoint` like

```python
from dlrover.trainer.torch.flash_checkpoint.megatron import save_checkpoint
from dlrover.trainer.torch.flash_checkpoint.megatron import load_checkpoint
from dlrover.trainer.torch.flash_checkpoint.megatron import StorageType

if args.save and iteration % save_memory_interval == 0:
    save_checkpoint(iteration, model, optimizer,
                    opt_param_scheduler, storage_type=StorageType.MEMORY,)
```

We are happy to contribute the asynchronous persistence to the Megatron-LM.

**Additional context**

We have conducted [experiments](https://github.com/intelligent-machine-learning/dlrover/blob/master/docs/blogs/flash_checkpoint.md#benchmark-experiments) to test the performance of asynchronous persistence with GPT2-1.5B on 2 * A100, the time to pause training decreases to 2.1s from 11s to save checkpoint to MVMe SSD.

**Comment by elliottnv** [comment]
Feature is available in latest version. Closing the ticket.
