### ISSUE TITLE
[QUESTION] Question about compute theoretical memory usage of weight and optimizer.

### ISSUE THREAD

**Issue by jkunchen** [NVIDIA/Megatron-LM#654]
Hi, I'm a bit uncertain about the computation of `num_bytes_per_parameter`. From what I understand in Mixed-Precision training, there are typically 4 bytes allocated for storing fp16 gradients and parameters and an extra 12 bytes for the optimizer. However, in this script, it appears to be computed as 18 bytes. Could you help me understand this apparent discrepancy?

https://github.com/NVIDIA/Megatron-LM/blob/3b27d30eecc5b0857e6652d872666d9a141b36e3/megatron/theoretical_memory_usage.py#L62-L64

**Comment by deepakn94** [comment]
2 bytes for model parameters used for fprop and bprop, 4 bytes for main parameters, 4 bytes for gradients, 8 bytes for Adam states. 2 + 4 + 4 + 8 = 18. The model parameters and gradients are *not* partitioned when using the distributed optimizer.
