### ISSUE TITLE
[BUG] Function IndexPutBackward0 returned an invalid gradient at index.

### ISSUE THREAD

**Issue by TriLoo** [NVIDIA/Megatron-LM#655]
**Describe the bug**
Add dropout layer to tensor model parallel context, but assure different mp rank got same dropout mask, then dropout layer will raise this error: 

**To Reproduce**
Steps to reproduce the behavior. The easier it is to reproduce the faster it will get maintainer attention.

**Expected behavior**
Different mp rank within same mp group will got same dropout mask for input_parallel at line 186:
![image](https://github.com/NVIDIA/Megatron-LM/assets/16267477/805d0a29-6eaf-493d-bd2a-0d11733be423)

**Stack trace/logs**
![image](https://github.com/NVIDIA/Megatron-LM/assets/16267477/ece32151-a711-4491-9d03-acc7c937a843)

**Environment (please complete the following information):**
 - Megatron-LM commit ID: 2bc6cd307a11423928c675f741e79e03df23e721
 - PyTorch version: 2.0.1+cu117
 - CUDA version: 11.8
 - NCCL version: 8.9.0

**Comment by elliottnv** [comment]
Won't fix. Closing.
