### ISSUE TITLE
KeyError: running GPT text generation sample

### ISSUE THREAD

**Issue by dnola** [NVIDIA/Megatron-LM#66]
Hello,

Running in the __20.12 PyTorch NGC container on V100__, when I try to run examples/generate_text.sh I get a series of errors...

1. It can't find tools/generate_samples_gpt2.py

If I change the name of tools/generate_samples_gpt.py to tools/generate_samples_gpt2.py it proceeds for a bit until...

2. It doesn't like the batch size parameter:

`AssertionError: --batch-size argument is no longer valid, use --micro-batch-size instead
`

If I change the argument name in generate_text.sh I can get it to proceed more until...

3. I get a KeyError:
`
> building GPT2BPETokenizer tokenizer ...
 > padded vocab (size: 50257) with 47 dummy tokens (new size: 50304)
> initializing torch distributed ...
> initializing tensor model parallel with size 1
> initializing pipeline model parallel with size 1
> setting random seeds to 1234 ...
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
building GPT model ...
 > number of parameters on (tensor, pipeline) model parallel rank (0, 0): 354871296
WARNING: could not find the metadata file checkpoints/gpt2_345m/latest_checkpointed_iteration.txt 
    will not load any checkpoints and will start from random
Avg s/batch: 47.92085814476013
Traceback (most recent call last):
  File "tools/generate_samples_gpt2.py", line 116, in <module>
    main()
  File "tools/generate_samples_gpt2.py", line 111, in main
    generate_and_write_samples_unconditional(model)
  File "/workspace/megatron/text_generation_utils.py", line 339, in generate_and_write_samples_unconditional
    for datum in generate_samples_unconditional(model):
  File "/workspace/megatron/text_generation_utils.py", line 317, in generate_samples_unconditional
    text = tokenizer.detokenize(tokens)
  File "/workspace/megatron/tokenizer/tokenizer.py", line 216, in detokenize
    return self.tokenizer.decode(token_ids)
  File "/workspace/megatron/tokenizer/gpt2_tokenization.py", line 284, in decode
    text = ''.join([self.decoder[token] for token in tokens])
  File "/workspace/megatron/tokenizer/gpt2_tokenization.py", line 284, in <listcomp>
    text = ''.join([self.decoder[token] for token in tokens])
KeyError: 50280
`

Any advice on how to proceed? Were the changes I made appropriate?

Thank you!

**Comment by jaredcasper** [comment]
Yes, that change to --micro-batch-size is correct, we need to update the example script. The problem you ran into is you need to give it a valid checkpoint. Without a checkpoint to load it'll generate random tokens, one of which is not a valid token.
