### ISSUE TITLE
[QUESTION] Why use CPU to gather distributed optimizer

### ISSUE THREAD

**Issue by zyksir** [NVIDIA/Megatron-LM#664]
Can we use GPU to gather the state and then save it? Since with GPU we can use NCCL and rdma, and now we have to use gloo and TCP.

**Comment by deepakn94** [comment]
We use gloo / CPU to collect the distributed optimizer state across DP ranks, which might not all fit in GPU memory.

**Comment by deepakn94** [comment]
Going to close this, feel free to re-open if you still have questions.
