### ISSUE TITLE
[QUESTION] What's the different between implementation of GPT model in megatron/model/gpt_model.py and megatron/core/model/gpt/gpt_model.py?

### ISSUE THREAD

**Issue by shaonan1993** [NVIDIA/Megatron-LM#666]
Hi, I find there are two implementation of gpt model in the repo. I want to know to know what's the different between them?

**Comment by deepakn94** [comment]
They should be similar. `megatron/model/gpt_model.py` will eventually be deprecated.

**Comment by deepakn94** [comment]
Going to close this.
