### ISSUE TITLE
[QUESTION]num_warmup_microbatch = (pipeline_parallel_size - pipeline_parallel_rank - 1) * 2

### ISSUE THREAD

**Issue by zhouyiyuan-mt** [NVIDIA/Megatron-LM#675]
https://github.com/NVIDIA/Megatron-LM/blob/de4028a9d45bd65c67e1a201d9e0690bd6cb4304/megatron/core/pipeline_parallel/schedules.py#L503

I am confused about why num_warmup_microbatch = (pipeline_parallel_size - pipeline_parallel_rank - 1) * 2 + num_chunk * pipeline_parallel_size, rather than  num_warmup_microbatch = (pipeline_parallel_size - pipeline_parallel_rank - 1) + num_chunk * pipeline_parallel_size, where the latter looks like more natural.  Wait for your answer, thank you.

**Comment by deepakn94** [comment]
<img width="1278" alt="image" src="https://github.com/NVIDIA/Megatron-LM/assets/2724038/d6d6a7f9-116d-45c1-bcbe-7eb28cbb1988">

The number of warmup microbatches is the number of microbatches needed until a pipeline stage can move to its "steady state" behavior of 1 forward and then 1 backward microbatch.

**Comment by zhouyiyuan-mt** [comment]
> <img alt="image" width="1278" src="https://private-user-images.githubusercontent.com/2724038/299199652-d6d6a7f9-116d-45c1-bcbe-7eb28cbb1988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcyNzcsIm5iZiI6MTcwNjA3Njk3NywicGF0aCI6Ii8yNzI0MDM4LzI5OTE5OTY1Mi1kNmQ2YTdmOS0xMTZkLTQ1YzEtYmNiZS03ZWIyOGNiYjE5ODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMDYxNjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmU0NzdmNDY2MWIzYzYyMDgwNWIxNmY2NjBjMjgzMGI0YTYyZjZiZjUwZjYwODdkNTc0MDlhYTVlZjFmOWJkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5WjnGLBVwvq5utYpT5vfyX7YlkYJQ-ihsiRUyg5q1L8">
> The number of warmup microbatches is the number of microbatches needed until a pipeline stage can move to its "steady state" behavior of 1 forward and then 1 backward microbatch.

https://github.com/NVIDIA/Megatron-LM/blob/de4028a9d45bd65c67e1a201d9e0690bd6cb4304/megatron/core/pipeline_parallel/schedules.py#L503
https://github.com/NVIDIA/Megatron-LM/blob/de4028a9d45bd65c67e1a201d9e0690bd6cb4304/megatron/core/pipeline_parallel/schedules.py#L1138
I know the meaning of  num_warmup_microbatch. I want to know why it is different to calculate  num_warmup_microbatch between forward_backward_pipelining_without_interleaving and forward_backward_pipelining_with_interleaving, and what is the meanning of the factor "2" in forward_backward_pipelining_with_interleaving.

**Comment by deepakn94** [comment]
For the interleaved schedule, the number of warmup microbatches is 10, 8, 6, 4 (difference of 2). For the non-interleaved schedule, the number of warmup microbatches is 3, 2, 1, 0 (difference of 1). Our interleaved schedule is trying to make sure all pipeline stages are running forward and backward passes in the same time step; the non-interleaved schedule does not have that restriction.

**Comment by zhouyiyuan-mt** [comment]
> For the interleaved schedule, the number of warmup microbatches is 10, 8, 6, 4 (difference of 2). For the non-interleaved schedule, the number of warmup microbatches is 3, 2, 1, 0 (difference of 1). Our interleaved schedule is trying to make sure all pipeline stages are running forward and backward passes in the same time step; the non-interleaved schedule does not have that restriction.

What are advantages to make all pipeline stages running forward and backward passes in the same time step?

**Comment by deepakn94** [comment]
We needed this since we have wraparound with the interleaved schedule: the last rank may need to send tensors to the first rank. If the different ranks in a pipeline are offset, then the implementation gets more complicated to schedule that last-to-first (or first-to-last when in backward pass) communication.

**Comment by zhouyiyuan-mt** [comment]
Thanks! Great idea!

**Comment by deepakn94** [comment]
Closing this, feel free to re-open if needed.
