### ISSUE TITLE
Is there any tool to convert hf llama-2 to Megatron with **mcore** model instead of legacy model?

### ISSUE THREAD

**Issue by 1049451037** [NVIDIA/Megatron-LM#703]
I have converted the model followed by https://github.com/NVIDIA/Megatron-LM/blob/main/docs/llama2.md#huggingface-format , but the generated model is legacy GPT model. I want to use mcore model.

**Comment by TING2938** [comment]
I write the model conversion code, but it hasn't been fully tested yet, maybe you can have a try. 

https://github.com/TING2938/Megatron-LM/tree/main/tools/checkpoint

**Comment by 1049451037** [comment]
Thank you for your reply! I have transformed the model and got a checkpoint file. How can I run your converted model for inference?

**Comment by 1049451037** [comment]
I think there is something wrong... I use the official text generation server and cli in Megatron-LM to run inference. The output of llama2-7b is weird:

<img width="635" alt="image" src="https://github.com/NVIDIA/Megatron-LM/assets/15194939/1f853a22-e919-4588-9c58-4b6fc4fd387e">

**Comment by 1049451037** [comment]
Now there is a new problem...

```
  File "/megatron/lib/python3.10/site-packages/transformer_engine/pytorch/attention.py", line 2552, in forward
    qkv_layout, query_layer, key_layer, value_layer = _get_qkv_layout(  File "/megatron/lib/python3.10/site-packages/transformer_engine/pytorch/attention.py", line 1466, in _get_qkv_layout
    raise Exception("The provided qkv memory layout is not supported!")
Exception: The provided qkv memory layout is not supported!
```

**Comment by TING2938** [comment]
> I think there is something wrong... I use the official text generation server and cli in Megatron-LM to run inference. The output of llama2-7b is weird:
> 
> <img alt="image" width="635" src="https://private-user-images.githubusercontent.com/15194939/307655397-1f853a22-e919-4588-9c58-4b6fc4fd387e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzM0MzgsIm5iZiI6MTcwODkzMzEzOCwicGF0aCI6Ii8xNTE5NDkzOS8zMDc2NTUzOTctMWY4NTNhMjItZTkxOS00NTg4LTljNTgtNGI2ZmM0ZmQzODdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA3Mzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNzY3NjdiOTdjYmZjNzY4YzYxZTIwNmM4ODllZmU4YTk1M2QyNmY0ZGVlMTUxYmNlMDg2NzVkMDQ2NGNhYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tt0CtufNbrC495VlmpiuRnphbpBvBZ0bVGOX0RnIjak">

what is the version of your transformer_engin? 

you can update to stable, pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable

**Comment by TING2938** [comment]
> Now there is a new problem...
> 
> ```
>   File "/megatron/lib/python3.10/site-packages/transformer_engine/pytorch/attention.py", line 2552, in forward
>     qkv_layout, query_layer, key_layer, value_layer = _get_qkv_layout(  File "/megatron/lib/python3.10/site-packages/transformer_engine/pytorch/attention.py", line 1466, in _get_qkv_layout
>     raise Exception("The provided qkv memory layout is not supported!")
> Exception: The provided qkv memory layout is not supported!
> ```

what is the version of your transformer_engin?

you can update to stable, pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable

**Comment by 1049451037** [comment]
My version is stable exactly.

**Comment by 1049451037** [comment]
I also tried the main branch of TransformerEngine. However, same problem occurs.

**Comment by 1049451037** [comment]
Finally, I make it work by adding lines of hard-code after https://github.com/NVIDIA/Megatron-LM/blob/5f9c870f9f24b482509699d206a9dbb00958f6fc/megatron/core/transformer/attention.py#L289

```python
            assert key.shape == value.shape
            value = torch.as_strided(value, value.shape, key.stride())
```

However, the inference result is not right... So your transformation code has some bugs...

```
Enter prompt: Q: What is the capital of China? A:
Enter number of tokens to generate: 10
Megatron Response: 
Q: What is the capital of China? A: Confusion. Anyone can answer the question: $
```

**Comment by 1049451037** [comment]
I changed the model from llama2-7b to llama2-7b-chat. Now it works! Thank you!

**Comment by CaesarWWK** [comment]
> > Now there is a new problem...
> > ```
> >   File "/megatron/lib/python3.10/site-packages/transformer_engine/pytorch/attention.py", line 2552, in forward
> >     qkv_layout, query_layer, key_layer, value_layer = _get_qkv_layout(  File "/megatron/lib/python3.10/site-packages/transformer_engine/pytorch/attention.py", line 1466, in _get_qkv_layout
> >     raise Exception("The provided qkv memory layout is not supported!")
> > Exception: The provided qkv memory layout is not supported!
> > ```
> 
> what is the version of your transformer_engin?
> 
> you can update to stable, pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable

I encounter with a bug when using your saver_llama2_hf to convert mcore llama2-70b to hf 
in saver_llama2_hf, the queue module report that cannot find package megatron. 
I solved it by adding the following code in the start of save_checkpoint function
`sys.path.append(os.path.abspath(
        os.path.join(os.path.dirname(__file__),
                     os.path.pardir,
                     os.path.pardir)))
    sys.path.insert(0, 'path-to-your-megatron-dir')`

**Comment by yiakwy-xpu-ml-framework-team** [comment]
> I changed the model from llama2-7b to llama2-7b-chat. Now it works! Thank you!

Yes you should use sft model (chat) to do the QA test. These SFT models are instructed to answer questions. Pre-train models is just learn the "capacity" or knowledge, they don't know how to "use" them.
