### ISSUE TITLE
Does Megatron has plan to support Gemma？

### ISSUE THREAD

**Issue by anlongfei** [NVIDIA/Megatron-LM#707]
**Your question**
Does Megatron has plan to support Gemma？

**Comment by ethanhe42** [comment]
nemo (using megatron-core) supports it https://github.com/NVIDIA/NeMo/blob/f005f1323eaf9a23ad6dc4bc326dc95bf0002e8d/examples/nlp/language_modeling/conf/megatron_gemma_config.yaml#L4

**Comment by fwyc0573** [comment]
also looking for example of gemma in megatron-lm
