### ISSUE TITLE
Is this assertion correct?

### ISSUE THREAD

**Issue by mayank31398** [NVIDIA/Megatron-LM#718]
https://github.com/NVIDIA/Megatron-LM/blob/53a350eddbce38f036fe5884c3fec955cf710b9e/megatron/core/datasets/indexed_dataset.py#L293

I have a bunch of datasets that used to work with older megatron (when data logic for GPTDatasets was not moved to core).
Now this assertion creates problem for them.
Is this correct?
The 2 assertions above this make sense but I can't figure out why this must be true?

@deepakn94 sorry to tag you since I don't know who to tag

**Comment by jkamalu** [comment]
Hi Mayank, Thanks for opening the issue. The `document_indices` are the indices which bookend the documents. As such, the final document index should correspond to the final sequence, whose index would be the length of the `sequence_lengths`. Can you please provide prints to help bottom out on this issue?

Starting perhaps will all values in the three assertions?

**Comment by mayank31398** [comment]
Yeah but is this also true if we do splitting by sentences?

**Comment by jkamalu** [comment]
The execution path is very similar. It would help to have the values and to see what kind of difference there is.

**Comment by mayank31398** [comment]
My bad, this is due to an internal bug
closing @jkamalu

**Comment by jkamalu** [comment]
@mayank31398 Can you disclose what caused your error? We'd like to make sure other users are aware of any potential pitfalls here.
