### ISSUE TITLE
 why Megatron's ParallelAttention currently only supports SelfAttention with a 'causal' MaskType?

### ISSUE THREAD

**Issue by chenfengshijie** [NVIDIA/Megatron-LM#719]
Could you please explain why Megatron's ParallelAttention currently only supports SelfAttention with a 'causal' MaskType? Also, is there potential for flashAttention support in cases where the Mask is 'None' for both Multihead Self Attention (MSA) and Multihead Cross Attention (MCA)?

In Parallel class,I noticed this:
![image](https://github.com/NVIDIA/Megatron-LM/assets/42408053/9b9be4ef-e4d9-4ade-8429-fc3d82ae889c)

It appears that the utilization of flash-attention is currently confined to causal self-attention. However, considering that flash-attention is compatible with padding mask types and cross-attention, could you elucidate on any technical challenges or distinctions that might prevent its extension to these contexts?

**Comment by ethanhe42** [comment]
you can use MaskType None when `--use-mcore-models`
