### ISSUE TITLE
[BUG]  "referenced before assignment" when training MOE+PP

### ISSUE THREAD

**Issue by shh2000** [NVIDIA/Megatron-LM#721]
**Describe the bug**
I run the sample given in `core/transformer/moe`, setting TP=1, PP=2, EP=8, on 2 DGXA100-8GPUperNode. Other hyperparameters or args remain unchanged.

**To Reproduce**
write the sample code into `run.sh`, then use command `bash run.sh` on 2 node.

**Expected behavior**
when TP=2, PP=1, EP=8, the task can be trained well. but when TPPPEP=1/2/8, i got `"UnboundLocalError: local variable 'loss' referenced before assignment"`

**Additional context**
I see the code at` Megatron-LM/megatron/core/pipeline_parallel/schedules.py, line 216`:

```
if parallel_state.is_pipeline_last_stage():
        if not collect_non_loss_data:
            output_tensor = loss_func(output_tensor)
            loss, loss_reduced = output_tensor
            output_tensor = loss / num_microbatches
            forward_data_store.append(loss_reduced)
        else:
            data = loss_func(output_tensor, non_loss_data=True)
            forward_data_store.append(data)

    if config.timers is not None:
        config.timers('forward-compute').stop()

    # Set the loss scale for the auxiliary loss of the MoE layer.
    # Since we use a trick to do backward on the auxiliary loss, we need to set the scale explicitly.
    if hasattr(config, 'num_moe_experts') and config.num_moe_experts is not None:
        # Calculate the loss scale based on the grad_scale_func if available, else default to 1.
        loss_scale = (
            config.grad_scale_func(torch.tensor(1.0, device=loss.device))
            if config.grad_scale_func is not None
            else torch.tensor(1.0)
        )
        # Set the loss scale
        MoEAuxLossAutoScaler.set_loss_scale(loss_scale / num_microbatches)

```

if not last PP stage, there won't be a "loss" variable, which is referenced in the next part"device=loss.device".

**Comment by shaonan1993** [comment]
You can try this: https://github.com/NVIDIA/Megatron-LM/pull/700

**Comment by shh2000** [comment]
> You can try this: #700

thanks, i'll use this solution locally. Looking forward to PR merged(or NV official update commits)

**Comment by deepakn94** [comment]
We have an internal fix for this, we will push soon.

**Comment by shh2000** [comment]
proved, the bug had been fixed, thanks!
