### ISSUE TITLE
checkpoint_util.py

### ISSUE THREAD

**Issue by yangzhipeng1108** [NVIDIA/Megatron-LM#732]
python tools/checkpoint_util.py \
        --model-type GPT \
        --load-dir /workspace/model/megatron-models/345m-init-mp\
        --save-dir /workspace/model/megatron-models/345m-init-mp-out \
        --target-tensor-parallel-size 1 \
        --target-pipeline-parallel-size 1

![image](https://github.com/NVIDIA/Megatron-LM/assets/33448441/377e83e8-f688-4dbd-ac92-d8ebf9f70001)

**Comment by yangzhipeng1108** [comment]
python tools/checkpoint_util.py \
        --model-type GPT \
        --load-dir /workspace/model/megatron-models/345m-init-mp\
        --save-dir /workspace/model/megatron-models/345m-init-mp-out \
        --target-tensor-parallel-size 1 \
        --target-pipeline-parallel-size 1

**Comment by sawanjr** [comment]
checkpoint_util.py  failed to run because the --vocab_file argument is missing!
