### ISSUE TITLE
How to calculate FLOPS?

### ISSUE THREAD

**Issue by ShivanshuPurohit** [NVIDIA/Megatron-LM#76]
I am trying to determine what is the total GPU utilization in training a GPT-like LM. As per this table
![image](https://user-images.githubusercontent.com/42869065/110487652-cb4b3f00-8113-11eb-8f0c-0a14c27d9b2e.png)
A 1B model on a single A100 achieves ~150TFLOPs, while 8 achieve 109TFLOPs/GPU on an 8B model. What is the formula used to calculate FLOPs for LM?

**Comment by Stonepia** [comment]
In this paper : "Efficient Large-Scale Language Model Training on GPU Clusters" has offered a formula, but I am not calculated it by hand, so I don't know whether this would fit your table.
