### ISSUE TITLE
[QUESTION] Is PackedSeqParams still under development?

### ISSUE THREAD

**Issue by XLzed** [NVIDIA/Megatron-LM#771]
I want to use sequence packing without Cross-Contamination Attention like this: https://github.com/Dao-AILab/flash-attention/issues/432. The GPTDataset within megatron is using sequence packing by default, and I found the PackedSeqParams can be passed into core-attention, but currentlly it is not usable, when can I use it to achieve seq packing without cross-contamination attention.

**Comment by XLzed** [comment]
Well, I found it's used in Nemo, so will megatron-lm support sft+packedDataset? or recommended to use nemo directly?

**Comment by Leo-T-Zang** [comment]
Did you figure it out? Thanks!

**Comment by XLzed** [comment]
> Did you figure it out? Thanks!

I use nemo to do sft training currently, the PackedSeqParams is used by NeMo sequence packing.
