### ISSUE TITLE
[BUG]The bug of the `average_losses_across_data_parallel_group`.

### ISSUE THREAD

**Issue by Baibaifan** [NVIDIA/Megatron-LM#779]
**Describe the bug**
When you use `average_losses_across_data_parallel_group` in pretrain_gpt.py with ep+dp, you could meet a bug which is wrong distribution group. Such as figure 1.
figure1:
<img width="989" alt="image" src="https://github.com/NVIDIA/Megatron-LM/assets/39549453/e7401f02-90c6-457e-9e47-a54d8099a74b">

**To Reproduce**
N/A

**Expected behavior**
N/A

**Stack trace/logs**
N/A

**Environment (please complete the following information):**
 - Megatron-LM commit ID: ba773259dbe5735fbd91ca41e7f4ded60b335c52

**Proposed fix**
N/A

**Additional context**
N/A

**Comment by ethanhe42** [comment]
is it an error or just inaccuracy? it should average across ep+dp ranks

**Comment by Baibaifan** [comment]
> is it an error or just inaccuracy? it should average across ep+dp ranks

@ethanhe42 I think it is a bug, because ep+dp, there will be an error running here.

**Comment by aoyulong** [comment]
@Baibaifan I think it 's not a bug since ep is within dp.

**Comment by Baibaifan** [comment]
> average_losses_across_data_parallel_group

ok, I found that during initialization there was `with_context_parallel=True`，and I changed this configuration and my problem disappeared, so I thought there was something wrong with this part.
when ep+dp, `_DATA_PARALLEL_GROUP_WITH_CP` == `_DATA_PARALLEL_GROUP`.
![image](https://github.com/NVIDIA/Megatron-LM/assets/39549453/6645a4f9-0f48-4fad-9217-6c2de328a67a)
