### ISSUE TITLE
How to Train on Multiple AWS Machines?

### ISSUE THREAD

**Issue by rhythmswing** [NVIDIA/Megatron-LM#79]
Hi,

I’m trying to apply this library for distributed training across multiple AWS instances, but I am not sure how to setup. Currently I can run Pre-training perfectly with the example script (“pretrain_bert_distributed.sh”). I wonder how to train on more than one instances though?

I’m trying to naively just changing the environment variables in the script. In the main instance I keep everything unchanged except that NNODES=2, and in the second instance I changed MASTER_ADDR to the local IP address of the main instance, NNODES=2, nad NODE_RANK=1. I tried to run both scripts on both instances, but they get stuck at “initializing torch distributed ...”. 

Thanks in advance for any help!

Rui

**Comment by rhythmswing** [comment]
Fixed with correct network settings.

**Comment by cdj0311** [comment]
> Fixed with correct network settings.

Hi,
I have the same problem, could you post your script?
