### ISSUE TITLE
How to set up fp8 training

### ISSUE THREAD

**Issue by yangzhipeng1108** [NVIDIA/Megatron-LM#817]
**Your question**
Ask a clear and concise question about Megatron-LM.

**Comment by felipeliliti** [comment]
Chamada de vídeo ou banco de dados

**Comment by felipeliliti** [comment]
Configurar o treinamento FP8 no NVIDIA Megatron-LM envolve alguns passos. O FP8 é uma progressão natural para acelerar o treinamento de aprendizado profundo (DL) além dos formatos de 16 bits comuns em processadores modernos². Aqui estão algumas informações que podem ajudar:

1. **FP8 no Deep Learning**: O FP8 é uma progressão natural para acelerar o treinamento de aprendizado profundo (DL) além dos formatos de 16 bits comuns em processadores modernos².

2. **FP8 LM - Treinamento de Grandes Modelos de Linguagem com FP8**: Este vídeo compartilha o artigo que propõe um framework de precisão mista automática FP8 que incorpora precisão de 8 bits em gradientes, estados do otimizador e treinamento distribuído para agilizar o processo de treinamento do LLM³.

3. **Usando FP8 com o Transformer Engine**: A documentação da NVIDIA pode ter mais detalhes sobre como configurar o treinamento FP8 com o Transformer Engine⁶.

4. **Migrando do Megatron-LM**: A documentação da NVIDIA também fornece informações sobre como migrar do Megatron-LM, que pode ser útil se você estiver configurando o treinamento FP8 após uma migração⁷.

5. **Problemas com o FP8 no GitHub**: Há uma discussão no GitHub sobre o uso do FP8 com o Transformer Engine que pode ser relevante. Um usuário mencionou que, após habilitar o FP8 Transformer Engine com dois argumentos --fp8-hybrid, --transformer-impl "transformer_engine", a velocidade do treinamento era de cerca de 0.24s/step⁸.

Por favor, note que essas informações são baseadas em recursos disponíveis publicamente e podem não ser totalmente precisas ou atualizadas. Recomendo verificar a documentação oficial da NVIDIA e o repositório do GitHub para obter as informações mais recentes e precisas. Se você tiver mais perguntas ou precisar de mais ajuda, sinta-se à vontade para perguntar! 😊

Origem: conversa com o Bing, 12/05/2024
(1) FP8 for Deep Learning | NVIDIA On-Demand. https://www.nvidia.com/en-us/on-demand/session/gtcspring23-s52166/.
(2) FP8 LM - Training FP8 Large Language Models. https://www.youtube.com/watch?v=VtVPt6VLJkA.
(3) Using FP8 with Transformer Engine - NVIDIA Documentation Hub. https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/examples/fp8_primer.html.
(4) Migrating from Megatron-LM - NVIDIA Docs. https://docs.nvidia.com/nemo-framework/user-guide/latest/nemotoolkit/nlp/nemo_megatron/mlm_migration.html.
(5) fp8 transformer engine only brings 35% speed up? #396 - GitHub. https://github.com/NVIDIA/Megatron-LM/issues/396.
(6) Announcing Megatron for Training Trillion Parameter Models and NVIDIA Riva Availability | NVIDIA Technical Blog. https://developer.nvidia.com/blog/announcing-megatron-for-training-trillion-parameter-models-riva-availability/.
(7) How to set up fp8 training · Issue #817 · NVIDIA/Megatron-LM. https://github.com/NVIDIA/Megatron-LM/issues/817.
(8) GitHub - NVIDIA/Megatron-LM: Ongoing research training transformer .... https://github.com/NVIDIA/Megatron-LM.
(9) undefined. https://www.linkedin.com/in/fahdmirza/.
(10) undefined. https://www.youtube.com/@fahdmirza.

**Comment by felipeliliti** [comment]
Mandei os links também

**Comment by yangzhipeng1108** [comment]
thanks
