### ISSUE TITLE
[QUESTION] Is FP32 supported in MultiNode Training

### ISSUE THREAD

**Issue by JiwenJ** [NVIDIA/Megatron-LM#837]
We plan to finetune a model in MegatronLM, the model (11B) is sharded with tp=4, pp=16. We want to finetune the model in fp32 rather than fp16 or bf16. The error is as follows:
```bash
TypeError: Can't instantiate abstract class FP32Optimizer with abstract methods sharded_state_dict
        return FP32Optimizer(optimizer, config, init_state_fn,)return FP32Optimizer(optimizer, config, init_state_fn,)

  File "/work/home/sx_mitee/Megatron-LM/megatron/core/optimizer/__init__.py", line 252, in _get_megatron_optimizer_based_on_param_groups
TypeError: Can't instantiate abstract class FP32Optimizer with abstract methods sharded_state_dict
    return FP32Optimizer(optimizer, config, init_state_fn,)
    return FP32Optimizer(optimizer, config, init_state_fn,)
    _get_megatron_optimizer_based_on_param_groups(

```

**Comment by deepakn94** [comment]
Stay tuned, we have a bugfix in the works.

**Comment by JiwenJ** [comment]
I try to use the flag `--use-distributed-optimzier`, and it does not report the error. So is `--use-distributed-optimzier`  a must for multinode training in fp32?

**Comment by deepakn94** [comment]
Should work now: https://github.com/NVIDIA/Megatron-LM/commit/020b51796e1302bc91a30154b665a4d0afc59dd6.

**Comment by deepakn94** [comment]
Going to close this, please re-open if you are still seeing issues.
