### ISSUE TITLE
[QUESTION]Mamba-2-hybrid Weights

### ISSUE THREAD

**Issue by Mooler0410** [NVIDIA/Megatron-LM#864]
**Your question**
[An Empirical Study of Mamba-based Language Models](https://arxiv.org/abs/2406.07887)](https://github.com/NVIDIA/Megatron-LM/tree/ssm/examples/mamba)
Hi! I'm impressed by this work and cannot wait to try the new mamba-2-hybrid.  This paper mentioned that the weights are released on Huggingface. But I cannot find any. Wondering have they been released? If yes, where can I download them? 

Thanks a lot for your folks' contribution to the community!

**Comment by ruipeterpan** [comment]
I think the model weights are released here: https://huggingface.co/collections/nvidia/ssms-666a362c5c3bb7e4a6bcfb9c

**Comment by Mooler0410** [comment]
> I think the model weights are released here: https://huggingface.co/collections/nvidia/ssms-666a362c5c3bb7e4a6bcfb9c

Thanks! I've already found it. While when this question is posted, the weights haven't been set as public.

Now, I'm looking for the tokenizer🤣. To run the example, a tokenizer is required. But I cannot find any. Any idea about this?

**Comment by ruipeterpan** [comment]
I think the tokenizer path should point to the .model file in the huggingface repos. For example, I downloaded the `mamba2-hybrid-8b-3t-4k` repo from huggingface, and `mamba2-hybrid-8b-3t-4k/mt_nlg_plus_multilingual_ja_zh_the_stack_frac_015_256k.model` is the tokenizer. I'm running inference using `run_text_gen_server_8b.sh` and the checkpoint/tokenizer paths are
```
CHECKPOINT_PATH="/workspace/checkpoints/mamba2-hybrid-8b-3t-4k/"
TOKENIZER_PATH="/workspace/checkpoints/mamba2-hybrid-8b-3t-4k/mt_nlg_plus_multilingual_ja_zh_the_stack_frac_015_256k.model"
```
respectively.

**Comment by Mooler0410** [comment]
Wow, thank you so much for your guidance! It took me hours to find something like a tokenizer. 

Never used megatron before🙃. You did save my life!!

**Comment by fxnie** [comment]
#!/bin/bash


CHECKPOINT_PATH="/workspace/mnt/xxx/models/mamba2-hybrid-8b-3t-4k"
TOKENIZER_PATH="/workspace/mnt/xxx/models/mamba2-hybrid-8b-3t-4k/mt_nlg_plus_multilingual_ja_zh_the_stack_frac_015_256k.model"

DISTRIBUTED_ARGS="--nproc_per_node 1 \
                  --nnodes 1 \
                  --node_rank 0 \
                  --master_addr localhost \
                  --master_port 6608"

export NCCL_IB_SL=1
export CUDA_DEVICE_MAX_CONNECTIONS=1
export NCCL_IB_TIMEOUT=19
export NCCL_IB_QPS_PER_CONNECTION=4

export TRITON_CACHE_DIR="./triton-cache/"
export TRITON_CACHE_MANAGER="megatron.core.ssm.triton_cache_manager:ParallelFileCacheManager"

torchrun $DISTRIBUTED_ARGS /workspace/mnt/xxx/Megatron-LM/tools/run_mamba_text_generation_server.py \
       --tensor-model-parallel-size 1  \
       --pipeline-model-parallel-size 1  \
       --untie-embeddings-and-output-weights \
       --num-layers 56  \
       --hidden-size 4096  \
       --load ${CHECKPOINT_PATH}  \
       --num-attention-heads 32  \
       --group-query-attention \
       --num-query-groups 8 \
       --hybrid-attention-ratio 0.08 \
       --hybrid-mlp-ratio 0.5 \
       --attention-dropout 0.0 \
       --hidden-dropout 0.0 \
       --disable-bias-linear \
       --normalization RMSNorm \
       --seq-length 4096  \
       --max-position-embeddings 4096  \
       --position-embedding-type none \
       --tokenizer-type GPTSentencePieceTokenizer  \
       --tokenizer-model ${TOKENIZER_PATH} \
       --distributed-backend nccl \
       --distributed-timeout-minutes 1440 \
       --bf16  \
       --micro-batch-size 1  \
       --use-mcore-models \
       --spec megatron.core.models.mamba.mamba_layer_specs mamba_stack_spec \
       --seed 42


error：
state = torch.load(state, map_location='cuda')
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/mnt/xxx/Megatron-LM/tools/run_mamba_text_generation_server.py", line 101, in <module>
[rank0]:     _ = load_checkpoint(model, None, None)
[rank0]:   File "/workspace/mnt/xxx/Megatron-LM/megatron/training/checkpointing.py", line 839, in load_checkpoint
[rank0]:     model[0].load_state_dict(state_dict['model'], strict=strict)
[rank0]:   File "/opt/conda/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
[rank0]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank0]: RuntimeError: Error(s) in loading state_dict for MambaModel:
[rank0]:        Missing key(s) in state_dict: "decoder.layers.0.mixer.in_proj.layer_norm_weight", "decoder.layers.0.mixer.in_proj._extra_state", "decoder.layers.0.mixer.out_proj._extra_state", "decoder.layers.2.mixer.in_proj.layer_norm_weight", "decoder.layers.2.mixer.in_proj._extra_state", "decoder.layers.2.mixer.out_proj._extra_state", "decoder.layers.4.mixer.in_proj.layer_norm_weight", "decoder.layers.4.mixer.in_proj._extra_state", "decoder.layers.4.mixer.out_proj._extra_state", "decoder.layers.7.mixer.in_proj.layer_norm_weight", "decoder.layers.7.mixer.in_proj._extra_state", "decoder.layers.7.mixer.out_proj._extra_state", "decoder.layers.9.mixer.in_proj.layer_norm_weight", "decoder.layers.9.mixer.in_proj._extra_state", "decoder.layers.9.mixer.out_proj._extra_state", "decoder.layers.12.mixer.in_proj.layer_norm_weight", "decoder.layers.12.mixer.in_proj._extra_state", "decoder.layers.12.mixer.out_proj._extra_state", "decoder.layers.14.mixer.in_proj.layer_norm_weight", "decoder.layers.14.mixer.in_proj._extra_state", "decoder.layers.14.mixer.out_proj._extra_state", "decoder.layers.16.mixer.in_proj.layer_norm_weight", "decoder.layers.16.mixer.in_proj._extra_state", "decoder.layers.16.mixer.out_proj._extra_state", "decoder.layers.18.mixer.in_proj.layer_norm_weight", "decoder.layers.18.mixer.in_proj._extra_state", "decoder.layers.18.mixer.out_proj._extra_state", "decoder.layers.21.mixer.in_proj.layer_norm_weight", "decoder.layers.21.mixer.in_proj._extra_state", "decoder.layers.21.mixer.out_proj._extra_state", "decoder.layers.24.mixer.in_proj.layer_norm_weight", "decoder.layers.24.mixer.in_proj._extra_state", "decoder.layers.24.mixer.out_proj._extra_state", "decoder.layers.26.mixer.in_proj.layer_norm_weight", "decoder.layers.26.mixer.in_proj._extra_state", "decoder.layers.26.mixer.out_proj._extra_state", "decoder.layers.28.mixer.in_proj.layer_norm_weight", "decoder.layers.28.mixer.in_proj._extra_state", "decoder.layers.28.mixer.out_proj._extra_state", "decoder.layers.30.mixer.in_proj.layer_norm_weight", "decoder.layers.30.mixer.in_proj._extra_state", "decoder.layers.30.mixer.out_proj._extra_state", "decoder.layers.32.mixer.in_proj.layer_norm_weight", "decoder.layers.32.mixer.in_proj._extra_state", "decoder.layers.32.mixer.out_proj._extra_state", "decoder.layers.36.mixer.in_proj.layer_norm_weight", "decoder.layers.36.mixer.in_proj._extra_state", "decoder.layers.36.mixer.out_proj._extra_state", "decoder.layers.38.mixer.in_proj.layer_norm_weight", "decoder.layers.38.mixer.in_proj._extra_state", "decoder.layers.38.mixer.out_proj._extra_state", "decoder.layers.40.mixer.in_proj.layer_norm_weight", "decoder.layers.40.mixer.in_proj._extra_state", "decoder.layers.40.mixer.out_proj._extra_state", "decoder.layers.42.mixer.in_proj.layer_norm_weight", "decoder.layers.42.mixer.in_proj._extra_state", "decoder.layers.42.mixer.out_proj._extra_state", "decoder.layers.44.mixer.in_proj.layer_norm_weight", "decoder.layers.44.mixer.in_proj._extra_state", "decoder.layers.44.mixer.out_proj._extra_state", "decoder.layers.47.mixer.in_proj.layer_norm_weight", "decoder.layers.47.mixer.in_proj._extra_state", "decoder.layers.47.mixer.out_proj._extra_state", "decoder.layers.50.mixer.in_proj.layer_norm_weight", "decoder.layers.50.mixer.in_proj._extra_state", "decoder.layers.50.mixer.out_proj._extra_state", "decoder.layers.52.mixer.in_proj.layer_norm_weight", "decoder.layers.52.mixer.in_proj._extra_state", "decoder.layers.52.mixer.out_proj._extra_state", "decoder.layers.54.mixer.in_proj.layer_norm_weight", "decoder.layers.54.mixer.in_proj._extra_state", "decoder.layers.54.mixer.out_proj._extra_state". 
[rank0]:        Unexpected key(s) in state_dict: "decoder.layers.0.norm.weight", "decoder.layers.2.norm.weight", "decoder.layers.4.norm.weight", "decoder.layers.7.norm.weight", "decoder.layers.9.norm.weight", "decoder.layers.12.norm.weight", "decoder.layers.14.norm.weight", "decoder.layers.16.norm.weight", "decoder.layers.18.norm.weight", "decoder.layers.21.norm.weight", "decoder.layers.24.norm.weight", "decoder.layers.26.norm.weight", "decoder.layers.28.norm.weight", "decoder.layers.30.norm.weight", "decoder.layers.32.norm.weight", "decoder.layers.36.norm.weight", "decoder.layers.38.norm.weight", "decoder.layers.40.norm.weight", "decoder.layers.42.norm.weight", "decoder.layers.44.norm.weight", "decoder.layers.47.norm.weight", "decoder.layers.50.norm.weight", "decoder.layers.52.norm.weight", "decoder.layers.54.norm.weight". 
E0110 10:25:42.590000 140450964977472 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 201340) of binary: /opt/conda/envs/mamba2/bin/python3.10



why error？

**Comment by jinghere11** [comment]
> I think the tokenizer path should point to the .model file in the huggingface repos. For example, I downloaded the `mamba2-hybrid-8b-3t-4k` repo from huggingface, and `mamba2-hybrid-8b-3t-4k/mt_nlg_plus_multilingual_ja_zh_the_stack_frac_015_256k.model` is the tokenizer. I'm running inference using `run_text_gen_server_8b.sh` and the checkpoint/tokenizer paths are
> 
> ```
> CHECKPOINT_PATH="/workspace/checkpoints/mamba2-hybrid-8b-3t-4k/"
> TOKENIZER_PATH="/workspace/checkpoints/mamba2-hybrid-8b-3t-4k/mt_nlg_plus_multilingual_ja_zh_the_stack_frac_015_256k.model"
> ```
> 
> respectively.

Have you encountered any unusual inference results like this?
The weather today is "-oppolo ( Plenosses subject As" Ext
amp Aktuqalicillinut TL GRE LOG
