### ISSUE TITLE
[BUG] the argument of parser.add_argument is wrong in tools/checkpoint/convert.py

### ISSUE THREAD

**Issue by adoda** [NVIDIA/Megatron-LM#866]
**Describe the bug**

https://github.com/NVIDIA/Megatron-LM/blob/main/tools/checkpoint/convert.py#L115

It must be 'choices=['GPT', 'BERT'],' 

not 'choice=['GPT', 'BERT'],'

**Comment by elliottnv** [comment]
This should be fixed. Please reopen if needed.
