### ISSUE TITLE
[QUESTION]when pretraining bert，meet bug：cuBLAS Error: the requested functionality is not supported

### ISSUE THREAD

**Issue by shanyuaa** [NVIDIA/Megatron-LM#876]
**Your question**
Ask a clear and concise question about Megatron-LM.

my train_bert_340m_distributed.sh(specialize part) is as follows:
CHECKPOINT_PATH=/proj/bert/checkpoints/null/
TENSORBOARD_LOGS_PATH=/proj/bert/logs
VOCAB_FILE=/proj/bert/checkpoints/bert-large-uncased-vocab.txt
DATA_PATH=/proj/bert/dataset/ag_news_text_sentence

the error is:
<img width="1335" alt="截屏2024-06-18 20 53 31" src="https://github.com/NVIDIA/Megatron-LM/assets/54535300/6bf86991-de4a-4e18-addb-727e76f77ff5">

**Comment by andrewvli** [comment]
also encountered this issue, were you able to resolve the cuBLAS error?

**Comment by shanyuaa** [comment]
你好，我已收到信件，在阅读后会尽快给回复。祝好。

**Comment by yaox12** [comment]
This https://github.com/NVIDIA/TransformerEngine/pull/845 may help. Try to install TE after this commit.

**Comment by shanyuaa** [comment]
你好，我已收到信件，在阅读后会尽快给回复。祝好。
