### ISSUE TITLE
[QUESTION] --overlap-grad-allreduce failing as gradients coming through as None in param hook

### ISSUE THREAD

**Issue by jambo6** [NVIDIA/Megatron-LM#879]
When I set `--overlap-grad-allreduce` my run fails because gradients are None inside the hook. It then fails due to this code 
```
                if self.ddp_config.overlap_grad_reduce:
                    assert (
                        param.grad is not None
                    ), 'param.grad being None is not safe when overlap_grad_reduce is True'
```

Gradients are available in the optimizer step, so its not that I'm just not computing gradients.

When I disable overlap I also find that every gradient is None inside the backwards hook.

**Comment by jambo6** [comment]
Issue on my end

**Comment by deepakn94** [comment]
What was the issue? Might be useful for other users.

**Comment by clarence-lee-sheng** [comment]
May I follow up if there is any way to solve this issue? I am getting this same error

**Comment by liangyuwang** [comment]
May I ask how you solved this problem?
