### ISSUE TITLE
AttributeError: module 'torch' has no attribute '_amp_foreach_non_finite_check_and_unscale_'

### ISSUE THREAD

**Issue by Carolingliang** [NVIDIA/Megatron-LM#90]
I use cuda 10.1, when I run both v2.0 and v2.1 release of Megatron-LM，
the code is :  bash examples/pretrain_gpt.sh
 I get a bug as follow:
![image](https://user-images.githubusercontent.com/78017166/113979715-2e95d180-9878-11eb-9721-431cf8dac0ec.png)

**Comment by szlll** [comment]
I also have this problem now. may i ask how did you deal with it?

**Comment by Lyken17** [comment]
Upgradding pytorch to >1.8.0 will resolve the problem.
