### ISSUE TITLE
How to solve the OOM problem when my vocab_size is very big

### ISSUE THREAD

**Issue by SerenaQuinn** [NVIDIA/Megatron-LM#92]
My vocab_size is about 30w, and a "cuda out of memory" error occured.
I think I should put the word_embeddings into cpu, then fetch the data and compute in gpu, then update the word_embeddings. 

> ------------------------ arguments ------------------------
  adam_beta1 ...................................... 0.9
  adam_beta2 ...................................... 0.999
  adam_eps ........................................ 1e-08
  adlr_autoresume ................................. False
  adlr_autoresume_interval ........................ 1000
  apply_query_key_layer_scaling ................... True
  apply_residual_connection_post_layernorm ........ False
  attention_dropout ............................... 0.1
  attention_softmax_in_fp32 ....................... False
  bert_load ....................................... None
  bias_dropout_fusion ............................. True
  bias_gelu_fusion ................................ True
  block_data_path ................................. None
  checkpoint_activations .......................... True
  checkpoint_num_layers ........................... 1
  clip_grad ....................................... 1.0
  consumed_train_samples .......................... 0
  consumed_valid_samples .......................... 0
  data_impl ....................................... infer
  data_parallel_size .............................. 1
  data_path ....................................... ['/data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document']
  DDP_impl ........................................ local
  distribute_checkpointed_activations ............. False
  distributed_backend ............................. nccl
  eod_mask_loss ................................... False
  eval_interval ................................... 1000
  eval_iters ...................................... 10
  exit_duration_in_mins ........................... None
  exit_interval ................................... None
  faiss_use_gpu ................................... False
  finetune ........................................ False
  fp16 ............................................ True
  fp16_lm_cross_entropy ........................... False
  fp32_allreduce .................................. False
  fp32_residual_connection ........................ False
  global_batch_size ............................... 8
  graph_file ...................................... /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_file.txt
  hidden_dropout .................................. 0.1
  hidden_size ..................................... 256
  hysteresis ...................................... 2
  ict_head_size ................................... None
  ict_load ........................................ None
  indexer_batch_size .............................. 128
  indexer_log_interval ............................ 1000
  init_method_std ................................. 0.02
  initial_loss_scale .............................. 4294967296
  layernorm_epsilon ............................... 1e-05
  lazy_mpu_init ................................... None
  load ............................................ /data/quxiaoru/Model/checkpoints/rev_gen/elec5/nei
  local_rank ...................................... None
  log_interval .................................... 100
  loss_scale ...................................... None
  loss_scale_window ............................... 1000
  lr .............................................. 0.00015
  lr_decay_iters .................................. None
  lr_decay_samples ................................ None
  lr_decay_style .................................. constant
  lr_warmup_fraction .............................. 0.01
  lr_warmup_iters ................................. 0
  lr_warmup_samples ............................... 0
  make_vocab_size_divisible_by .................... 128
  mask_prob ....................................... 0.15
  max_graph_capacity .............................. 20
  max_position_embeddings ......................... 1024
  merge_file ...................................... ../gpt2-merges.txt
  micro_batch_size ................................ 8
  min_loss_scale .................................. 1.0
  min_lr .......................................... 0.0
  mmap_warmup ..................................... False
  no_load_optim ................................... False
  no_load_rng ..................................... False
  no_resample ..................................... False
  no_save_optim ................................... False
  no_save_rng ..................................... False
  num_attention_heads ............................. 8
  num_layers ...................................... 6
  num_workers ..................................... 2
  onnx_safe ....................................... None
  openai_gelu ..................................... False
  override_lr_scheduler ........................... False
  params_dtype .................................... torch.float16
  pipeline_model_parallel_size .................... 1
  query_in_block_prob ............................. 0.1
  rampup_batch_size ............................... None
  rank ............................................ 0
  report_topk_accuracies .......................... []
  reset_attention_mask ............................ True
  reset_position_ids .............................. True
  save ............................................ /data/quxiaoru/Model/checkpoints/rev_gen/elec5/nei
  save_interval ................................... 5000
  scaled_masked_softmax_fusion .................... True
  scaled_upper_triang_masked_softmax_fusion ....... True
  seed ............................................ 1234
  seq_length ...................................... 1024
  short_seq_prob .................................. 0.1
  split ........................................... 80, 10, 10
  tensor_model_parallel_size ...................... 1
  tensorboard_dir ................................. None
  titles_data_path ................................ None
  tokenizer_type .................................. GraphBPETokenizer
  train_iters ..................................... 5000000
  train_samples ................................... None
  use_checkpoint_lr_scheduler ..................... False
  use_cpu_initialization .......................... False
  use_one_sent_docs ............................... False
  vocab_file ...................................... ../gpt2-vocab.json
  weight_decay .................................... 0.01
  world_size ...................................... 1
-------------------- end of arguments ---------------------
setting number of micro-batches to constant 1
> building GraphBPETokenizer tokenizer ...
 > padded vocab (size: 305662) with 2 dummy tokens (new size: 305664)
> initializing torch distributed ...
> initializing tensor model parallel with size 1
> initializing pipeline model parallel with size 1
> setting random seeds to 1234 ...
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
time to initialize megatron (seconds): 33.262
[after megatron is initialized] datetime: 2021-04-17 05:58:57
building GPT model ...
 > number of parameters on (tensor, pipeline) model parallel rank (0, 0): 83251200
> learning rate decay style: constant
WARNING: could not find the metadata file /data/quxiaoru/Model/checkpoints/rev_gen/elec5/nei/latest_checkpointed_iteration.txt
    will not load any checkpoints and will start from random
time (ms) | load checkpoint: 0.09
[after model, optimizer, and learning rate scheduler are built] datetime: 2021-04-17 05:58:57
> building train, validation, and test datasets ...
 > datasets target sizes (minimum size):
    train:      40000000
    validation: 400080
    test:       80
> building train, validation, and test datasets for GPT ...
 > building dataset index ...
    reading sizes...
    reading pointers...
    reading document index...
    creating numpy buffer of mmap...
    creating memory view of numpy buffer...
 > finished creating indexed dataset in 0.000469 seconds
    number of documents: 1689188
 > dataset split:
    train:
     document indices in [0, 1351350) total of 1351350 documents
    validation:
     document indices in [1351350, 1520269) total of 168919 documents
    test:
     document indices in [1520269, 1689188) total of 168919 documents
 > loading doc-idx mapping from /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document_train_indexmap_40000000ns_1024sl_1234s_doc_idx.npy
 > loading sample-idx mapping from /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document_train_indexmap_40000000ns_1024sl_1234s_sample_idx.npy
 > loading shuffle-idx mapping from /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document_train_indexmap_40000000ns_1024sl_1234s_shuffle_idx.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 40077470
    total number of epochs: 185
 > loading doc-idx mapping from /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document_valid_indexmap_400080ns_1024sl_1234s_doc_idx.npy
 > loading sample-idx mapping from /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document_valid_indexmap_400080ns_1024sl_1234s_sample_idx.npy
 > loading shuffle-idx mapping from /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document_valid_indexmap_400080ns_1024sl_1234s_shuffle_idx.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 424446
    total number of epochs: 16
 > loading doc-idx mapping from /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document_test_indexmap_80ns_1024sl_1234s_doc_idx.npy
 > loading sample-idx mapping from /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document_test_indexmap_80ns_1024sl_1234s_sample_idx.npy
 > loading shuffle-idx mapping from /data/quxiaoru/Dataset/rev_gen/elec5/nei/graph_text_document_test_indexmap_80ns_1024sl_1234s_shuffle_idx.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 32856
    total number of epochs: 1
> finished creating GPT datasets ...
[after dataloaders are built] datetime: 2021-04-17 05:58:57
done with setups ...
time (ms) | model and optimizer: 52.52 | train/valid/test data iterators: 405.21
training ...
[before the start of training step] datetime: 2021-04-17 05:58:57
Traceback (most recent call last):
  File "../pretrain_graph.py", line 98, in <module>
    'scaled_upper_triang_masked_softmax_fusion': True})
  File "/data/quxiaoru/Code/rev_gen/megatron/training.py", line 129, in pretrain
    train_data_iterator, valid_data_iterator)
  File "/data/quxiaoru/Code/rev_gen/megatron/training.py", line 808, in train
    lr_scheduler)
  File "/data/quxiaoru/Code/rev_gen/megatron/training.py", line 594, in train_step
    forward_step_func, data_iterator, model, optimizer, timers)
  File "/data/quxiaoru/Code/rev_gen/megatron/training.py", line 507, in forward_backward_no_pipelining
    loss, loss_reduced = forward_step_func(data_iterator, model, input_tensor=None)
  File "../pretrain_graph.py", line 72, in forward_step
    labels=labels)
  File "/data/quxiaoru/anaconda3/envs/torch18/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/quxiaoru/Code/rev_gen/megatron/model/distributed.py", line 76, in forward
    return self.module(*inputs, **kwargs)
  File "/data/quxiaoru/anaconda3/envs/torch18/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/quxiaoru/Code/rev_gen/megatron/model/module.py", line 140, in forward
    outputs = self.module(*inputs, **kwargs)
  File "/data/quxiaoru/anaconda3/envs/torch18/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/quxiaoru/Code/rev_gen/megatron/model/gpt_model.py", line 150, in forward
    forward_method_parallel_output=forward_method_parallel_output)
  File "/data/quxiaoru/Code/rev_gen/megatron/model/gpt_model.py", line 104, in forward
    self.fp16_lm_cross_entropy)
  File "/data/quxiaoru/Code/rev_gen/megatron/model/gpt_model.py", line 60, in post_language_model_processing
    loss = mpu.vocab_parallel_cross_entropy(output.float(), labels)
RuntimeError: CUDA out of memory. Tried to allocate 9.33 GiB (GPU 0; 10.76 GiB total capacity; 5.17 GiB already allocated; 4.48 GiB free; 5.28 GiB reserved in total by PyTorch)

**Comment by SerenaQuinn** [comment]
Does anyone know how to sovle this problem?

**Comment by floatshadow** [comment]
#60 may help, though not quite clear what makes sense for different DDP_impl
