### ISSUE TITLE
[BUG] Getting distributed rank in save_checkpoint when torch.distributed is not initialized.

### ISSUE THREAD

**Issue by haolin-nju** [NVIDIA/Megatron-LM#920]
**Describe the bug**
Regarding the code in [https://github.com/NVIDIA/Megatron-LM/blob/c7a1f82d761577e6ca0338d3521eac82f2aa0904/megatron/training/checkpointing.py#L426](https://github.com/NVIDIA/Megatron-LM/blob/c7a1f82d761577e6ca0338d3521eac82f2aa0904/megatron/training/checkpointing.py#L426)

In the case of converting a checkpoint, torch.distributed() might not have been initialized, and calling torch.distributed.get_rank() within the logger.debug will result in an exception: `Default process group has not been initialized, please make sure to call init_process_group.`

**To Reproduce**
Try converting a checkpoint as described in [https://github.com/NVIDIA/Megatron-LM/blob/c7a1f82d761577e6ca0338d3521eac82f2aa0904/examples/mixtral/README.md?plain=1#L14](https://github.com/NVIDIA/Megatron-LM/blob/c7a1f82d761577e6ca0338d3521eac82f2aa0904/examples/mixtral/README.md?plain=1#L14)

**Stack trace/logs**
```shell
...
 > padded vocab (size: 32000) with 0 dummy tokens (new size: 32000)
saving checkpoint at iteration       1 to /mnt/workspace/someone/checkpoint/mcore/Mixtral-8x7B-v0.1-tp1-pp1-ep1 in torch format
  successfully saved checkpoint from iteration       1 to /mnt/workspace/someone/checkpoint/mcore/Mixtral-8x7B-v0.1-tp1-pp1-ep1
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/workspace/someone/Megatron-LM/tools/checkpoint/saver_mcore.py", line 789, in save_checkpoint
    save_checkpoint(md.iteration, [get_local_model(pp_rank, ep_rank, tp_rank)], None, None, num_floating_point_operations_so_far=0,
  File "/mnt/workspace/someone/Megatron-LM/megatron/training/checkpointing.py", line 426, in save_checkpoint
    logger.debug(f"rank: {torch.distributed.get_rank()}, takes {end_misc - start_misc} to finalize ckpt save ")
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1507, in get_rank
    default_pg = _get_default_group()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 958, in _get_default_group
    raise ValueError(
ValueError: Default process group has not been initialized, please make sure to call init_process_group.
```

**Proposed fix**
Adding `if torch.distributed.is_initialized()`.

**Comment by ericharper** [comment]
This seems to be the same as #911

**Comment by jon-barker** [comment]
@ericharper it is, I'm working on a fix

**Comment by jon-barker** [comment]
We have implemented a fix internally and it will be pushed out to github later this week.

**Comment by Ethan-yt** [comment]
I have created a PR to fix this issue. For those who wants a quick fix, you can clone my fork.
https://github.com/NVIDIA/Megatron-LM/pull/923

**Comment by jon-barker** [comment]
This is now fixed in main

**Comment by jon-barker** [comment]
Now fixed in main
