### ISSUE TITLE
[QUESTION] Why Megatron choose sync style training?

### ISSUE THREAD

**Issue by MaCasK9** [NVIDIA/Megatron-LM#922]
**Your question**
Ask a clear and concise question about Megatron-LM.

Hello, I've noticed that Megatron is running in a sync style (i.e. SSGD/BSP). To my knowledge, this method works well in homogeneous setting, but suffers from heterogeneity of FLOPS/s, bandwith etc.. So I'm wondering why Megatron choose to only support sync style? Is it rare to see a heterogeneous env so there is no much need for async support? Really appreciate for any answers.

**Comment by shanmugamr1992** [comment]
Hi  MaCask, megatron mainly focuses on Homogenous training setting as you rightly pointed since heterogenous is quite rare. Its not on our roadmap either in the short term.
