### ISSUE TITLE
[BUG] Failed to load the megatron_mixtral checkpoint

### ISSUE THREAD

**Issue by kumulaor** [NVIDIA/Megatron-LM#924]
**Describe the bug**
After converting the weights using the following code, I get an error when I use examples/mixtral/train_mixtral_8x7b_distributed.sh to load the model weights:
`export CUDA_DEVICE_MAX_CONNECTIONS=1

python tools/checkpoint/convert.py \
--model-type GPT \
--loader mixtral_hf \
--saver mcore \
--target-tensor-parallel-size 4 \
--target-pipeline-parallel-size 1 \
--target-expert-parallel-size 4 \
--load-dir /workspace/mixtral/model/ \
--save-dir /workspace/mixtral/model_4tp1pp4ep/ \
--tokenizer-model /workspace/mixtral/model/tokenizer.model`

**Expected behavior**
use the alpaca dataset to fine tune the moe mixtral

**Stack trace/logs**
[rank3]: Traceback (most recent call last):
[rank3]:   File "/workspace/Megatron-LM/pretrain_gpt.py", line 245, in <module>
[rank3]:     pretrain(
[rank3]:   File "/workspace/Megatron-LM/megatron/training/training.py", line 234, in pretrain
[rank3]:     model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
[rank3]:   File "/workspace/Megatron-LM/megatron/training/training.py", line 553, in setup_model_and_optimizer
[rank3]:     args.iteration, args.num_floating_point_operations_so_far = load_checkpoint(
[rank3]:   File "/workspace/Megatron-LM/megatron/training/checkpointing.py", line 840, in load_checkpoint
[rank3]:     model[0].load_state_dict(state_dict['model'], strict=strict)
[rank3]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2182, in load_state_dict
[rank3]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank3]: RuntimeError: Error(s) in loading state_dict for GPTModel:
[rank3]:        Missing key(s) in state_dict: "decoder.layers.0.mlp.experts.weight1", "decoder.layers.0.mlp.experts.weight2", "decoder.layers.1.mlp.experts.weight1", "decoder.layers.1.mlp.experts.weight2", "decoder.layers.2.mlp.experts.weight1", "decoder.layers.2.mlp.experts.weight2", "decoder.layers.3.mlp.experts.weight1", "decoder.layers.3.mlp.experts.weight2", "decoder.layers.4.mlp.experts.weight1", "decoder.layers.4.mlp.experts.weight2", "decoder.layers.5.mlp.experts.weight1", "decoder.layers.5.mlp.experts.weight2", "decoder.layers.6.mlp.experts.weight1", "decoder.layers.6.mlp.experts.weight2", "decoder.layers.7.mlp.experts.weight1", "decoder.layers.7.mlp.experts.weight2", "decoder.layers.8.mlp.experts.weight1", "decoder.layers.8.mlp.experts.weight2", "decoder.layers.9.mlp.experts.weight1", "decoder.layers.9.mlp.experts.weight2", "decoder.layers.10.mlp.experts.weight1", "decoder.layers.10.mlp.experts.weight2", "decoder.layers.11.mlp.experts.weight1", "decoder.layers.11.mlp.experts.weight2", "decoder.layers.12.mlp.experts.weight1", "decoder.layers.12.mlp.experts.weight2", "decoder.layers.13.mlp.experts.weight1", "decoder.layers.13.mlp.experts.weight2", "decoder.layers.14.mlp.experts.weight1", "decoder.layers.14.mlp.experts.weight2", "decoder.layers.15.mlp.experts.weight1", "decoder.layers.15.mlp.experts.weight2", "decoder.layers.16.mlp.experts.weight1", "decoder.layers.16.mlp.experts.weight2", "decoder.layers.17.mlp.experts.weight1", "decoder.layers.17.mlp.experts.weight2", "decoder.layers.18.mlp.experts.weight1", "decoder.layers.18.mlp.experts.weight2", "decoder.layers.19.mlp.experts.weight1", "decoder.layers.19.mlp.experts.weight2", "decoder.layers.20.mlp.experts.weight1", "decoder.layers.20.mlp.experts.weight2", "decoder.layers.21.mlp.experts.weight1", "decoder.layers.21.mlp.experts.weight2", "decoder.layers.22.mlp.experts.weight1", "decoder.layers.22.mlp.experts.weight2", "decoder.layers.23.mlp.experts.weight1", "decoder.layers.23.mlp.experts.weight2", "decoder.layers.24.mlp.experts.weight1", "decoder.layers.24.mlp.experts.weight2", "decoder.layers.25.mlp.experts.weight1", "decoder.layers.25.mlp.experts.weight2", "decoder.layers.26.mlp.experts.weight1", "decoder.layers.26.mlp.experts.weight2", "decoder.layers.27.mlp.experts.weight1", "decoder.layers.27.mlp.experts.weight2", "decoder.layers.28.mlp.experts.weight1", "decoder.layers.28.mlp.experts.weight2", "decoder.layers.29.mlp.experts.weight1", "decoder.layers.29.mlp.experts.weight2", "decoder.layers.30.mlp.experts.weight1", "decoder.layers.30.mlp.experts.weight2", "decoder.layers.31.mlp.experts.weight1", "decoder.layers.31.mlp.experts.weight2". 
[rank3]:        Unexpected key(s) in state_dict: "decoder.layers.0.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.0.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.0.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.0.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.1.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.1.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.1.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.1.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.2.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.2.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.2.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.2.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.3.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.3.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.3.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.3.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.4.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.4.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.4.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.4.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.5.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.5.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.5.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.5.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.6.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.6.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.6.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.6.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.7.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.7.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.7.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.7.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.8.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.8.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.8.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.8.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.9.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.9.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.9.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.9.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.10.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.10.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.10.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.10.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.11.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.11.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.11.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.11.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.12.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.12.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.12.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.12.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.13.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.13.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.13.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.13.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.14.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.14.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.14.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.14.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.15.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.15.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.15.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.15.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.16.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.16.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.16.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.16.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.17.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.17.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.17.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.17.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.18.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.18.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.18.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.18.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.19.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.19.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.19.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.19.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.20.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.20.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.20.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.20.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.21.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.21.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.21.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.21.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.22.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.22.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.22.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.22.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.23.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.23.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.23.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.23.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.24.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.24.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.24.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.24.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.25.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.25.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.25.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.25.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.26.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.26.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.26.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.26.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.27.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.27.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.27.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.27.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.28.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.28.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.28.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.28.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.29.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.29.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.29.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.29.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.30.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.30.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.30.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.30.mlp.experts.local_experts.1.linear_fc2.weight", "decoder.layers.31.mlp.experts.local_experts.0.linear_fc1.weight", "decoder.layers.31.mlp.experts.local_experts.0.linear_fc2.weight", "decoder.layers.31.mlp.experts.local_experts.1.linear_fc1.weight", "decoder.layers.31.mlp.experts.local_experts.1.linear_fc2.weight". 

**Environment (please complete the following information):**
 - Megatron-LM commit ID nvcr.io/nvidia/pytorch:24.04-py3
 - PyTorch version 2.3.0a0+6ddf5cf85e.nv24.4
 - CUDA version 12.1
 - NCCL version 2.21.5

**Comment by Wangyongdi** [comment]
May I ask how it was resolved

**Comment by kumulaor** [comment]
> May I ask how it was resolved

This issue is due to the setting of the parameter --moe grouped gemm in the moe args of the mixtral model in train_mixtral_8x7b_distributed.sh。When using -- moe grouped gemm, the type of experts in MoELayer is GroupedMLP, and the type of experts in the checkpoint is SequentialMLP。I fixed it by deleting --moe grouped gemm。
