### ISSUE TITLE
[BUG]RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by wccccp** [NVIDIA/Megatron-LM#942]
Traceback (most recent call last):
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/./pretrain_gpt.py", line 263, in <module>
[rank2]:     pretrain(train_valid_test_datasets_provider,
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/training.py", line 170, in pretrain
[rank2]:     iteration = train(forward_step_func,
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/training.py", line 812, in train
[rank2]:     train_step(forward_step_func,
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/training.py", line 454, in train_step
[rank2]:     losses_reduced = forward_backward_func(
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 327, in forward_backward_no_pipelining
[rank2]:     output_tensor = forward_step(
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 183, in forward_step
[rank2]:     output_tensor, loss_func = forward_step_func(data_iterator, model)
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/./pretrain_gpt.py", line 218, in forward_step
[rank2]:     output_tensor = model(tokens, position_ids, attention_mask,
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/core/distributed.py", line 287, in forward
[rank2]:     return self.module(*inputs, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/model/module.py", line 181, in forward
[rank2]:     outputs = self.module(*inputs, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/model/gpt_model.py", line 83, in forward
[rank2]:     lm_output = self.language_model(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/model/language_model.py", line 487, in forward
[rank2]:     rotary_pos_emb = self.rotary_pos_emb(self.seq_length)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/workspace/megatron/wcp/test_mega/Megatron-LM/megatron/core/models/common/embeddings/rotary_pos_embedding.py", line 89, in forward
[rank2]:     emb = torch.cat((freqs, freqs), dim=-1)
[rank2]: RuntimeError: CUDA error: device-side assert triggered
[rank2]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank2]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank2]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by ericharper** [comment]
When creating an issue please use the template.
