### ISSUE TITLE
[BUG] MoE Router TopK algorithm is differeent from huggingface implement

### ISSUE THREAD

**Issue by Au3C2** [NVIDIA/Megatron-LM#955]
**Describe the bug**
In [Megatron](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/transformer/moe/moe_utils.py#L310):topk_softmax_with_capacity()

```python
    scores, top_indices = torch.topk(logits, k=topk, dim=1)     # topk first
    probs = torch.softmax(scores, dim=-1, dtype=torch.float32).type_as(logits)
```

In [transformers-mixtral](https://github.com/huggingface/transformers/blob/8da90687308a10b33c5553b8a506cc04aab31702/src/transformers/models/mixtral/modeling_mixtral.py#L662):MixtralSparseMoeBlock

```python
        routing_weights = F.softmax(router_logits, dim=1, dtype=torch.float)
        routing_weights, selected_experts = torch.topk(routing_weights, self.top_k, dim=-1
```

This two algorithm result in two different inference anser.

Is there any reason why megatron calculate probs like this?

**To Reproduce**
Steps to reproduce the behavior. The easier it is to reproduce the faster it will get maintainer attention.

**Expected behavior**

**Stack trace/logs**
If applicable, add the stack trace or logs from the time of the error.

**Environment (please complete the following information):**
 - Megatron-LM commit ID
 - PyTorch version
 - CUDA version
 - NCCL version

**Proposed fix**
If you have a proposal for how to fix the issue state it here or link to a PR.

**Additional context**

**Comment by kiddyboots216** [comment]
See https://github.com/NVIDIA/Megatron-LM/issues/894#issuecomment-2212765002
