### ISSUE TITLE
Error in README file

### ISSUE THREAD

**Issue by leenldk** [NVIDIA/Megatron-LM#96]
I believe there is an error in README. In subsection "Downloading Checkpoints", the command for downloading BERT-345M-uncased model should be wget from site "https://api.ngc.nvidia.com/v2/models/nvidia/megatron_bert_345m/versions/v0.1_uncased/zip" instead of "https://api.ngc.nvidia.com/v2/models/nvidia/megatron_bert_345m/versions/v0.1_cased/zip". You mistyped "uncased" to "cased".

**Comment by jon-barker** [comment]
Fixed here: https://github.com/NVIDIA/Megatron-LM/commit/26b49aab4fd18f8ae1defd22eb8f813a7b35704f
