### ISSUE TITLE
how to export the gpt2 to onnx model? 

### ISSUE THREAD

**Issue by HuuY** [NVIDIA/Megatron-LM#99]
Hi, could you please tell me how I can export gpt2 to onnx model? Is there a protobuf limitition of 2GB? I have already run the inference code of gpt2 based on megatron with nvidia V100, and I try to export a onnx file.  But it is said that:

''RuntimeError: Exporting model exceed maximum protobuf size of 2GB. Please call torch.onnx.export with use_external_data_format=True.''

When I did so, the onnx model was exported as lots of weight files, and it can not be used with onnxruntime to inference. Can anyone help me? Thanks a lot.

**Comment by lucasjinreal** [comment]
@HuuY for large models, like bigger than 2 GB, you should make weights standalone. Can you share how do you exported GPT2 to onnx?
