### ISSUE TITLE
[QUESTION] How to freeze specific modules while training?

### ISSUE THREAD

**Issue by wavy-jung** [NVIDIA/Megatron-LM#994]
Hi, I want to continually pretrain llama-series of models, while freezing self-attention layer.
I just found out that simply set `requires_grad = False` does not work for the purpose (raised some errors while debugging).
How can I update the model parameters except for specific layer? (including the scenario when tensor parallel is applied)

**Comment by wavy-jung** [comment]
I found the solution while I was exploring the training script for llava model.

**Comment by zixianwang2022** [comment]
Hi @wavy-jung, 

I am also facing a similar situation. Could you direct me on finding how to freeze some part of the model while training?

**Comment by zixianwang2022** [comment]
> Hi [@wavy-jung](https://github.com/wavy-jung),
> 
> I am also facing a similar situation. Could you direct me on finding how to freeze some part of the model while training?

Nvm! I found it!

**Comment by huangk10** [comment]
> > Hi [@wavy-jung](https://github.com/wavy-jung),
> > I am also facing a similar situation. Could you direct me on finding how to freeze some part of the model while training?
> 
> Nvm! I found it!

May I ask where can i found it

**Comment by zixianwang2022** [comment]
> > > Hi [@wavy-jung](https://github.com/wavy-jung),
> > > I am also facing a similar situation. Could you direct me on finding how to freeze some part of the model while training?
> > 
> > 
> > Nvm! I found it!
> 
> May I ask where can i found it

Here is what I did before. This is for Mamba. What model you were using?

```
    def freeze(
        self, 
        freeze_mamba_model: bool, 
        freeze_embedding_model:bool, 
        freeze_output_layer:bool, 
        unfreeze_decoder_last_layer: bool = False,
    ):
        """
        Zixian: Sept 8 19:11pm VERIFIED functionality 
        
        Freeze model modules. 

        Make specific modules non-trainable by setting requires_grad to False for the module's parameters.

        Args:
        freeze_mamba_model (bool): Freeze the entire decoder module.
        freeze_embedding_model (bool): Freeze the embedding module.
        freeze_output_layer (bool): Freeze the output layer.
        unfreeze_decoder_last_layer (bool): Unfreeze decoder's last layer. 
        
        """
        
        # for l in range(self.model.decoder.num_layers_per_pipeline_rank):
        #     layer_params = count_parameters_in_layer(model, f'decoder.layers.{l}.')
        modules = []
        if freeze_mamba_model:
            modules.append(self.decoder)
        if freeze_embedding_model:
            # Zixian: Prevent second host triggerring errors for hosting model only 
            if self.pre_process:
                modules.append(self.embedding)
        if freeze_output_layer:
            # Zixian: Prevent second host triggerring errors for hosting model only 
            if self.post_process:
                modules.append(self.output_layer)
        
        # Update Sept 7 22:12pm Not tested yet. 
        # TODO: if does not work, follow similar method in counting params 
        for module in modules:
            print (f' \n\n freezing {module} \n\n')
            for param in module.parameters():
                param.requires_grad = False

```

**Comment by huangk10** [comment]
> > > > Hi [@wavy-jung](https://github.com/wavy-jung),
> > > > I am also facing a similar situation. Could you direct me on finding how to freeze some part of the model while training?
> > > 
> > > 
> > > Nvm! I found it!
> > 
> > 
> > May I ask where can i found it
> 
> Here is what I did before. This is for Mamba. What model you were using?
> 
> ```
>     def freeze(
>         self, 
>         freeze_mamba_model: bool, 
>         freeze_embedding_model:bool, 
>         freeze_output_layer:bool, 
>         unfreeze_decoder_last_layer: bool = False,
>     ):
>         """
>         Zixian: Sept 8 19:11pm VERIFIED functionality 
>         
>         Freeze model modules. 
> 
>         Make specific modules non-trainable by setting requires_grad to False for the module's parameters.
> 
>         Args:
>         freeze_mamba_model (bool): Freeze the entire decoder module.
>         freeze_embedding_model (bool): Freeze the embedding module.
>         freeze_output_layer (bool): Freeze the output layer.
>         unfreeze_decoder_last_layer (bool): Unfreeze decoder's last layer. 
>         
>         """
>         
>         # for l in range(self.model.decoder.num_layers_per_pipeline_rank):
>         #     layer_params = count_parameters_in_layer(model, f'decoder.layers.{l}.')
>         modules = []
>         if freeze_mamba_model:
>             modules.append(self.decoder)
>         if freeze_embedding_model:
>             # Zixian: Prevent second host triggerring errors for hosting model only 
>             if self.pre_process:
>                 modules.append(self.embedding)
>         if freeze_output_layer:
>             # Zixian: Prevent second host triggerring errors for hosting model only 
>             if self.post_process:
>                 modules.append(self.output_layer)
>         
>         # Update Sept 7 22:12pm Not tested yet. 
>         # TODO: if does not work, follow similar method in counting params 
>         for module in modules:
>             print (f' \n\n freezing {module} \n\n')
>             for param in module.parameters():
>                 param.requires_grad = False
> ```

I am working on Llama 7B, I don't know if this method will work.

**Comment by huangk10** [comment]
> > > > Hi [@wavy-jung](https://github.com/wavy-jung),
> > > > I am also facing a similar situation. Could you direct me on finding how to freeze some part of the model while training?
> > > 
> > > 
> > > Nvm! I found it!
> > 
> > 
> > May I ask where can i found it
> 
> Here is what I did before. This is for Mamba. What model you were using?
> 
> ```
>     def freeze(
>         self, 
>         freeze_mamba_model: bool, 
>         freeze_embedding_model:bool, 
>         freeze_output_layer:bool, 
>         unfreeze_decoder_last_layer: bool = False,
>     ):
>         """
>         Zixian: Sept 8 19:11pm VERIFIED functionality 
>         
>         Freeze model modules. 
> 
>         Make specific modules non-trainable by setting requires_grad to False for the module's parameters.
> 
>         Args:
>         freeze_mamba_model (bool): Freeze the entire decoder module.
>         freeze_embedding_model (bool): Freeze the embedding module.
>         freeze_output_layer (bool): Freeze the output layer.
>         unfreeze_decoder_last_layer (bool): Unfreeze decoder's last layer. 
>         
>         """
>         
>         # for l in range(self.model.decoder.num_layers_per_pipeline_rank):
>         #     layer_params = count_parameters_in_layer(model, f'decoder.layers.{l}.')
>         modules = []
>         if freeze_mamba_model:
>             modules.append(self.decoder)
>         if freeze_embedding_model:
>             # Zixian: Prevent second host triggerring errors for hosting model only 
>             if self.pre_process:
>                 modules.append(self.embedding)
>         if freeze_output_layer:
>             # Zixian: Prevent second host triggerring errors for hosting model only 
>             if self.post_process:
>                 modules.append(self.output_layer)
>         
>         # Update Sept 7 22:12pm Not tested yet. 
>         # TODO: if does not work, follow similar method in counting params 
>         for module in modules:
>             print (f' \n\n freezing {module} \n\n')
>             for param in module.parameters():
>                 param.requires_grad = False
> ```

PS where should i call the freeze function

**Comment by zixianwang2022** [comment]
> > > > > Hi [@wavy-jung](https://github.com/wavy-jung),
> > > > > I am also facing a similar situation. Could you direct me on finding how to freeze some part of the model while training?
> > > > 
> > > > 
> > > > Nvm! I found it!
> > > 
> > > 
> > > May I ask where can i found it
> > 
> > 
> > Here is what I did before. This is for Mamba. What model you were using?
> > ```
> >     def freeze(
> >         self, 
> >         freeze_mamba_model: bool, 
> >         freeze_embedding_model:bool, 
> >         freeze_output_layer:bool, 
> >         unfreeze_decoder_last_layer: bool = False,
> >     ):
> >         """
> >         Zixian: Sept 8 19:11pm VERIFIED functionality 
> >         
> >         Freeze model modules. 
> > 
> >         Make specific modules non-trainable by setting requires_grad to False for the module's parameters.
> > 
> >         Args:
> >         freeze_mamba_model (bool): Freeze the entire decoder module.
> >         freeze_embedding_model (bool): Freeze the embedding module.
> >         freeze_output_layer (bool): Freeze the output layer.
> >         unfreeze_decoder_last_layer (bool): Unfreeze decoder's last layer. 
> >         
> >         """
> >         
> >         # for l in range(self.model.decoder.num_layers_per_pipeline_rank):
> >         #     layer_params = count_parameters_in_layer(model, f'decoder.layers.{l}.')
> >         modules = []
> >         if freeze_mamba_model:
> >             modules.append(self.decoder)
> >         if freeze_embedding_model:
> >             # Zixian: Prevent second host triggerring errors for hosting model only 
> >             if self.pre_process:
> >                 modules.append(self.embedding)
> >         if freeze_output_layer:
> >             # Zixian: Prevent second host triggerring errors for hosting model only 
> >             if self.post_process:
> >                 modules.append(self.output_layer)
> >         
> >         # Update Sept 7 22:12pm Not tested yet. 
> >         # TODO: if does not work, follow similar method in counting params 
> >         for module in modules:
> >             print (f' \n\n freezing {module} \n\n')
> >             for param in module.parameters():
> >                 param.requires_grad = False
> > ```
> 
> PS where should i call the freeze function

There is a `mamba_model.py`, which serves as the main function to run training. I assume there will be a similar file for llama. Just include it before running forward.

**Comment by huangk10** [comment]
> > > > > > Hi [@wavy-jung](https://github.com/wavy-jung),
> > > > > > I am also facing a similar situation. Could you direct me on finding how to freeze some part of the model while training?
> > > > > 
> > > > > 
> > > > > Nvm! I found it!
> > > > 
> > > > 
> > > > May I ask where can i found it
> > > 
> > > 
> > > Here is what I did before. This is for Mamba. What model you were using?
> > > ```
> > >     def freeze(
> > >         self, 
> > >         freeze_mamba_model: bool, 
> > >         freeze_embedding_model:bool, 
> > >         freeze_output_layer:bool, 
> > >         unfreeze_decoder_last_layer: bool = False,
> > >     ):
> > >         """
> > >         Zixian: Sept 8 19:11pm VERIFIED functionality 
> > >         
> > >         Freeze model modules. 
> > > 
> > >         Make specific modules non-trainable by setting requires_grad to False for the module's parameters.
> > > 
> > >         Args:
> > >         freeze_mamba_model (bool): Freeze the entire decoder module.
> > >         freeze_embedding_model (bool): Freeze the embedding module.
> > >         freeze_output_layer (bool): Freeze the output layer.
> > >         unfreeze_decoder_last_layer (bool): Unfreeze decoder's last layer. 
> > >         
> > >         """
> > >         
> > >         # for l in range(self.model.decoder.num_layers_per_pipeline_rank):
> > >         #     layer_params = count_parameters_in_layer(model, f'decoder.layers.{l}.')
> > >         modules = []
> > >         if freeze_mamba_model:
> > >             modules.append(self.decoder)
> > >         if freeze_embedding_model:
> > >             # Zixian: Prevent second host triggerring errors for hosting model only 
> > >             if self.pre_process:
> > >                 modules.append(self.embedding)
> > >         if freeze_output_layer:
> > >             # Zixian: Prevent second host triggerring errors for hosting model only 
> > >             if self.post_process:
> > >                 modules.append(self.output_layer)
> > >         
> > >         # Update Sept 7 22:12pm Not tested yet. 
> > >         # TODO: if does not work, follow similar method in counting params 
> > >         for module in modules:
> > >             print (f' \n\n freezing {module} \n\n')
> > >             for param in module.parameters():
> > >                 param.requires_grad = False
> > > ```
> > 
> > 
> > PS where should i call the freeze function
> 
> There is a `mamba_model.py`, which serves as the main function to run training. I assume there will be a similar file for llama. Just include it before running forward.

i see, THX
